-- Synthetic tenants only. Never use production customer sales as test fixtures.
begin;
do $$
declare owner_id uuid:=gen_random_uuid(); other_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid();
 r uuid; b uuid; other_b uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); stock uuid:=gen_random_uuid(); menu uuid:=gen_random_uuid();
 d uuid; d2 uuid; v jsonb; c jsonb; h jsonb; receipt jsonb; pair jsonb; pair2 jsonb; request uuid:=gen_random_uuid(); payload jsonb; n numeric; denied boolean;
begin
 insert into auth.users(id,email,raw_user_meta_data) values
 (owner_id,'restaurant-pos-'||owner_id||'@example.invalid','{"role":"owner","business_type":"restaurant","full_name":"POS fixture","company_name":"POS test","branch_name":"Test branch"}'),
 (other_id,'restaurant-other-'||other_id||'@example.invalid','{"role":"owner","business_type":"retail","full_name":"Other","company_name":"Isolation","branch_name":"Other"}'),
 (staff_id,'restaurant-staff-'||staff_id||'@example.invalid','{"role":"owner","business_type":"restaurant","full_name":"Staff","company_name":"Temporary","branch_name":"Temporary"}');
 select restaurant_id,branch_id into r,b from public.erp_memberships where user_id=owner_id;
 insert into public.subscriptions(restaurant_id,subscription_status,plan,trial_end) values(r,'TRIAL','growth_40',current_date+7)
 on conflict(restaurant_id) where restaurant_id is not null do update set subscription_status='TRIAL',plan='growth_40',trial_end=current_date+7;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 insert into public.branches(id,restaurant_id,branch_key,name) values(other_b,r,other_b::text,'Second branch');
 update public.erp_memberships set restaurant_id=r,branch_id=other_b,role='employee',permissions='{"viewSales":true,"uploadSales":true,"viewOrders":true}' where user_id=staff_id;
 insert into public.products(id,restaurant_id,product_id,name,name_ar,is_active) values(p,r,'FOOD-'||p,'Half chicken','نصف دجاج',true);
 insert into public.inventory(id,restaurant_id,branch_id,branch,product_id,product_name,quantity,unit,average_cost) values(stock,r,b,b::text,p::text,'Raw chicken',10,'kg',8);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 set local role authenticated;
 perform public.erp_restaurant_pos_setup(r,b,'devices','{"count":2}');
 perform public.erp_restaurant_pos_setup(r,b,'devices','{"count":2}');
 v:=public.erp_restaurant_pos_workspace(r,b,current_date);
 assert jsonb_array_length(v->'devices')=2,'Device creation is not idempotent';
 d:=(v->'devices'->0->>'id')::uuid;d2:=(v->'devices'->1->>'id')::uuid;
 payload:=jsonb_build_object('id',menu,'product_id',p,'name','Half chicken','name_ar','نصف دجاج','price',11.5,'tax_rate',15,'stock_mode','recipe','recipe',jsonb_build_array(jsonb_build_object('inventory_id',stock,'quantity',0.25)));
 perform public.erp_restaurant_pos_setup(r,b,'menu',payload);
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,other_b,'menu',payload);exception when others then denied:=true;end;
 assert denied,'Cross-branch ingredient configuration allowed';
 v:=public.erp_restaurant_cashier_command(d,'open_shift','{"cashier_name":"Fixture","opening_cash":100}',gen_random_uuid());
 v:=public.erp_restaurant_cashier_command(d,'new_sale','{}',gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',menu,'quantity',3,'unit_price',0.01),gen_random_uuid());c:=v->'cart';
 assert (c->>'net_total')::numeric=34.5 and (c->>'tax_total')::numeric=4.5,'Canonical price or included tax failed';
 assert not ((c->'lines'->0) ? 'recipe'),'Cashier leaks raw recipe stock ids';
 reset role;
 select quantity into n from public.inventory where id=stock; assert n=10,'Cart prematurely consumed stock';
 set local role authenticated;
 denied:=false;begin perform public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',0,'menu_id',menu,'quantity',4),gen_random_uuid());exception when serialization_failure then denied:=true;end;
 assert denied,'Stale revision accepted';
 v:=public.erp_restaurant_cashier_command(d,'hold',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());h:=v->'held'->0;
 v:=public.erp_restaurant_cashier_command(d,'resume',jsonb_build_object('cart_id',h->'id','revision',h->'revision'),gen_random_uuid());c:=v->'cart';
 pair:=public.erp_restaurant_cashier_command(d,'pair_display','{}',gen_random_uuid());
 set local role anon;
 v:=public.erp_restaurant_customer_display(pair->>'token');
 assert (v->>'net_total')::numeric=34.5 and not(v ? 'cashier_id') and not(v::text like '%inventory_id%'),'Customer allowlist failed';
 denied:=false;begin perform public.erp_restaurant_cashier_snapshot(d);exception when insufficient_privilege then denied:=true;end;assert denied,'Anonymous cashier access';
 set local role authenticated;
 pair2:=public.erp_restaurant_cashier_command(d,'pair_display','{}',gen_random_uuid());
 denied:=false;begin perform public.erp_restaurant_customer_display(pair->>'token');exception when insufficient_privilege then denied:=true;end;assert denied,'Display rotation failed';
 v:=public.erp_restaurant_cashier_command(d,'send_kitchen',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());c:=v->'cart';
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=9.25,'Recipe consumption failed';
 select count(*) into n from public.daily_sales where reference_id='restaurant-pos:'||(c->>'id');assert n=0,'Unpaid order counted as sales';
 set local role authenticated;
 perform public.erp_restaurant_pos_kitchen((c->>'id')::uuid,(c->>'revision')::integer,'preparing');
 v:=public.erp_restaurant_cashier_snapshot(d);c:=v->'cart';
 perform public.erp_restaurant_pos_kitchen((c->>'id')::uuid,(c->>'revision')::integer,'ready');
 v:=public.erp_restaurant_cashier_snapshot(d);c:=v->'cart';
 denied:=false;begin perform public.erp_restaurant_pos_kitchen((c->>'id')::uuid,(c->>'revision')::integer,'served');exception when check_violation then denied:=true;end;assert denied,'Unpaid food handed over';
 payload:=jsonb_build_object('cart_id',c->'id','revision',c->'revision','payment_confirmed',true,'payments','[{"payment_method":"cash","amount":20},{"payment_method":"card","amount":20}]'::jsonb);
 v:=public.erp_restaurant_cashier_command(d,'checkout',payload,request);receipt:=v->'receipt';
 assert (receipt->>'change')::numeric=5.5,'Split payment change incorrect';
 perform public.erp_restaurant_cashier_command(d,'checkout',payload,request);
 perform public.erp_restaurant_cashier_command(d,'checkout',payload,gen_random_uuid());
 v:=public.erp_restaurant_cashier_snapshot(d);assert (v->>'expected_cash')::numeric=114.5,'Expected cash incorrect';
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=9.25,'Checkout double-consumed ingredients';
 select count(*) into n from public.daily_sales where reference_id='restaurant-pos:'||(c->>'id');assert n=1,'Duplicate sale posting';
 select total into n from public.daily_sales where reference_id='restaurant-pos:'||(c->>'id');assert n=34.5,'Owner financial bridge missing';
 set local role authenticated;
 denied:=false;begin update public.daily_sales set restaurant_cash=0 where id=(receipt->>'id')::uuid;exception when insufficient_privilege then denied:=true;end;assert denied,'POS sales editable through legacy closing';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);
 denied:=false;begin perform public.erp_restaurant_cashier_snapshot(d);exception when insufficient_privilege then denied:=true;end;assert denied,'Cross-branch access';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',other_id,'role','authenticated')::text,true);
 denied:=false;begin perform public.erp_restaurant_pos_workspace(r,b,current_date);exception when insufficient_privilege then denied:=true;end;assert denied,'Cross-tenant access';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 v:=public.erp_restaurant_cashier_command(d,'new_sale','{}',gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',menu,'quantity',50),gen_random_uuid());c:=v->'cart';
 denied:=false;begin perform public.erp_restaurant_cashier_command(d,'send_kitchen',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());exception when check_violation then denied:=true;end;assert denied,'Ingredient overselling allowed';
 v:=public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',menu,'quantity',1),gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d,'send_kitchen',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());c:=v->'cart';
 denied:=false;begin perform public.erp_restaurant_cashier_command(d,'close_shift','{"counted_cash":114.5}',gen_random_uuid());exception when check_violation then denied:=true;end;assert denied,'Shift closed with unpaid food';
 v:=public.erp_restaurant_cashier_command(d,'cancel',jsonb_build_object('cart_id',c->'id','revision',c->'revision','reason','Synthetic prepared cancellation'),gen_random_uuid());
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=9,'Prepared cancellation restored raw stock';
 select sum(quantity) into n from restaurant_pos_private.consumption where order_id=(c->>'id')::uuid and wasted;assert n=0.25,'Prepared waste missing';
 set local role authenticated;
 perform public.erp_restaurant_cashier_command(d,'close_shift','{"counted_cash":114.5}',gen_random_uuid());
 denied:=false;begin perform public.erp_restaurant_customer_display(pair2->>'token');exception when insufficient_privilege then denied:=true;end;assert denied,'Closed shift display still visible';
 reset role;
 select count(*) into n from public.daily_sales where restaurant_id=r::text and reference_id like 'restaurant-pos:%';assert n=1,'Shift closing posted duplicate sales';
end $$;
rollback;
