-- Synthetic tenants only. Never use production customer sales as test fixtures.
begin;
do $$
declare owner_id uuid:=gen_random_uuid(); other_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid();
 r uuid; b uuid; other_b uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); dish uuid; stock uuid:=gen_random_uuid(); menu uuid:=gen_random_uuid();
 purchase_category uuid:=gen_random_uuid(); category uuid:=gen_random_uuid(); foreign_category uuid:=gen_random_uuid(); batch jsonb; batch_item jsonb; keys text[]:=array['whole_rice','whole_plain','half_rice','half_plain','quarter_rice','quarter_plain']; ix integer; d uuid; d2 uuid; whole_menu uuid:=gen_random_uuid(); v jsonb; c jsonb; h jsonb; receipt jsonb; pair jsonb; pair2 jsonb; request uuid:=gen_random_uuid(); payload jsonb; n numeric; denied boolean;
begin
 insert into auth.users(id,email,raw_user_meta_data) values
 (owner_id,'restaurant-pos-'||owner_id||'@example.invalid','{"role":"owner","business_type":"restaurant","full_name":"POS fixture","company_name":"POS test","branch_name":"Test branch"}'),
 (other_id,'restaurant-other-'||other_id||'@example.invalid','{"role":"owner","business_type":"retail","full_name":"Other","company_name":"Isolation","branch_name":"Other"}'),
 (staff_id,'restaurant-staff-'||staff_id||'@example.invalid','{"role":"owner","business_type":"restaurant","full_name":"Staff","company_name":"Temporary","branch_name":"Temporary"}');
 select restaurant_id,branch_id into r,b from public.erp_memberships where user_id=owner_id;
 insert into public.subscriptions(restaurant_id,subscription_status,plan,trial_end) values(r,'TRIAL','growth_40',current_date+7)
 on conflict(restaurant_id) where restaurant_id is not null do update set subscription_status='TRIAL',plan='growth_40',trial_end=current_date+7;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 insert into public.branches(id,restaurant_id,branch_key,name) values(other_b,r,other_b::text,'Second branch');
 update public.erp_memberships set restaurant_id=r,branch_id=other_b,role='employee',permissions='{"viewSales":true,"uploadSales":true,"viewOrders":true}' where user_id=staff_id;
 insert into public.products(id,restaurant_id,product_id,name,name_ar,is_active) values(p,r,'FOOD-'||p,'Raw chicken','دجاج خام',true);
 insert into public.inventory(id,restaurant_id,branch_id,branch,product_id,product_name,quantity,unit,average_cost) values(stock,r,b,b::text,p::text,'Raw chicken',10,'kg',8);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 insert into public.product_categories(id,restaurant_id,branch_id,name,is_active) values(purchase_category,r,b,'Supplier materials',true);
 set local role authenticated;
 perform public.erp_restaurant_pos_setup(r,b,'category_save',jsonb_build_object('id',category,'name','Chicken'));
 perform public.erp_restaurant_pos_setup(r,other_b,'category_save',jsonb_build_object('id',foreign_category,'name','Other branch'));
 d:=gen_random_uuid();d2:=gen_random_uuid();
 perform public.erp_restaurant_pos_setup(r,b,'device_save',jsonb_build_object('id',d,'code','Front counter'));
 perform public.erp_restaurant_pos_setup(r,b,'device_save',jsonb_build_object('id',d2,'code','Takeaway'));
 perform public.erp_restaurant_pos_setup(r,b,'device_save',jsonb_build_object('id',d,'code','Front counter'));
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'devices','{"count":10}');exception when check_violation then denied:=true;end;assert denied,'Bulk test devices still enabled';
 v:=public.erp_restaurant_pos_workspace(r,b,current_date);
 assert jsonb_array_length(v->'devices')=2,'Device creation is not idempotent';
 d:=(v->'devices'->0->>'id')::uuid;d2:=(v->'devices'->1->>'id')::uuid;
 payload:=jsonb_build_object('category_id',category,'id',menu,'option_group','Roast chicken','option_key','half_rice','name','Half chicken with rice','name_ar','نصف دجاج','price',11.5,'tax_rate',15,'stock_mode','recipe','recipe',jsonb_build_array(jsonb_build_object('inventory_id',stock,'quantity',0.25)));
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'menu',payload||jsonb_build_object('category_id',purchase_category));exception when check_violation then denied:=true;end;
 assert denied,'Purchase category accepted in POS menu';
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'menu',payload||jsonb_build_object('product_id',p));exception when check_violation then denied:=true;end;
 assert denied,'Raw material accepted as a dish';
 perform public.erp_restaurant_pos_setup(r,b,'menu',payload);
 perform public.erp_restaurant_pos_setup(r,b,'menu',payload);
 reset role;
 select product_id into dish from restaurant_pos_private.menu mm where mm.id=menu;
 assert dish<>p,'Dish and material share identity';
 select count(*) into n from public.products where restaurant_id=r and restaurant_product_type='menu_item';
 assert n=1,'Menu retry created duplicate products';
 denied:=false;begin insert into public.inventory(restaurant_id,branch_id,product_id) values(r,b,dish::text);exception when check_violation then denied:=true;end;
 assert denied,'Menu dish accepted into raw inventory';
 denied:=false;begin insert into public.purchases(restaurant_id,branch_id,product_id) values(r,b,dish::text);exception when check_violation then denied:=true;end;
 assert denied,'Menu dish accepted in supplier purchasing';
 denied:=false;begin update public.products set restaurant_product_type='menu_item' where id=p;exception when check_violation then denied:=true;end;
 assert denied,'Material retyped despite stock references';
 set local role authenticated;
 v:=public.erp_restaurant_pos_catalog(r,b,'');
 assert jsonb_array_length(v->'menu')=1 and jsonb_array_length(v->'inventory')=1,'Separated catalog missing dishes or ingredients';
 assert v->'menu'->0->>'option_key'='half_rice','Serving key missing from catalog';
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'menu',payload||jsonb_build_object('id',gen_random_uuid()));exception when unique_violation then denied:=true;end;
 assert denied,'Duplicate serving allowed in branch';
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'menu',payload||jsonb_build_object('id',gen_random_uuid(),'option_key','invalid'));exception when check_violation then denied:=true;end;
 assert denied,'Invalid serving key allowed';
 perform public.erp_restaurant_pos_setup(r,b,'menu',payload||jsonb_build_object('id',whole_menu,'option_key','whole_rice','name','Whole chicken with rice','name_ar','حبة شواية مع الرز','price',40,'recipe',jsonb_build_array(jsonb_build_object('inventory_id',stock,'quantity',0.5))));
 v:=public.erp_restaurant_pos_workspace(r,b,current_date);
 assert jsonb_array_length(v->'menu')=2,'Grouped choices missing from POS workspace';

 -- Owner-defined six-choice batch is atomic, idempotent and scoped to managed categories.
 batch:='[]'::jsonb;
 for ix in 1..6 loop
  batch:=batch||jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'option_key',keys[ix],'name','Owner choice '||ix,'price',10+ix,'tax_rate',0,'stock_mode','recipe','recipe',jsonb_build_array(jsonb_build_object('inventory_id',stock,'quantity',ix*0.1))));
 end loop;
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'menu_batch',jsonb_build_object('option_group','Batch fixture','category_id',foreign_category,'items',batch));exception when check_violation then denied:=true;end;
 assert denied,'Other branch category accepted';
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'menu_batch',jsonb_build_object('option_group','Batch fixture','category_id',category,'items',jsonb_set(batch,'{5,price}','0')));exception when check_violation then denied:=true;end;
 assert denied,'Invalid batch price accepted';
 reset role;
 select count(*) into n from restaurant_pos_private.menu mm where mm.restaurant_id=r;assert n=2,'Invalid batch partially saved';
 select count(*) into n from public.products pp where pp.restaurant_id=r and pp.restaurant_product_type='menu_item';assert n=2,'Failed batch leaked products';
 set local role authenticated;
 perform public.erp_restaurant_pos_setup(r,b,'menu_batch',jsonb_build_object('option_group','Batch fixture','category_id',category,'items',batch));
 perform public.erp_restaurant_pos_setup(r,b,'menu_batch',jsonb_build_object('option_group','Batch fixture','category_id',category,'items',batch));
 v:=public.erp_restaurant_pos_catalog(r,b,'');
 assert jsonb_array_length(v->'categories')=1,'Catalog leaked other branch categories';
 for ix in 1..6 loop
  select value into batch_item from jsonb_array_elements(v->'menu') where value->>'id'=batch->(ix-1)->>'id';
  assert (batch_item->>'price')::numeric=10+ix and batch_item->>'name'='Owner choice '||ix,'Independent name/price lost';
  assert (batch_item->'recipe'->0->>'quantity')::numeric=ix*0.1,'Independent recipe lost';
 end loop;
 reset role;
 update restaurant_pos_private.categories set name='Managed chicken renamed' where id=category;
 select count(*) into n from restaurant_pos_private.menu mm where mm.restaurant_id=r;assert n=8,'Batch retry duplicated dishes';
 set local role authenticated;
 v:=public.erp_restaurant_pos_workspace(r,b,current_date);
 assert v->'menu'->0->>'category'='Managed chicken renamed','POS ignored managed category rename';
 v:=public.erp_restaurant_pos_setup(r,b,'category_list','{}');
 assert jsonb_array_length(v->'categories')=1 and v->'categories'->0->>'name'='Managed chicken renamed','POS category list mixed scopes';
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,other_b,'category_save',jsonb_build_object('id',category,'name','Foreign overwrite'));exception when insufficient_privilege then denied:=true;end;
 assert denied,'Cross-branch category overwrite allowed';
 perform public.erp_restaurant_pos_setup(r,b,'category_save',jsonb_build_object('id',category,'name','Archived chicken','is_active',false));
 v:=public.erp_restaurant_pos_catalog(r,b,'');assert jsonb_array_length(v->'categories')=0,'Inactive POS category offered for selection';
 v:=public.erp_restaurant_pos_setup(r,b,'category_list','{}');assert jsonb_array_length(v->'categories')=1,'Inactive category missing from management';
 perform public.erp_restaurant_pos_setup(r,b,'category_save',jsonb_build_object('id',category,'name','Managed chicken renamed','is_active',true));
 reset role;
 select count(*) into n from public.product_categories pc where pc.restaurant_id=r;assert n=1,'POS category save created purchasing categories';
 select count(*) into n from public.product_categories pc where pc.id=purchase_category and pc.name='Supplier materials';assert n=1,'POS category edit changed purchasing category';
 select count(*) into n from public.products pp where pp.restaurant_id=r and pp.restaurant_product_type='menu_item' and pp.category_id is not null;assert n=0,'Menu dishes retained purchasing category links';
 set local role authenticated;


 batch:='[]'::jsonb;
 for ix in 1..2 loop
  batch_item:=jsonb_build_object('id',gen_random_uuid(),'option_key','custom_'||gen_random_uuid(),'variant_options',jsonb_build_array(jsonb_build_object('label','Size','value',case when ix=1 then 'Small' else 'Large' end),jsonb_build_object('label','Milk','value','Oat')),'name','Owner latte '||ix,'price',ix*12,'tax_rate',0,'stock_mode','recipe','recipe',jsonb_build_array(jsonb_build_object('inventory_id',stock,'quantity',ix*0.1)));
  batch:=batch||jsonb_build_array(batch_item);
 end loop;
 perform public.erp_restaurant_pos_setup(r,b,'menu_batch',jsonb_build_object('option_group','Latte','category_id',category,'items',batch));
 perform public.erp_restaurant_pos_setup(r,b,'menu_batch',jsonb_build_object('option_group','Latte','category_id',category,'items',batch));
 v:=public.erp_restaurant_pos_catalog(r,b,'Latte');assert jsonb_array_length(v->'menu')=2,'Custom menu retry duplicated choices';
 assert v->'menu'->1->'variant_options'->0->>'value'='Large','Custom dimensions lost';
 assert (v->'menu'->1->>'price')::numeric=24,'Custom price lost';
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'menu_batch',jsonb_build_object('option_group','Latte','category_id',category,'items',jsonb_set(batch,'{1,variant_options}',batch->0->'variant_options')));exception when check_violation then denied:=true;end;assert denied,'Duplicate combinations accepted';
 v:=public.erp_restaurant_pos_catalog(r,b,'Latte');assert (v->'menu'->1->>'price')::numeric=24,'Failed batch changed existing menu';
 perform public.erp_restaurant_pos_setup(r,b,'device_archive',jsonb_build_object('id',d2,'active',false));
 denied:=false;begin perform public.erp_restaurant_cashier_command(d2,'open_shift','{"cashier_name":"Test","opening_cash":0}',gen_random_uuid());exception when insufficient_privilege then denied:=true;end;assert denied,'Archived POS accepted sales commands';
 perform public.erp_restaurant_pos_setup(r,b,'device_archive',jsonb_build_object('id',d2,'active',true));
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,other_b,'device_save',jsonb_build_object('id',d2,'code','Wrong branch'));exception when insufficient_privilege then denied:=true;end;assert denied,'Device moved across branches';
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'device_save',jsonb_build_object('id',gen_random_uuid(),'code','front COUNTER'));exception when check_violation then denied:=true;end;assert denied,'Duplicate device names accepted';

 denied:=false;begin perform public.erp_restaurant_pos_setup(r,other_b,'menu',payload);exception when others then denied:=true;end;
 assert denied,'Cross-branch ingredient configuration allowed';
 v:=public.erp_restaurant_cashier_command(d,'open_shift','{"cashier_name":"Fixture","opening_cash":100}',gen_random_uuid());
 v:=public.erp_restaurant_cashier_command(d,'new_sale','{}',gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',menu,'quantity',3,'unit_price',0.01),gen_random_uuid());c:=v->'cart';
 assert (c->>'net_total')::numeric=34.5 and (c->>'tax_total')::numeric=4.5,'Canonical price or included tax failed';
 assert not ((c->'lines'->0) ? 'recipe'),'Cashier leaks raw recipe stock ids';
 reset role;
 select quantity into n from public.inventory where id=stock; assert n=10,'Cart prematurely consumed stock';
 set local role authenticated;
 denied:=false;begin perform public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',0,'menu_id',menu,'quantity',4),gen_random_uuid());exception when serialization_failure then denied:=true;end;
 assert denied,'Stale revision accepted';
 v:=public.erp_restaurant_cashier_command(d,'hold',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());h:=v->'held'->0;
 v:=public.erp_restaurant_cashier_command(d,'resume',jsonb_build_object('cart_id',h->'id','revision',h->'revision'),gen_random_uuid());c:=v->'cart';
 pair:=public.erp_restaurant_cashier_command(d,'pair_display','{}',gen_random_uuid());
 set local role anon;
 v:=public.erp_restaurant_customer_display(pair->>'token');
 assert (v->>'net_total')::numeric=34.5 and not(v ? 'cashier_id') and not(v::text like '%inventory_id%'),'Customer allowlist failed';
 denied:=false;begin perform public.erp_restaurant_cashier_snapshot(d);exception when insufficient_privilege then denied:=true;end;assert denied,'Anonymous cashier access';
 set local role authenticated;
 pair2:=public.erp_restaurant_cashier_command(d,'pair_display','{}',gen_random_uuid());
 denied:=false;begin perform public.erp_restaurant_customer_display(pair->>'token');exception when insufficient_privilege then denied:=true;end;assert denied,'Display rotation failed';
 v:=public.erp_restaurant_cashier_command(d,'send_kitchen',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());c:=v->'cart';
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=9.25,'Recipe consumption failed';
 select count(*) into n from public.daily_sales where reference_id='restaurant-pos:'||(c->>'id');assert n=0,'Unpaid order counted as sales';
 set local role authenticated;
 perform public.erp_restaurant_pos_kitchen((c->>'id')::uuid,(c->>'revision')::integer,'preparing');
 v:=public.erp_restaurant_cashier_snapshot(d);c:=v->'cart';
 perform public.erp_restaurant_pos_kitchen((c->>'id')::uuid,(c->>'revision')::integer,'ready');
 v:=public.erp_restaurant_cashier_snapshot(d);c:=v->'cart';
 denied:=false;begin perform public.erp_restaurant_pos_kitchen((c->>'id')::uuid,(c->>'revision')::integer,'served');exception when check_violation then denied:=true;end;assert denied,'Unpaid food handed over';
 payload:=jsonb_build_object('cart_id',c->'id','revision',c->'revision','payment_confirmed',true,'payments','[{"payment_method":"cash","amount":20},{"payment_method":"card","amount":20}]'::jsonb);
 v:=public.erp_restaurant_cashier_command(d,'checkout',payload,request);receipt:=v->'receipt';
 assert (receipt->>'change')::numeric=5.5,'Split payment change incorrect';
 perform public.erp_restaurant_cashier_command(d,'checkout',payload,request);
 perform public.erp_restaurant_cashier_command(d,'checkout',payload,gen_random_uuid());
 v:=public.erp_restaurant_cashier_snapshot(d);assert (v->>'expected_cash')::numeric=114.5,'Expected cash incorrect';
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=9.25,'Checkout double-consumed ingredients';
 select count(*) into n from public.daily_sales where reference_id='restaurant-pos:'||(c->>'id');assert n=1,'Duplicate sale posting';
 select total into n from public.daily_sales where reference_id='restaurant-pos:'||(c->>'id');assert n=34.5,'Owner financial bridge missing';
 set local role authenticated;
 denied:=false;begin update public.daily_sales set restaurant_cash=0 where id=(receipt->>'id')::uuid;exception when insufficient_privilege then denied:=true;end;assert denied,'POS sales editable through legacy closing';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,other_b,'category_save',jsonb_build_object('id',gen_random_uuid(),'name','Employee category'));exception when insufficient_privilege then denied:=true;end;assert denied,'Cashier edited owner sales categories';
 denied:=false;begin perform public.erp_restaurant_cashier_snapshot(d);exception when insufficient_privilege then denied:=true;end;assert denied,'Cross-branch access';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',other_id,'role','authenticated')::text,true);
 denied:=false;begin perform public.erp_restaurant_pos_workspace(r,b,current_date);exception when insufficient_privilege then denied:=true;end;assert denied,'Cross-tenant access';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 v:=public.erp_restaurant_cashier_command(d,'new_sale','{}',gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',menu,'quantity',50),gen_random_uuid());c:=v->'cart';
 denied:=false;begin perform public.erp_restaurant_cashier_command(d,'send_kitchen',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());exception when check_violation then denied:=true;end;assert denied,'Ingredient overselling allowed';
 v:=public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',menu,'quantity',1),gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d,'send_kitchen',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());c:=v->'cart';
 denied:=false;begin
 v:=public.erp_restaurant_cashier_command(d,'new_sale','{}',gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',whole_menu,'quantity',2,'unit_price',1),gen_random_uuid());c:=v->'cart';
 assert (c->>'net_total')::numeric=80,'Whole serving did not use its independent price';
 assert c->'lines'->0->>'name'='Whole chicken with rice','Serving name missing from invoice line';
 v:=public.erp_restaurant_cashier_command(d,'send_kitchen',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid());c:=v->'cart';
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=8,'Whole serving used the wrong ingredient quantity';
 set local role authenticated;
 v:=public.erp_restaurant_cashier_command(d,'cancel',jsonb_build_object('cart_id',c->'id','revision',c->'revision','reason','Synthetic variant check'),gen_random_uuid());
 perform public.erp_restaurant_cashier_command(d,'close_shift','{"counted_cash":114.5}',gen_random_uuid());exception when check_violation then denied:=true;end;assert denied,'Shift closed with unpaid food';
 v:=public.erp_restaurant_cashier_command(d,'cancel',jsonb_build_object('cart_id',c->'id','revision',c->'revision','reason','Synthetic prepared cancellation'),gen_random_uuid());
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=9,'Prepared cancellation restored raw stock';
 select sum(quantity) into n from restaurant_pos_private.consumption where order_id=(c->>'id')::uuid and wasted;assert n=0.25,'Prepared waste missing';
 set local role authenticated;
 perform public.erp_restaurant_cashier_command(d,'close_shift','{"counted_cash":114.5}',gen_random_uuid());
 denied:=false;begin perform public.erp_restaurant_customer_display(pair2->>'token');exception when insufficient_privilege then denied:=true;end;assert denied,'Closed shift display still visible';
 reset role;
 select count(*) into n from public.daily_sales where restaurant_id=r::text and reference_id like 'restaurant-pos:%';assert n=1,'Shift closing posted duplicate sales';

 -- A custom combination follows the same canonical invoice and ingredient path as fixed servings.
 set local role authenticated;
 v:=public.erp_restaurant_cashier_command(d2,'open_shift','{"cashier_name":"Custom cashier","opening_cash":0}',gen_random_uuid());
 denied:=false;begin perform public.erp_restaurant_pos_setup(r,b,'device_archive',jsonb_build_object('id',d2,'active',false));exception when check_violation then denied:=true;end;assert denied,'POS with an open shift archived';
 v:=public.erp_restaurant_cashier_command(d2,'new_sale','{}',gen_random_uuid());c:=v->'cart';
 v:=public.erp_restaurant_cashier_command(d2,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','menu_id',batch->1->>'id','quantity',1,'price',0.01),gen_random_uuid());c:=v->'cart';
 assert (c->>'net_total')::numeric=24,'Cashier overrode the configured custom price';
 v:=public.erp_restaurant_cashier_command(d2,'checkout',jsonb_build_object('cart_id',c->'id','revision',c->'revision','payment_confirmed',true,'payments',jsonb_build_array(jsonb_build_object('payment_method','cash','amount',24))),gen_random_uuid());
 assert (v->'receipt'->>'total')::numeric=24 or (v->'receipt'->>'net_total')::numeric=24,'Custom invoice price missing';
 reset role;
 select quantity into n from public.inventory where id=stock;assert n=8.8,'Custom recipe quantity was not deducted exactly once';
end $$;
rollback;
