-- Synthetic tenants only; every row created here is rolled back.
begin;
do $$
declare
  owner_id uuid:=gen_random_uuid(); other_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid();
  r uuid; branch uuid; other_branch uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); w uuid; device uuid; device2 uuid;
  v jsonb; s jsonb; c jsonb; held jsonb; receipt jsonb; refund jsonb; doc jsonb; link jsonb; link2 jsonb; payload jsonb;
  request_id uuid:=gen_random_uuid(); n numeric; failed boolean; txn uuid;
begin
  insert into auth.users(id,email,raw_user_meta_data) values
    (owner_id,'cashier-owner-'||owner_id||'@example.invalid','{"role":"owner","business_type":"retail","full_name":"Cashier verification","company_name":"Cashier test","branch_name":"Test A"}'),
    (other_id,'cashier-other-'||other_id||'@example.invalid','{"role":"owner","business_type":"retail","full_name":"Other owner","company_name":"Isolation test","branch_name":"Other"}'),
    (staff_id,'cashier-staff-'||staff_id||'@example.invalid','{"role":"owner","business_type":"retail","full_name":"Staff","company_name":"Temporary test","branch_name":"Temporary"}');
  select restaurant_id,branch_id into r,branch from public.erp_memberships where user_id=owner_id;
  insert into public.subscriptions(restaurant_id,subscription_status,plan,trial_end) values(r,'TRIAL','growth_40',current_date+7)
    on conflict(restaurant_id) where restaurant_id is not null do update set subscription_status='TRIAL',plan='growth_40',trial_end=current_date+7;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
  insert into public.branches(id,restaurant_id,name,branch_key) values(other_branch,r,'Test B',other_branch::text);
  update public.erp_memberships set restaurant_id=r,branch_id=other_branch,role='employee',permissions='{"viewSales":true,"uploadSales":true,"viewInventory":true}' where user_id=staff_id;
  update public.profiles set restaurant_id=r,organization_id=r,branch_id=other_branch,role='employee' where id=staff_id;
  insert into public.products(id,restaurant_id,product_id,name,name_ar,sku,barcode,unit,purchase_cost,selling_price,tax_rate,is_active,custom_attributes)
    values(p,r,'TEST-'||p,'Verification milk','حليب الاختبار','TEST-'||p,'0012345678905','pc',4,11.5,15,true,'{"__erp_master":{"price_includes_tax":true}}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
  set local role authenticated;
  perform public.erp_retail_inventory_command(r,'assign',jsonb_build_object('branch_id',branch,'product_ids',jsonb_build_array(p)));
  select id into w from public.retail_inventory_warehouses where branch_id=branch and is_default;
  doc:=public.erp_retail_inventory_command(r,'create',jsonb_build_object('kind','receipt','warehouse_id',w,'lines',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',100,'unit_cost',4))),'cashier-fixture-'||p);
  perform public.erp_retail_inventory_command(r,'receive',jsonb_build_object('document_id',doc->>'id'));
  perform public.erp_retail_pos_seed_branch_devices(branch,2);
  select id into device from public.retail_pos_devices where branch_id=branch order by code limit 1;
  select id into device2 from public.retail_pos_devices where branch_id=branch order by code offset 1 limit 1;
  v:=public.erp_retail_cashier_command(device,'open_shift','{"cashier_name":"Test cashier","opening_cash":100}',gen_random_uuid());
  c:=v->'cart';
  v:=public.erp_retail_cashier_command(device,'scan',jsonb_build_object('cart_id',c->'id','revision',c->'revision','code','0012345678905'),gen_random_uuid());
  c:=v->'cart';
  if (c->>'net_total')::numeric<>11.5 or (c->>'tax_total')::numeric<>1.5 then raise exception 'Inclusive tax calculation failed: %',c; end if;
  select quantity into n from public.retail_inventory_balances where warehouse_id=w and product_id=p;
  if n<>100 then raise exception 'Scanning prematurely deducted physical stock'; end if;
  select reserved into n from public.retail_inventory_balances where warehouse_id=w and product_id=p;
  if n<>1 then raise exception 'Scan reservation missing'; end if;
  failed:=false;
  begin perform public.erp_retail_cashier_command(device,'quantity',jsonb_build_object('cart_id',c->'id','revision',0,'product_id',p,'quantity',2),gen_random_uuid());
    exception when serialization_failure then failed:=true; end;
  if not failed then raise exception 'Stale revision accepted'; end if;
  v:=public.erp_retail_cashier_command(device,'quantity',jsonb_build_object('cart_id',c->'id','revision',c->'revision','product_id',p,'quantity',3,'price',0.01),gen_random_uuid()); c:=v->'cart';
  if (c->>'net_total')::numeric<>34.5 then raise exception 'Client price tampering or quantity calculation failed'; end if;
  s:=public.erp_retail_cashier_command(device2,'open_shift','{"cashier_name":"Second cashier","opening_cash":0}',gen_random_uuid());
  failed:=false;
  begin perform public.erp_retail_cashier_command(device2,'quantity',jsonb_build_object('cart_id',s->'cart'->'id','revision',s->'cart'->'revision','product_id',p,'quantity',98),gen_random_uuid());
    exception when check_violation then failed:=true; end;
  if not failed then raise exception 'Another lane oversold reserved stock'; end if;
  v:=public.erp_retail_cashier_command(device,'hold',jsonb_build_object('cart_id',c->'id','revision',c->'revision'),gen_random_uuid()); held:=v->'held'->0->'cart';
  v:=public.erp_retail_cashier_command(device,'new_sale','{}',gen_random_uuid());
  v:=public.erp_retail_cashier_command(device,'resume',jsonb_build_object('cart_id',held->'id','revision',held->'revision'),gen_random_uuid()); c:=v->'cart';
  if (c->>'net_total')::numeric<>34.5 then raise exception 'Held sale did not resume'; end if;
  link:=public.erp_retail_cashier_command(device,'pair_display','{}',gen_random_uuid());
  set local role anon;
  v:=public.erp_retail_customer_display(link->>'token');
  if v ? 'cashier_id' or v ? 'receipt' or v ? 'device_id' or (v->>'net_total')::numeric<>34.5 or v::text like '%purchase_cost%' then raise exception 'Public display allowlist failed'; end if;
  failed:=false;
  begin perform public.erp_retail_customer_display(repeat('0',64)); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Invalid public token accepted'; end if;
  failed:=false;
  begin perform public.erp_retail_cashier_snapshot(device); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Anonymous cashier access'; end if;
  set local role authenticated;
  link2:=public.erp_retail_cashier_command(device,'pair_display','{}',gen_random_uuid());
  failed:=false;
  begin perform public.erp_retail_customer_display(link->>'token'); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Rotated display link still works'; end if;
  payload:=jsonb_build_object('cart_id',c->'id','revision',c->'revision','payment_confirmed',true,'payments',jsonb_build_array(jsonb_build_object('payment_method','mada','amount',20),jsonb_build_object('payment_method','cash','amount',20)));
  failed:=false;
  begin perform public.erp_retail_cashier_command(device,'checkout',payload||'{"payment_confirmed":false}',gen_random_uuid()); exception when others then failed:=true; end;
  if not failed then raise exception 'Unconfirmed payment accepted'; end if;
  v:=public.erp_retail_cashier_command(device,'checkout',payload,request_id); receipt:=v->'receipt'; txn:=(receipt->>'id')::uuid;
  if (receipt->>'change')::numeric<>5.5 or (receipt->>'net_total')::numeric<>34.5 then raise exception 'Split payment/change failed'; end if;
  perform public.erp_retail_cashier_command(device,'checkout',payload,request_id);
  perform public.erp_retail_cashier_command(device,'checkout',payload,gen_random_uuid());
  select quantity into n from public.retail_inventory_balances where warehouse_id=w and product_id=p;
  if n<>97 then raise exception 'Duplicate checkout deducted stock: %',n; end if;
  select reserved into n from public.retail_inventory_balances where warehouse_id=w and product_id=p;
  if n<>0 then raise exception 'Paid stock remains reserved'; end if;
  select count(*) into n from public.retail_pos_transactions where device_id=device and transaction_type='sale';
  if n<>1 then raise exception 'Duplicate ledger sale'; end if;
  v:=public.erp_retail_cashier_snapshot(device);
  if (v->>'expected_cash')::numeric<>114.5 then raise exception 'Drawer expected cash failed'; end if;
  failed:=false;
  begin perform public.erp_retail_pos_record_transaction('{}'); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Legacy client-priced writer still exposed'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',other_id,'role','authenticated')::text,true);
  failed:=false;
  begin perform public.erp_retail_cashier_snapshot(device); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Cross-tenant access'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);
  failed:=false;
  begin perform public.erp_retail_cashier_command(device,'heartbeat','{}',gen_random_uuid()); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Cross-branch staff access'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
  v:=public.erp_retail_cashier_command(device,'refund',jsonb_build_object('cart_id',receipt->'cart_id','reason','Fixture returned unopened','payment_confirmed',true),gen_random_uuid()); refund:=v->'receipt';
  if refund->>'transaction_type'<>'refund' then raise exception 'Refund missing'; end if;
  v:=public.erp_retail_cashier_receipt(device,(refund->>'id')::uuid);
  if v->>'id'<>refund->>'id' then raise exception 'Refund reprint failed'; end if;
  failed:=false;
  begin perform public.erp_retail_cashier_command(device,'refund',jsonb_build_object('cart_id',receipt->'cart_id','reason','duplicate','payment_confirmed',true),gen_random_uuid()); exception when others then failed:=true; end;
  if not failed then raise exception 'Duplicate refund accepted'; end if;
  select on_hand into n from public.retail_inventory_stock where warehouse_id=w and product_id=p;
  if n<>100 then raise exception 'Refund did not restore physical stock'; end if;
  select available into n from public.retail_inventory_stock where warehouse_id=w and product_id=p;
  if n<>97 then raise exception 'Refund was not quarantined'; end if;
  v:=public.erp_retail_cashier_command(device,'new_sale','{}',gen_random_uuid()); c:=v->'cart';
  v:=public.erp_retail_cashier_command(device,'scan',jsonb_build_object('cart_id',c->'id','revision',c->'revision','code','0012345678905'),gen_random_uuid()); c:=v->'cart';
  perform public.erp_retail_cashier_command(device,'close_shift','{"counted_cash":100,"notes":"Fixture close"}',gen_random_uuid());
  select reserved into n from public.retail_inventory_balances where warehouse_id=w and product_id=p;
  if n<>0 then raise exception 'Closing shift did not release cart'; end if;
  failed:=false;
  begin perform public.erp_retail_customer_display(link2->>'token'); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Display link survived closed shift'; end if;
  reset role;
  update public.products set name='Changed after sale' where id=p;
  set local role authenticated;
  v:=public.erp_retail_cashier_receipt(device,txn);
  if v->'lines'->0->>'name'<>'Verification milk' then raise exception 'Receipt history changed after product edit'; end if;
  v:=public.erp_retail_cashier_command(device2,'scan',jsonb_build_object('cart_id',s->'cart'->'id','revision',s->'cart'->'revision','code','0012345678905'),gen_random_uuid()); c:=v->'cart';
  reset role;
  update retail_checkout_private.carts set expires_at=now()-interval '1 minute' where id=(c->>'id')::uuid;
  perform retail_checkout_private.expire_carts();
  select reserved into n from public.retail_inventory_balances where warehouse_id=w and product_id=p;
  if n<>0 then raise exception 'Expired cart retained stock'; end if;
  update public.erp_memberships set branch_id=branch where user_id=staff_id;
  update public.profiles set branch_id=(select m.branch_id from public.erp_memberships m where m.user_id=staff_id) where id=staff_id;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);
  set local role authenticated;
  v:=public.erp_retail_cashier_command(device,'open_shift','{"cashier_name":"Staff cashier","opening_cash":0}',gen_random_uuid()); c:=v->'cart';
  if v->'shift'->>'cashier_user_id'<>staff_id::text then raise exception 'Shift was not assigned to authenticated cashier'; end if;
  failed:=false;
  begin perform public.erp_retail_cashier_command(device,'discount',jsonb_build_object('cart_id',c->'id','revision',c->'revision','percent',50,'reason','Unauthorized staff discount'),gen_random_uuid()); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Staff authorized own discount'; end if;
  failed:=false;
  begin perform public.erp_retail_pos_open_shift(device,'Bypass',0); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Legacy shift opener bypass still exposed'; end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
  perform public.erp_retail_pos_request_command(device,'lock','{}');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',staff_id,'role','authenticated')::text,true);
  v:=public.erp_retail_cashier_command(device,'heartbeat','{}',gen_random_uuid());
  if v->'device'->>'status'<>'locked' then raise exception 'Remote lock was not enforced by cashier'; end if;
  failed:=false;
  begin perform public.erp_retail_cashier_command(device,'scan',jsonb_build_object('cart_id',c->'id','revision',c->'revision','code','0012345678905'),gen_random_uuid()); exception when object_not_in_prerequisite_state then failed:=true; end;
  if not failed then raise exception 'Locked cashier accepted a scan'; end if;
  reset role;
  raise notice 'PASS: cashier stock reservation, oversell, tax, hold/resume, split payment, idempotency, immutable receipts, refund, isolation, public pairing, close and expiry';
end $$;
rollback;
