import jsPDF from 'jspdf';
import { calcInvoiceTotals } from './procurementEngine';
import { drawLocalizedPdfText, prepareLocalizedPdf, safePdfFilename } from './pdfLocalization';

const WORDS={
  en:{title:'Purchase Invoice',business:'Business',branch:'Branch',supplier:'Supplier',
    reference:'Invoice number',date:'Date',due:'Due date',status:'Status',payment:'Payment method',
    taxId:'Tax registration',address:'Address',items:'PURCHASE ITEMS',
    product:'Product / description',unit:'Unit',qty:'Qty',price:'Unit cost',
    discount:'Discount',tax:'VAT',line:'Total',notes:'NOTES',summary:'INVOICE SUMMARY',
    before:'Before VAT',vat:'VAT',additional:'Additional costs',total:'TOTAL AMOUNT',
    paid:'Amount paid',dueAmount:'Remaining balance',created:'Created',
    approved:'Approved',draft:'Draft',pending:'Pending approval',cancelled:'Cancelled',
    generated:'Generated by BizCTRL ERP',page:'Page',of:'of',
    empty:'No line items have been recorded',disclaimer:'Figures come from the saved purchase invoice. No payment is created by printing this document.',
    mismatch:'Line details differ from the saved invoice total; verify original records.',
    paymentPending:'Not recorded'},
  ar:{title:'فاتورة المشتريات',business:'المنشأة',branch:'الفرع',supplier:'المورد',
    reference:'رقم الفاتورة',date:'التاريخ',due:'تاريخ الاستحقاق',status:'الحالة',payment:'طريقة الدفع',
    taxId:'الرقم الضريبي',address:'العنوان',items:'أصناف المشتريات',
    product:'الصنف / الوصف',unit:'الوحدة',qty:'الكمية',price:'سعر الوحدة',
    discount:'الخصم',tax:'الضريبة',line:'الإجمالي',notes:'ملاحظات',summary:'ملخص الفاتورة',
    before:'قبل الضريبة',vat:'ضريبة القيمة المضافة',additional:'تكاليف إضافية',total:'الإجمالي شامل الضريبة',
    paid:'المبلغ المدفوع',dueAmount:'الرصيد المتبقي',created:'تم الإنشاء',
    approved:'معتمدة',draft:'مسودة',pending:'بانتظار الموافقة',cancelled:'ملغاة',
    generated:'أنشأها نظام BizCTRL ERP',page:'صفحة',of:'من',
    empty:'لم تُسجّل أصناف في هذه الفاتورة',disclaimer:'الأرقام من الفاتورة المحفوظة. طباعة المستند لا تسجل دفعة جديدة.',
    mismatch:'تفاصيل الأصناف لا تطابق الإجمالي المحفوظ؛ يرجى مراجعة السجلات.',
    paymentPending:'غير مسجلة'},
  fa:{title:'فاکتور خرید',business:'کسب‌وکار',branch:'شعبه',supplier:'تأمین‌کننده',
    reference:'شماره فاکتور',date:'تاریخ',due:'سررسید',status:'وضعیت',payment:'روش پرداخت',
    taxId:'شماره مالیاتی',address:'آدرس',items:'اقلام خرید',
    product:'محصول / توضیحات',unit:'واحد',qty:'تعداد',price:'قیمت واحد',
    discount:'تخفیف',tax:'مالیات',line:'جمع',notes:'یادداشت‌ها',summary:'خلاصه فاکتور',
    before:'قبل از مالیات',vat:'مالیات ارزش افزوده',additional:'مصارف اضافی',total:'مجموع با مالیات',
    paid:'پرداخت‌شده',dueAmount:'باقی‌مانده',created:'ثبت‌شده',
    approved:'تأییدشده',draft:'پیش‌نویس',pending:'منتظر تأیید',cancelled:'لغوشده',
    generated:'تولیدشده توسط BizCTRL ERP',page:'صفحه',of:'از',
    empty:'هیچ قلمی در این فاکتور ثبت نشده',disclaimer:'اعداد از فاکتور ذخیره‌شده گرفته شده‌اند. تولید PDF پرداخت جدید ایجاد نمی‌کند.',
    mismatch:'جزئیات اقلام با مجموع ذخیره‌شده فرق دارد؛ رکورد اصلی را بررسی کنید.',
    paymentPending:'ثبت نشده'},
};
const NAVY=[12,28,61],BLUE=[29,111,246],CYAN=[0,186,226],MUTED=[99,115,139],BORDER=[224,234,245],GREEN=[0,145,107];
const cash=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const arr=value=>{if(Array.isArray(value))return value;try{const v=JSON.parse(value);return Array.isArray(v)?v:[]}catch{return []}};
const safe=value=>String(value??'').trim()||'—';
const rounded=n=>Math.round((Number(n)||0)*100)/100;
const wrapItem=(value,max=26)=>{
 const parts=String(value||'—').trim().split(/\s+/);
 const rows=[];let row='';
 for(const raw of parts){
  for(let word=raw;word.length;){
   const part=word.slice(0,max); word=word.slice(max);
   if(row && (row.length+part.length+1)>max){rows.push(row);row='';}
   row=row?row+' '+part:part;
   if(word.length){rows.push(row);row='';}
  }
 }
 if(row)rows.push(row);
 return rows.length?rows:['—'];
};

const statusOf=invoice=>{
  if(invoice.status==='cancelled')return 'cancelled';
  if(['approved','auto_approved'].includes(invoice.approval_status)||['approved','paid','partial'].includes(invoice.status))return 'approved';
  if(invoice.approval_status==='pending'||invoice.status==='pending')return 'pending';
  return 'draft';
};
export function buildPurchaseInvoiceDocument(invoice,options={}){
  if(!invoice?.id && !invoice?.invoice_number)throw new Error('A saved purchase invoice is required');
  const items=arr(invoice.items);
  const extras=arr(invoice.additional_costs);
  const computed=calcInvoiceTotals(items,extras);
  const total=rounded(invoice.total_amount??computed.grandTotal);
  const vat=rounded(invoice.tax_amount??computed.taxAmount);
  const subtotalWithVat=rounded(invoice.subtotal??computed.subtotal);
  const additional=rounded(extras.reduce((s,x)=>s+(Number(x.amount)||0),0));
  const paid=rounded(invoice.paid_amount);
  return {
    invoice,items:computed.lines,extras,
    subtotalWithVat,vat,additional,total,paid,remaining:rounded(Math.max(0,total-paid)),
    beforeVAT:rounded(subtotalWithVat-vat),
    difference:Math.abs(total-computed.grandTotal),status:statusOf(invoice),
    businessName:safe(options.business?.name||options.business?.brand_name||options.brand?.brand_name||'Restaurant'),
    businessTax:safe(options.business?.tax_number||options.business?.vat_number||options.brand?.vat_registration_number),
    address:safe(options.brand?.address||options.business?.address),
    branch:safe(options.branch?.name||options.branch?.label||invoice.branch),
    currency:invoice.currency||options.currency||'SAR',
  };
}
export function createBrandedPurchaseInvoicePDF(invoice,{lang='en',business,brand,branch,currency}={}){
 const language=WORDS[lang]?lang:'en',w=WORDS[language],rtl=language!=='en';
 const m=buildPurchaseInvoiceDocument(invoice,{business,brand,branch,currency});
 const doc=new jsPDF({format:'a4',orientation:'portrait',unit:'mm',putOnlyUsedFonts:true});
 prepareLocalizedPdf(doc,{lang:language,dir:rtl?'rtl':'ltr'});
 const W=210,L=12,R=198, CW=186, left=x=>rtl?R-x:L+x;
 const write=(value,x,y,{size=8,bold=false,color=NAVY,align,maxWidth}={})=>
   drawLocalizedPdfText(doc,String(value??'—'),x,y,{rtl,size,bold,color,align:align||(rtl?'right':'left'),maxWidth});
 const rectangle=(x,y,width,height,fill=[248,251,255])=>{
  doc.setFillColor(...fill);doc.setDrawColor(...BORDER);doc.roundedRect(x,y,width,height,2.4,2.4,'FD');
 };
 const amount=(n)=>cash(n)+' '+m.currency;
 let pageNo=0;
 const header=()=>{
  pageNo+=1;
  // Four-part mark inspired by the existing BizCTRL identity. Brand is
  // identifiable even if the restaurant hasn't uploaded its own logo.
  const positions=[[0,0],[7.7,0],[0,7.7],[7.7,7.7]];
  positions.forEach(([dx,dy],i)=>{doc.setFillColor(...(i===1||i===3?CYAN:BLUE));
    doc.roundedRect(13+dx,10+dy,6.8,6.8,1.1,1.1,'F');});
  write('BizCTRL',32,20,{size:23,bold:true,align:'left'});
  write('Restaurant ERP System',32,26.5,{size:7.5,color:MUTED,align:'left'});
  write(w.title,R,18,{size:16,bold:true,color:NAVY,align:'right'});
  write(safe(invoice.invoice_number),R,27,{size:9,bold:true,color:BLUE,align:'right'});
  doc.setDrawColor(...BORDER);doc.line(L,32,R,32);
  rectangle(L,37,91,40,[244,249,255]);rectangle(107,37,91,40,[248,251,255]);
  const businessX=rtl?99:16;
  write(w.business+': '+m.businessName,businessX,45,{size:9.5,bold:true,maxWidth:82});
  write(w.branch+': '+m.branch,businessX,54,{size:8,maxWidth:82});
  write(w.taxId+': '+m.businessTax,businessX,62,{size:7.5,maxWidth:82});
  write(w.address+': '+m.address,businessX,70,{size:7.2,maxWidth:82});
  const invX=rtl?194:111;
  write(w.supplier+': '+safe(invoice.supplier_name),invX,45,{size:9.5,bold:true,maxWidth:82});
  write(w.date+': '+safe(invoice.date),invX,54,{size:8,maxWidth:82});
  write(w.due+': '+safe(invoice.due_date),invX,62,{size:7.5,maxWidth:82});
  write(w.status+': '+w[m.status],invX,70,{size:8,bold:true,color:m.status==='approved'?GREEN:BLUE,maxWidth:82});
 };
 const gridTitles=[w.product,w.unit,w.qty,w.price,w.discount,w.tax,w.line];
 const widths=[61,19,14,23,20,20,29];
 const grid=(y)=>{
  doc.setFillColor(230,242,254);doc.roundedRect(L,y,CW,10,1.4,1.4,'F');
  let x=L;
  gridTitles.forEach((name,i)=>{write(name,x+widths[i]/2,y+6.6,{size:7,bold:true,align:'center',maxWidth:widths[i]-2});x+=widths[i]});
 };
 const newPage=()=>{if(pageNo)doc.addPage();header();grid(83);return 95;};
 let y=newPage();
 for (const [i,item] of m.items.entries()){
  // Printed product descriptions wrap without crossing numeric columns.
  // Height follows the real number of lines; long invoices keep all items
  // and continue onto subsequent pages rather than hiding products.
  const productLines=wrapItem(item.product_name||item.name||item.description);
  const rowHeight=Math.max(13.5,7+productLines.length*5.6);
  if(y+rowHeight>264)y=newPage();
  if(i%2===0){doc.setFillColor(248,251,255);doc.rect(L,y-1,CW,rowHeight,'F');}
  productLines.forEach((line,k)=>write(line,L+widths[0]/2,y+4.5+k*5.6,
    {size:7.2,align:'center',maxWidth:widths[0]-3}));
  const numbers=[
    safe(item.unit||item.unit_name),String(item.quantity),
    cash(item.unit_cost),cash(item.discount),cash(calcInvoiceTotals([item]).taxAmount),cash(item.line_total),
  ];
  let x=L+widths[0];
  numbers.forEach((value,j)=>{
   const col=j+1;
   write(value,x+widths[col]/2,y+Math.min(7,rowHeight/2),{size:7.1,bold:col===6,
    color:col===6?BLUE:NAVY,align:'center',maxWidth:widths[col]-3});
   x+=widths[col];
  });
  y+=rowHeight;
 }
 if(!m.items.length){write(w.empty,L+4,y+7,{size:9,color:MUTED,align:'left'});y+=17;}
 // Summary is never placed over the footer or cut off by item overflow.
 if(y>194){doc.addPage();header();y=84;}
 y+=4;
 rectangle(107,y,91,71,[247,251,255]);
 write(w.summary,rtl?194:111,y+8,{size:9,bold:true,color:BLUE});
 const summaryRows=[
  [w.before,m.beforeVAT],[w.vat,m.vat],[w.additional,m.additional],
  [w.total,m.total],[w.paid,m.paid],[w.dueAmount,m.remaining],
 ];
 summaryRows.forEach(([label,n],i)=>{
  const yy=y+17+i*9;
  if(i===3){doc.setFillColor(223,240,255);doc.rect(109,yy-6,87,9,'F');}
  write(label,rtl?194:111,yy,{size:i===3?8.5:7.5,bold:i===3,maxWidth:44});
  write(amount(n),rtl?111:194,yy,{size:i===3?9.5:8,bold:i===3,color:i===5?GREEN:NAVY,
    align:rtl?'left':'right',maxWidth:42});
 });
 rectangle(L,y,91,45,[248,251,255]);
 write(w.notes,rtl?99:16,y+9,{size:9,bold:true,color:BLUE});
 write(safe(invoice.notes),rtl?99:16,y+19,{size:7.5,maxWidth:83});
 if(m.difference>.05)write(w.mismatch,rtl?99:16,y+37,{size:6.7,color:[205,73,47],maxWidth:83});
 // No false approval timeline or QR verification; only stored approval state.
 if(m.status==='approved'){
   write(w.approved,rtl?99:16,y+31,{size:8,bold:true,color:GREEN});
 }else write(w[m.status],rtl?99:16,y+31,{size:8,bold:true,color:BLUE});
 const totalPages=doc.getNumberOfPages();
 for(let p=1;p<=totalPages;p++){
  doc.setPage(p);doc.setDrawColor(...BORDER);doc.line(L,277,R,277);
  write(w.generated,rtl?R:L,283,{size:8,bold:true,color:BLUE});
  write(w.disclaimer,rtl?R:L,288,{size:6.5,color:MUTED,maxWidth:150});
  write(w.page+' '+p+' '+w.of+' '+totalPages,rtl?L:R,291.2,{size:7,color:MUTED,align:rtl?'left':'right'});
 }
 const filename=safePdfFilename('BizCTRL-Purchase-'+safe(invoice.invoice_number||invoice.id).replace(/[^a-zA-Z0-9_-]/g,''),language);
 return {doc,filename,model:m};
}
export function downloadPurchaseInvoicePDF(invoice,options={}){
 const {doc,filename}=createBrandedPurchaseInvoicePDF(invoice,options);
 doc.save(filename);
 return filename;
}

/** Shares the *actual PDF file* on iOS/Android supported browsers via native
 * share sheet. WhatsApp must be chosen by the user; no app can silently send
 * a PDF to WhatsApp contacts without an authenticated messaging integration.
 */
export async function sharePurchaseInvoicePDF(invoice,options={}){
 const {doc,filename,model}=createBrandedPurchaseInvoicePDF(invoice,options);
 const blob=doc.output('blob');
 const file=typeof File!=='undefined'
   ?new File([blob],filename,{type:'application/pdf'}):null;
 if(file && typeof navigator!=='undefined' && navigator.canShare?.({files:[file]}) && navigator.share){
  try{
   await navigator.share({files:[file],title:'BizCTRL Purchase '+safe(invoice.invoice_number)});
   return {shared:true};
  }catch(e){
   if(e?.name==='AbortError')return {cancelled:true};
   // If the system share sheet failed, fall back to a real downloadable PDF.
  }
 }
 doc.save(filename);
 const text=['BizCTRL Purchase Invoice '+safe(invoice.invoice_number),
    safe(invoice.supplier_name),amountForShare(model.total,model.currency),
    'PDF downloaded. Attach it from Files to send on WhatsApp.'].join('\n');
 return {shared:false,downloaded:true,text,whatsappUrl:'https://wa.me/?text='+encodeURIComponent(text)};
}
const amountForShare=(n,c)=>cash(n)+' '+c;
