import jsPDF from 'jspdf';
import { calcInvoiceTotals } from './procurementEngine';
import { prepareLocalizedPdf, safePdfFilename } from './pdfLocalization';
import { renderPurchaseInvoiceReference } from './purchaseInvoiceReferenceLayout';

const WORDS={
  en:{title:'Purchase Invoice',business:'Business',branch:'Branch',supplier:'Supplier',
    reference:'Invoice number',date:'Date',due:'Due date',status:'Status',payment:'Payment method',
    taxId:'Tax registration',address:'Address',items:'PURCHASE ITEMS',
    product:'Product / description',unit:'Unit',qty:'Qty',price:'Unit cost',
    discount:'Discount',tax:'VAT',line:'Total',notes:'NOTES',summary:'INVOICE SUMMARY',
    before:'Before VAT',vat:'VAT',additional:'Additional costs',total:'TOTAL AMOUNT',
    paid:'Amount paid',dueAmount:'Remaining balance',created:'Created',
    approved:'Approved',draft:'Draft',pending:'Pending approval',cancelled:'Cancelled',
    generated:'Generated by BizCTRL ERP',page:'Page',of:'of',
    empty:'No line items have been recorded',disclaimer:'Figures come from the saved purchase invoice. No payment is created by printing this document.',
    mismatch:'Line details differ from the saved invoice total; verify original records.',
    paymentPending:'Not recorded'},
  ar:{title:'فاتورة المشتريات',business:'المنشأة',branch:'الفرع',supplier:'المورد',
    reference:'رقم الفاتورة',date:'التاريخ',due:'تاريخ الاستحقاق',status:'الحالة',payment:'طريقة الدفع',
    taxId:'الرقم الضريبي',address:'العنوان',items:'أصناف المشتريات',
    product:'الصنف / الوصف',unit:'الوحدة',qty:'الكمية',price:'سعر الوحدة',
    discount:'الخصم',tax:'الضريبة',line:'الإجمالي',notes:'ملاحظات',summary:'ملخص الفاتورة',
    before:'قبل الضريبة',vat:'ضريبة القيمة المضافة',additional:'تكاليف إضافية',total:'الإجمالي شامل الضريبة',
    paid:'المبلغ المدفوع',dueAmount:'الرصيد المتبقي',created:'تم الإنشاء',
    approved:'معتمدة',draft:'مسودة',pending:'بانتظار الموافقة',cancelled:'ملغاة',
    generated:'أنشأها نظام BizCTRL ERP',page:'صفحة',of:'من',
    empty:'لم تُسجّل أصناف في هذه الفاتورة',disclaimer:'الأرقام من الفاتورة المحفوظة. طباعة المستند لا تسجل دفعة جديدة.',
    mismatch:'تفاصيل الأصناف لا تطابق الإجمالي المحفوظ؛ يرجى مراجعة السجلات.',
    paymentPending:'غير مسجلة'},
  fa:{title:'فاکتور خرید',business:'کسب‌وکار',branch:'شعبه',supplier:'تأمین‌کننده',
    reference:'شماره فاکتور',date:'تاریخ',due:'سررسید',status:'وضعیت',payment:'روش پرداخت',
    taxId:'شماره مالیاتی',address:'آدرس',items:'اقلام خرید',
    product:'محصول / توضیحات',unit:'واحد',qty:'تعداد',price:'قیمت واحد',
    discount:'تخفیف',tax:'مالیات',line:'جمع',notes:'یادداشت‌ها',summary:'خلاصه فاکتور',
    before:'قبل از مالیات',vat:'مالیات ارزش افزوده',additional:'مصارف اضافی',total:'مجموع با مالیات',
    paid:'پرداخت‌شده',dueAmount:'باقی‌مانده',created:'ثبت‌شده',
    approved:'تأییدشده',draft:'پیش‌نویس',pending:'منتظر تأیید',cancelled:'لغوشده',
    generated:'تولیدشده توسط BizCTRL ERP',page:'صفحه',of:'از',
    empty:'هیچ قلمی در این فاکتور ثبت نشده',disclaimer:'اعداد از فاکتور ذخیره‌شده گرفته شده‌اند. تولید PDF پرداخت جدید ایجاد نمی‌کند.',
    mismatch:'جزئیات اقلام با مجموع ذخیره‌شده فرق دارد؛ رکورد اصلی را بررسی کنید.',
    paymentPending:'ثبت نشده'},
};
const NAVY=[12,28,61],BLUE=[29,111,246],CYAN=[0,186,226],MUTED=[99,115,139],BORDER=[224,234,245],GREEN=[0,145,107];
const cash=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const arr=value=>{if(Array.isArray(value))return value;try{const v=JSON.parse(value);return Array.isArray(v)?v:[]}catch{return []}};
const safe=value=>String(value??'').trim()||'—';
const rounded=n=>Math.round((Number(n)||0)*100)/100;
const wrapItem=(value,max=26)=>{
 const parts=String(value||'—').trim().split(/\s+/);
 const rows=[];let row='';
 for(const raw of parts){
  for(let word=raw;word.length;){
   const part=word.slice(0,max); word=word.slice(max);
   if(row && (row.length+part.length+1)>max){rows.push(row);row='';}
   row=row?row+' '+part:part;
   if(word.length){rows.push(row);row='';}
  }
 }
 if(row)rows.push(row);
 return rows.length?rows:['—'];
};

const statusOf=invoice=>{
  if(invoice.status==='cancelled')return 'cancelled';
  if(['approved','auto_approved'].includes(invoice.approval_status)||['approved','paid','partial'].includes(invoice.status))return 'approved';
  if(invoice.approval_status==='pending'||invoice.status==='pending')return 'pending';
  return 'draft';
};
export function buildPurchaseInvoiceDocument(invoice,options={}){
  if(!invoice?.id && !invoice?.invoice_number)throw new Error('A saved purchase invoice is required');
  const items=arr(invoice.items);
  const extras=arr(invoice.additional_costs);
  const computed=calcInvoiceTotals(items,extras);
  const total=rounded(invoice.total_amount??computed.grandTotal);
  const vat=rounded(invoice.tax_amount??computed.taxAmount);
  const subtotalWithVat=rounded(invoice.subtotal??computed.subtotal);
  const additional=rounded(extras.reduce((s,x)=>s+(Number(x.amount)||0),0));
  const paid=rounded(invoice.paid_amount);
  return {
    invoice,items:computed.lines,extras,
    subtotalWithVat,vat,additional,total,paid,remaining:rounded(Math.max(0,total-paid)),
    beforeVAT:rounded(subtotalWithVat-vat),
    difference:Math.abs(total-computed.grandTotal),status:statusOf(invoice),
    businessName:safe(options.brand?.brand_name||options.business?.settings?.legal_name||options.business?.name||'Restaurant'),
    businessTax:safe(options.brand?.vat_registration_number||options.business?.tax_number||options.business?.vat_number||options.business?.settings?.tax_number),
    address:safe(options.brand?.address||options.business?.address||options.branch?.location),
    branch:safe(options.branch?.name||options.branch?.label||invoice.branch),
    currency:invoice.currency||options.currency||'SAR',
  };
}
export function createBrandedPurchaseInvoicePDF(invoice,options={}){
 const {lang='en',business,brand,branch,currency}=options;
 const language=WORDS[lang]?lang:'en',rtl=language!=='en';
 const m=buildPurchaseInvoiceDocument(invoice,{business,brand,branch,currency});
 const doc=new jsPDF({format:'a4',orientation:'portrait',unit:'mm',putOnlyUsedFonts:true});
 prepareLocalizedPdf(doc,{lang:language,dir:rtl?'rtl':'ltr'});
 renderPurchaseInvoiceReference(doc,invoice,m,{
   lang:language,business,brand,branch,
   payments:options.payments||[],auditEvents:options.auditEvents||[],
 });
 const filename=safePdfFilename('BizCTRL-Purchase-'+safe(invoice.invoice_number||invoice.id).replace(/[^a-zA-Z0-9_-]/g,''),language);
 return {doc,filename,model:m};
}
export function downloadPurchaseInvoicePDF(invoice,options={}){
 const {doc,filename}=createBrandedPurchaseInvoicePDF(invoice,options);
 doc.save(filename);
 return filename;
}

/** Shares the *actual PDF file* on iOS/Android supported browsers via native
 * share sheet. WhatsApp must be chosen by the user; no app can silently send
 * a PDF to WhatsApp contacts without an authenticated messaging integration.
 */
export async function sharePurchaseInvoicePDF(invoice,options={}){
 const {doc,filename,model}=createBrandedPurchaseInvoicePDF(invoice,options);
 const blob=doc.output('blob');
 const file=typeof File!=='undefined'
   ?new File([blob],filename,{type:'application/pdf'}):null;
 if(file && typeof navigator!=='undefined' && navigator.canShare?.({files:[file]}) && navigator.share){
  try{
   await navigator.share({files:[file],title:'BizCTRL Purchase '+safe(invoice.invoice_number)});
   return {shared:true};
  }catch(e){
   if(e?.name==='AbortError')return {cancelled:true};
   // If the system share sheet failed, fall back to a real downloadable PDF.
  }
 }
 doc.save(filename);
 const text=['BizCTRL Purchase Invoice '+safe(invoice.invoice_number),
    safe(invoice.supplier_name),amountForShare(model.total,model.currency),
    'PDF downloaded. Attach it from Files to send on WhatsApp.'].join('\n');
 return {shared:false,downloaded:true,text,whatsappUrl:'https://wa.me/?text='+encodeURIComponent(text)};
}
const amountForShare=(n,c)=>cash(n)+' '+c;
