import QRCode from 'qrcode';
import { drawLocalizedPdfText } from './pdfLocalization';
import { calcPurchaseLine } from './procurementEngine';

const LANGUAGE = {
 en: {
  title:'Purchase Invoice',sub:'فاتورة مشتريات',business:'BUSINESS PROFILE',details:'INVOICE DETAILS',
  branch:'Branch',taxId:'VAT registration',address:'Address',supplier:'Supplier',date:'Invoice date',
  payment:'Payment method',status:'Status',reference:'Invoice number',item:'PRODUCT / ITEM',
  unit:'UNIT',qty:'QTY',unitPrice:'UNIT COST',discount:'DISC.',before:'BEFORE VAT',
  vat:'VAT',lineTotal:'INCL. VAT',notes:'NOTES',workflow:'APPROVAL WORKFLOW',
  created:'Created',reviewed:'Reviewed',approved:'Approved',auto:'Auto-approved',
  pending:'Pending',cancelled:'Cancelled',draft:'Draft',unknown:'Not recorded',
  financials:'FINANCIAL SUMMARY',subtotal:'Before VAT',vatAmount:'VAT',
  extras:'Additional costs',total:'TOTAL AMOUNT',paid:'Amount paid',remaining:'Remaining balance',
  qr:'Invoice reference QR',generated:'Generated by BizCTRL ERP',
  disclaimer:'Saved ERP amounts • Printing does not create a payment',
  mismatch:'Review: recorded and recomputed totals differ',
  more:'Continued items',unitNo:'Item',noItems:'No invoice items recorded',
  paymentMixed:'Multiple payment methods',
 },
 ar: {
  title:'فاتورة مشتريات',sub:'Purchase Invoice',business:'بيانات المنشأة',details:'بيانات الفاتورة',
  branch:'الفرع',taxId:'الرقم الضريبي',address:'العنوان',supplier:'المورد',date:'تاريخ الفاتورة',
  payment:'طريقة الدفع',status:'حالة الفاتورة',reference:'رقم الفاتورة',item:'الصنف',
  unit:'الوحدة',qty:'الكمية',unitPrice:'سعر الوحدة',discount:'الخصم',before:'قبل الضريبة',
  vat:'الضريبة',lineTotal:'شامل الضريبة',notes:'ملاحظات',workflow:'سير الاعتماد',
  created:'تم الإنشاء',reviewed:'تمت المراجعة',approved:'تم الاعتماد',auto:'اعتماد تلقائي',
  pending:'قيد الانتظار',cancelled:'ملغاة',draft:'مسودة',unknown:'غير مسجل',
  financials:'ملخص الفاتورة',subtotal:'المجموع قبل الضريبة',vatAmount:'ضريبة القيمة المضافة',
  extras:'تكاليف إضافية',total:'الإجمالي شامل الضريبة',paid:'المبلغ المدفوع',remaining:'الرصيد المتبقي',
  qr:'رمز مرجع الفاتورة',generated:'تم إنشاء المستند بواسطة BizCTRL ERP',
  disclaimer:'أرقام السجل المحفوظ • لا تُنشئ الطباعة دفعة جديدة',
  mismatch:'تنبيه: إجمالي الأصناف لا يطابق المبلغ المسجل',
  more:'تابع الأصناف',unitNo:'صنف',noItems:'لم تُسجل أصناف',
  paymentMixed:'طرق دفع متعددة',
 },
 fa: {
  title:'فاکتور خرید',sub:'Purchase Invoice',business:'اطلاعات کسب‌وکار',details:'جزئیات فاکتور',
  branch:'شعبه',taxId:'شماره مالیاتی',address:'آدرس',supplier:'تأمین‌کننده',date:'تاریخ فاکتور',
  payment:'روش پرداخت',status:'وضعیت فاکتور',reference:'شماره فاکتور',item:'محصول',
  unit:'واحد',qty:'تعداد',unitPrice:'قیمت واحد',discount:'تخفیف',before:'قبل از مالیات',
  vat:'مالیات',lineTotal:'مجموع با مالیات',notes:'یادداشت‌ها',workflow:'مراحل تأیید',
  created:'ایجادشده',reviewed:'بررسی‌شده',approved:'تأییدشده',auto:'تأیید خودکار',
  pending:'در انتظار',cancelled:'لغوشده',draft:'پیش‌نویس',unknown:'ثبت نشده',
  financials:'خلاصه مالی',subtotal:'قبل از مالیات',vatAmount:'مالیات ارزش افزوده',
  extras:'مصارف اضافی',total:'مجموع با مالیات',paid:'پرداخت‌شده',remaining:'مانده',
  qr:'کد مرجع فاکتور',generated:'تولیدشده توسط BizCTRL ERP',
  disclaimer:'مبالغ ثبت‌شده ERP • تولید فایل پرداخت جدیدی ایجاد نمی‌کند',
  mismatch:'هشدار: مجموع اقلام و مبلغ ثبت‌شده متفاوت است',
  more:'ادامه اقلام',unitNo:'قلم',noItems:'اقلام ثبت نشده',
  paymentMixed:'روش‌های مختلف پرداخت',
 }
};
const NAVY=[13,32,70], BLUE=[22,104,233], CYAN=[0,191,218], FADED=[99,116,140], LIGHT=[239,248,255],
 BORDER=[221,233,245], GREEN=[0,154,107], RED=[217,48,78];
const currencyAmount=(n,c)=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)+' '+c;
const display=(x)=>x===null||x===undefined||String(x).trim()===''?'—':String(x).trim();
const shorten=(x,length)=>{const s=display(x);return s.length>length?s.slice(0,length-1)+'…':s;};
const firstStr=(...values)=>values.find(v=>v!==null&&v!==undefined&&String(v).trim()!=='')||null;
function wrapWords(input,max=32){
 const words=display(input).split(/\s+/),lines=[];let line='';
 for(const word of words){
  if(line&&line.length+word.length+1>max){lines.push(line);line='';}
  if(word.length>max){
   if(line){lines.push(line);line='';}
   for(let i=0;i<word.length;i+=max)lines.push(word.slice(i,i+max));
  }else line=line?line+' '+word:word;
 }
 if(line)lines.push(line);
 return lines.length?lines:['—'];
}
export function invoiceApprovalSteps(invoice,history=[]){
 const steps=[];
 if(invoice.created_date)steps.push({type:'created',date:invoice.created_date,who:invoice.created_by||null});
 const rows=(Array.isArray(history)?history:[]).sort((a,b)=>String(a.created_date||'').localeCompare(String(b.created_date||'')));
 const reviewed=rows.find(x=>/review|مراجع/i.test(String(x.action||'')));
 if(reviewed)steps.push({type:'reviewed',date:reviewed.created_date,who:reviewed.user_name||null});
 const status=invoice.approval_status;
 if(['approved','auto_approved'].includes(status)){
  const event=rows.find(x=>/approv/i.test(String(x.action||'')));
  steps.push({type:status==='auto_approved'?'auto':'approved',
   date:event?.created_date||null,who:event?.user_name||null});
 }
 if(status==='pending' && !steps.some(x=>x.type==='pending'))steps.push({type:'pending',date:null});
 return steps;
}
export function invoicePaymentLabel(invoice,payments=[],language='en'){
 const w=LANGUAGE[language]||LANGUAGE.en;
 const methods=[...new Set((Array.isArray(payments)?payments:[])
  .map(p=>String(p.payment_method||'').trim()).filter(Boolean))];
 if(!methods.length)return firstStr(invoice.payment_method)||w.unknown;
 return methods.length===1?methods[0]:w.paymentMixed;
}
const pageLineFont=6.4;
export function renderPurchaseInvoiceReference(doc,invoice,model,{lang='en',business,brand,branch,payments=[],auditEvents=[]}={}){
 const language=LANGUAGE[lang]?lang:'en',w=LANGUAGE[language];
 const rtl=language!=='en';
 const currency=model.currency, invoiceNumber=display(invoice.invoice_number||invoice.id);
 const L=9,R=201,CW=R-L;
 const txt=(v,x,y,{size=8,bold=false,color=NAVY,align,limit,maxWidth}={})=>
   drawLocalizedPdfText(doc,limit?shorten(v,limit):display(v),x,y,
    {rtl,bold,size,color,align:align||(rtl?'right':'left'),maxWidth});
 const roundedBox=(x,y,width,height,fill=[255,255,255],line=BORDER,radius=2.3)=>{
  doc.setFillColor(...fill);if(line)doc.setDrawColor(...line);
  doc.roundedRect(x,y,width,height,radius,radius,line?'FD':'F');
 };
 const field=(label,value,x,y,wid,{tone=NAVY,labelWidth=30}={})=>{
  // Separating labels from values avoids bidi/font corruption in mixed records.
  txt(label,x+2,y,{size:6.5,color:FADED,maxWidth:labelWidth,align:'left',limit:26});
  txt(value,x+wid-2,y,{size:7.6,color:tone,bold:true,maxWidth:wid-labelWidth-6,align:'right',limit:32});
 };
 const icon=(x,y,kind='doc',color=BLUE)=>{
  doc.setDrawColor(...color);doc.setLineWidth(.38);
  if(kind==='check'){doc.circle(x+2,y-1.2,1.8);doc.line(x+1,y-1.2,x+1.8,y-.5);doc.line(x+1.8,y-.5,x+3.2,y-2);return;}
  doc.roundedRect(x,y-3,4.4,5.6,.5,.5,'S');
  doc.line(x+.9,y-1.8,x+3.4,y-1.8);doc.line(x+.9,y-.1,x+3,y-.1);
 };
 const brandMark=(x,y,scale=1)=>{
  const sz=5.5*scale, gap=1.15*scale;
  [[0,0,BLUE],[1,0,CYAN],[0,1,BLUE],[1,1,CYAN]].forEach(([cx,cy,color])=>{
   doc.setFillColor(...color);doc.roundedRect(x+cx*(sz+gap),y+cy*(sz+gap),sz,sz,1*scale,1*scale,'F');
  });
 };
 const smallHeading=(s,x,y,accent=BLUE)=>{roundedBox(x,y-5,5,5,[235,245,255],null,1);icon(x+.45,y-.2,'doc',accent);
  txt(s,x+8,y,{size:8.8,bold:true,color:NAVY,limit:30,align:'left'});};
 const drawHeader=(continuation=false)=>{
   doc.setFillColor(248,252,255);doc.rect(0,0,210,34,'F');
   brandMark(10,7.2,1.5);
   txt('Biz',30,17,{size:22,bold:true,align:'left',color:NAVY});
   txt('CTRL',46.5,17,{size:22,bold:true,align:'left',color:CYAN});
   txt('Restaurant ERP System',30,23,{size:7.2,align:'left',color:FADED});
   txt(w.title,198,16,{size:16.8,bold:true,align:'right',color:NAVY});
   txt(w.sub,198,23,{size:8.5,bold:true,align:'right',color:BLUE});
   roundedBox(183,26,15,5.4,[227,243,255],null,1.4);
   txt('ERP PDF',190.5,29.7,{size:6.5,bold:true,align:'center',color:BLUE});
   doc.setDrawColor(...BORDER);doc.line(L,34,R,34);
   if(continuation)txt(w.more+' • '+invoiceNumber,L+2,40,{size:7.2,color:BLUE,align:'left'});
 };
 const infoCards=()=>{
  roundedBox(L,37,94,48,[248,252,255]);
  roundedBox(106,37,95,48,[248,252,255]);
  smallHeading(w.business,14,45);
  txt(model.businessName,17,53,{size:12,bold:true,color:NAVY,limit:36,maxWidth:83,align:'left'});
  field(w.branch,model.branch,13,61,86,{labelWidth:25});
  field(w.taxId,model.businessTax,13,69,86,{labelWidth:26});
  field(w.address,model.address,13,77,86,{labelWidth:24});
  smallHeading(w.details,111,45);
  field(w.reference,invoiceNumber,110,53,88,{labelWidth:29,tone:BLUE});
  field(w.date,invoice.date,110,61,88,{labelWidth:27});
  field(w.supplier,invoice.supplier_name,110,69,88,{labelWidth:29});
  field(w.payment,invoicePaymentLabel(invoice,payments,language),110,77,88,{labelWidth:29});
  const statusLabel=model.status==='approved'?w.approved:w[model.status]||w.unknown;
  roundedBox(155,79,43,5.2,model.status==='approved'?[225,249,240]:[238,244,255],null,1.5);
  txt(w.status+': '+statusLabel,176.5,82.7,{size:6.8,bold:true,
   align:'center',color:model.status==='approved'?GREEN:BLUE,limit:45});
 };
 const colSpecs=[
  {key:'num',width:9,title:'#'},
  {key:'item',width:48,title:w.item},
  {key:'unit',width:15,title:w.unit},
  {key:'qty',width:13,title:w.qty},
  {key:'unit_cost',width:21,title:w.unitPrice},
  {key:'discount',width:18,title:w.discount},
  {key:'before',width:21,title:w.before},
  {key:'vat',width:19,title:w.vat},
  {key:'sum',width:28,title:w.lineTotal},
 ];
 // exact width = 192 mm. Printed physical order follows chosen UI direction.
 const tableColumns=rtl?[...colSpecs].reverse():colSpecs;
 const drawTableHead=(y)=>{
  roundedBox(L,y,CW,11,[227,241,254],null,1.4);
  let x=L;
  for(const col of tableColumns){
   txt(col.title,x+col.width/2,y+7,{size:6.2,bold:true,color:NAVY,align:'center',
     limit:15,maxWidth:col.width-1});
   x+=col.width;
  }
 };
 const drawLine=(item,index,y)=>{
  const nameLines=wrapWords(item.product_name||item.name||item.description,23).slice(0,4);
  const height=Math.max(12.5,2.3+5.1*nameLines.length);
  roundedBox(L,y,CW,height,index%2===0?[251,253,255]:[246,250,254],null,0.6);
  let x=L;
  const result=calcPurchaseLine(item);
  const values={
   num:String(index+1),unit:item.unit||item.unit_name||'—',qty:String(item.quantity),
   unit_cost:currencyAmount(item.unit_cost,''),discount:currencyAmount(result.discountAmount,''),
   before:currencyAmount(result.discountedAmount,''),vat:currencyAmount(result.taxAmount,''),
   sum:currencyAmount(item.line_total,''),
  };
  for(const col of tableColumns){
   if(col.key==='item'){
    const dataImage=firstStr(item.image_data,item.image_base64,item.imageData);
    const imgX=x+(rtl?col.width-9:1.3);
    if(dataImage&&/^data:image\/(?:png|jpe?g);base64,/i.test(dataImage)){
      try{doc.addImage(dataImage,imgX,y+1.1,7.8,Math.min(9,height-2));}catch{/* no fake image */}}
    for(let k=0;k<nameLines.length;k++){
      txt(nameLines[k],x+col.width/2,y+5.1+k*4.9,{size:7.3,bold:k===0,align:'center',
        maxWidth:col.width-10,limit:27});
    }
   }else{
    txt(values[col.key],x+col.width/2,y+Math.min(height/2+2,8),{
      size:col.key==='sum'?7.6:7.1,bold:col.key==='sum',
      color:col.key==='sum'?BLUE:NAVY,align:'center',maxWidth:col.width-1,limit:20});
   }
   x+=col.width;
  }
  doc.setDrawColor(...BORDER);doc.line(L,y+height,R,y+height);
  return height;
 };
 const makeFooter=()=>{
  for(let p=1;p<=doc.getNumberOfPages();p++){
   doc.setPage(p);
   doc.setDrawColor(...BORDER);doc.line(9,272,201,272);
   brandMark(10,277,.9);txt('BizCTRL',24.7,283,{size:13.2,bold:true,color:NAVY,align:'left'});
   txt('Restaurant ERP System',24.7,288,{size:6,color:FADED,align:'left'});
   txt(w.generated,83,281,{size:7,bold:true,color:NAVY,align:'center',maxWidth:95});
   txt(w.disclaimer,83,287,{size:5.8,color:FADED,align:'center',maxWidth:100});
   // Pure reference QR. Not a tax validation QR or an official ZATCA stamp.
   try{
    const payload='BizCTRL invoice reference: '+invoiceNumber;
    const qr=QRCode.create(payload,{errorCorrectionLevel:'M'}).modules;
    const cell=16/qr.size,originX=162,originY=274;
    doc.setFillColor(255,255,255);doc.rect(originX,originY,16,16,'F');
    doc.setFillColor(...NAVY);
    for(let j=0;j<qr.size;j++)for(let i=0;i<qr.size;i++)
      if(qr.get(i,j))doc.rect(originX+i*cell,originY+j*cell,cell+.025,cell+.025,'F');
    txt(w.qr,180,281,{size:5.8,color:FADED,align:'left',limit:27});
   }catch{/* malformed missing reference has no QR */}
   txt(invoiceNumber,198,286,{size:6.7,bold:true,color:BLUE,align:'right',limit:28});
   txt(p+' / '+doc.getNumberOfPages(),198,292,{size:6.2,color:FADED,align:'right'});
  }
 };
 const approvalSteps=invoiceApprovalSteps(invoice,auditEvents);
 const finishSummary=(y)=>{
  const panelY=Math.max(183,y+3);
  roundedBox(L,panelY,104,28,[248,252,255]);
  smallHeading(w.notes,L+4,panelY+8);
  const noteLines=wrapWords(invoice.notes||w.unknown,41).slice(0,3);
  noteLines.forEach((line,i)=>txt(line,rtl?108:15,panelY+16+i*4,{size:7.1,color:FADED,
    align:rtl?'right':'left',maxWidth:92}));
  roundedBox(L,panelY+32,104,42,[248,252,255]);
  smallHeading(w.workflow,L+4,panelY+40);
  const shown=approvalSteps.length?approvalSteps.slice(0,3):[{type:'draft'}];
  shown.forEach((step,i)=>{
    const point=L+19+i*33.5;
    if(i<shown.length-1){
      doc.setDrawColor(...BORDER);doc.setLineWidth(.6);doc.line(point+2.1,panelY+53,point+31.4,panelY+53);
    }
    doc.setFillColor(...(step.type==='pending'?[227,238,255]:[220,248,234]));
    doc.circle(point,panelY+53,3,'F');
    icon(point-2.0,panelY+55,step.type==='pending'?'doc':'check',
      step.type==='pending'?BLUE:GREEN);
    txt(w[step.type]||w.unknown,point,panelY+62,{size:6.8,bold:true,
      color:NAVY,align:'center',limit:19,maxWidth:30});
    if(step.date)txt(String(step.date).slice(0,16).replace('T',' '),point,panelY+69,{
      size:6,color:FADED,align:'center',limit:18});
  });
  const right=119;
  roundedBox(right,panelY,82,74,[249,252,255]);
  smallHeading(w.financials,right+4,panelY+8);
  const financialRows=[
   [w.subtotal,model.beforeVAT],
   [w.vatAmount,model.vat],
   [w.extras,model.additional],
   [w.total,model.total],
   [w.paid,model.paid],
   [w.remaining,model.remaining],
  ];
  financialRows.forEach(([label,value],i)=>{
    const ty=panelY+19+i*9.5;
    if(i===3)roundedBox(right+2,ty-5.8,78,9.1,[224,241,255],null,1);
    txt(label,right+5,ty,{size:7,bold:i===3,color:i===3?BLUE:FADED,align:'left',
      maxWidth:40,limit:25});
    txt(currencyAmount(value,currency),right+78,ty,{size:i===3?9.2:7.7,
      color:i===5?GREEN:NAVY,bold:i>=3,align:'right',maxWidth:37});
  });
  if(model.difference>.05)txt(w.mismatch,L+3,panelY+78.5,{
    size:6.4,color:RED,align:'left',maxWidth:105});
 };
 drawHeader();
 infoCards();
 let y=93;
 drawTableHead(y);y=105;
 const lines=model.items||[];
 if(!lines.length){txt(w.noItems,L+8,y+7,{size:8,color:FADED,align:'left'});y+=15;}
 for(let idx=0;idx<lines.length;idx++){
  const item=lines[idx];
  const needed=Math.max(12.5,2.3+5.1*Math.min(4,wrapWords(item.product_name||item.name||item.description,23).length));
  if(y+needed>191){
   doc.addPage();drawHeader(true);drawTableHead(44);y=56;
  }
  y+=drawLine(item,idx,y);
 }
 if(Math.max(183,y+3)+75>270){
  doc.addPage();drawHeader(true);y=56;
 }
 finishSummary(y);
 makeFooter();
 return doc;
}
