// Every combination is a real menu item: its server price and recipe remain authoritative.
export function customizationCopy(lang='en') {
 return ({en:{title:'Customize food & prices',hint:'Choose a starting template, then set your own options, names, prices and ingredients.',template:'Business template',custom:'Custom food',chicken:'Chicken & rice',burger:'Burger',pizza:'Pizza',cafe:'Café',group:'Option group',values:'Choices (one per line)',addGroup:'Add option group',remove:'Remove',generate:'Generate choices',limit:'Use 1–4 distinct option groups, with 1–12 choices each and at most 100 combinations.',preview:'Cashier preview',options:'Food options',new:'Customizable food',archived:'Archived choices',empty:'Configure and enable at least one choice.',addPOS:'Add POS',devices:'POS devices',deviceName:'POS name',emptyPOS:'No POS devices added',emptyHint:'Add the cashier devices your branch needs.',savePOS:'Save POS',archive:'Archive POS',restore:'Restore POS',archivedPOS:'Archived POS',archiveHint:'Close the shift and settle orders before archiving. Sales history is retained.',managePOS:'Manage POS',nameHint:'For example: Front counter',back:'Cancel',edit:'Edit',generating:'Review every price and recipe before saving.'},
 ar:{title:'تخصيص الطعام والأسعار',hint:'اختر قالباً ثم حدد الخيارات والأسماء والأسعار والمكونات حسب نشاطك.',template:'قالب النشاط',custom:'طعام مخصص',chicken:'دجاج وأرز',burger:'برجر',pizza:'بيتزا',cafe:'مقهى',group:'مجموعة الخيارات',values:'الخيارات (كل خيار في سطر)',addGroup:'إضافة مجموعة خيارات',remove:'إزالة',generate:'إنشاء الخيارات',limit:'من ١ إلى ٤ مجموعات مختلفة، ومن ١ إلى ١٢ خياراً للمجموعة، وبحد أقصى ١٠٠ تركيبة.',preview:'معاينة الكاشير',options:'خيارات الطعام',new:'طعام قابل للتخصيص',archived:'خيارات مؤرشفة',empty:'فعّل خياراً واحداً على الأقل.',addPOS:'إضافة POS',devices:'أجهزة الكاشير',deviceName:'اسم جهاز الكاشير',emptyPOS:'لم تتم إضافة أجهزة كاشير',emptyHint:'أضف أجهزة الكاشير التي يحتاجها الفرع.',savePOS:'حفظ الجهاز',archive:'أرشفة الجهاز',restore:'استعادة الجهاز',archivedPOS:'أجهزة مؤرشفة',archiveHint:'أغلق الوردية وسوّ الطلبات قبل الأرشفة. يبقى سجل المبيعات محفوظاً.',managePOS:'إدارة أجهزة POS',nameHint:'مثال: الكاشير الأمامي',back:'إلغاء',edit:'تعديل',generating:'راجع سعر ووصفة كل خيار قبل الحفظ.'},
 fa:{title:'تنظیم غذا و قیمت‌ها',hint:'قالب را انتخاب کنید؛ گزینه‌ها، نام‌ها، قیمت‌ها و مواد لازم را مطابق کسب‌وکار خود تنظیم کنید.',template:'قالب کسب‌وکار',custom:'غذای دلخواه',chicken:'مرغ و برنج',burger:'برگر',pizza:'پیتزا',cafe:'کافه',group:'گروه گزینه‌ها',values:'گزینه‌ها (هر کدام در یک خط)',addGroup:'افزودن گروه گزینه',remove:'حذف',generate:'ساخت گزینه‌ها',limit:'۱ تا ۴ گروه متفاوت، هر گروه ۱ تا ۱۲ گزینه و حداکثر ۱۰۰ ترکیب.',preview:'پیش‌نمایش کاشیر',options:'گزینه‌های غذا',new:'غذای قابل تنظیم',archived:'گزینه‌های آرشیف‌شده',empty:'حداقل یک گزینه را فعال کنید.',addPOS:'افزودن POS',devices:'دستگاه‌های کاشیر',deviceName:'نام دستگاه POS',emptyPOS:'هنوز دستگاه POS اضافه نشده',emptyHint:'به تعداد مورد نیاز شعبه، دستگاه کاشیر اضافه کنید.',savePOS:'ذخیره دستگاه',archive:'آرشیف دستگاه',restore:'فعال‌سازی دوباره',archivedPOS:'دستگاه‌های آرشیف‌شده',archiveHint:'پیش از آرشیف، شیفت را ببندید و سفارش‌ها را تسویه کنید. سابقهٔ فروش حفظ می‌شود.',managePOS:'مدیریت دستگاه‌های POS',nameHint:'مثال: کاشیر ورودی',back:'لغو',edit:'ویرایش',generating:'پیش از ذخیره، قیمت و دستور پخت هر گزینه را بررسی کنید.'}})[lang]||customizationCopy('en');
}
export function optionTemplate(kind,lang='en') {
 const presets={
 en:{custom:[['Option',['Standard']]],burger:[['Size',['Single','Double']],['Meal',['Burger only','With fries & drink']]],pizza:[['Size',['Small','Medium','Large']],['Crust',['Thin','Classic']]],cafe:[['Size',['Small','Medium','Large']],['Milk',['Regular','Oat']],['Sugar',['No sugar','Regular']]]},
 ar:{custom:[['الخيار',['عادي']]],burger:[['الحجم',['سنجل','دبل']],['الوجبة',['برجر فقط','مع بطاطس ومشروب']]],pizza:[['الحجم',['صغير','وسط','كبير']],['العجينة',['رقيقة','عادية']]],cafe:[['الحجم',['صغير','وسط','كبير']],['الحليب',['عادي','شوفان']],['السكر',['بدون سكر','عادي']]]},
 fa:{custom:[['گزینه',['معمولی']]],burger:[['اندازه',['سینگل','دبل']],['سرو',['برگر تنها','با کچالو و نوشابه']]],pizza:[['اندازه',['کوچک','متوسط','بزرگ']],['خمیر',['نازک','معمولی']]],cafe:[['اندازه',['کوچک','متوسط','بزرگ']],['شیر',['معمولی','جو دوسر']],['شکر',['بدون شکر','معمولی']]]}};
 return (presets[lang]||presets.en)[kind].map(([label,values])=>({label,values:values.join('\n')}));
}
export const choiceSignature=choices=>JSON.stringify((choices||[]).map(({label,value})=>[label,value]));
export function buildCombinations(axes) {
 const normalized=axes.map(a=>({label:a.label.trim(),values:a.values.split('\n').map(v=>v.trim()).filter(Boolean)}));
 if(normalized.length<1||normalized.length>4||new Set(normalized.map(a=>a.label)).size!==normalized.length||normalized.some(a=>!a.label||a.label.length>60||!a.values.length||a.values.length>12||new Set(a.values).size!==a.values.length||a.values.some(v=>v.length>60))||normalized.reduce((n,a)=>n*a.values.length,1)>100)throw new Error('Invalid choices');
 return normalized.reduce((rows,a)=>rows.flatMap(row=>a.values.map(value=>[...row,{label:a.label,value}])),[[]]);
}
export function axesFromItems(items) {
 const axes=new Map();
 for(const item of (items.some(m=>m.active)?items.filter(m=>m.active):items))for(const choice of item.variant_options||[]) {
  if(!axes.has(choice.label))axes.set(choice.label,new Set());axes.get(choice.label).add(choice.value);
 }
 return [...axes].map(([label,values])=>({label,values:[...values].join('\n')}));
}
