import { isRestaurantPOSPortal } from '@/lib/productImportAccess';

export function restaurantMaterialFilter(organization) {
  return isRestaurantPOSPortal(organization) ? { restaurant_product_type: 'raw_material' } : {};
}

export const restaurantProductCopy = lang => ({
 en: { title:'Restaurant products', menu:'Sales menu', raw:'Raw materials & purchases', hint:'Sell dishes through POS. Purchase ingredients into stock and link them to each dish using a recipe.', add:'New dish', edit:'Edit dish & recipe', search:'Search dishes', empty:'No dishes in this branch. Add your first dish.', branch:'Branch', choose:'Select a branch', image:'Food image URL (HTTPS)', persian:'Persian name', active:'Available in POS', save:'Save dish', inactive:'Inactive', recipe:'Recipe linked', untracked:'No stock deduction', materials:'Raw materials', materialHint:'Supplier purchases and ingredient stock', purchase:'Purchase order', pos:'Open touch POS', loading:'Loading…', rawSearch:'Search materials', rawEmpty:'No raw materials. Add chicken, rice or another ingredient.', setup:'Dish & recipe', recipeHint:'Quantity is per portion in the inventory unit shown. Sending to the kitchen deducts ingredients once.', rawConflict:'Existing stock products are kept in Raw materials. Add a separate dish here to sell prepared food.'},
 ar: { title:'منتجات المطعم', menu:'قائمة البيع', raw:'المواد الخام والمشتريات', hint:'بيع الأطباق عبر الكاشير، وشراء المواد للمخزون وربطها بالأطباق عبر الوصفات.', add:'طبق جديد', edit:'تعديل الطبق والوصفة', search:'بحث في الأطباق', empty:'لا توجد أطباق في هذا الفرع. أضف طبقاً جديداً.', branch:'الفرع', choose:'اختر الفرع', image:'رابط صورة الطعام (HTTPS)', persian:'الاسم بالفارسية', active:'متاح في الكاشير', save:'حفظ الطبق', inactive:'غير نشط', recipe:'مرتبط بوصفة', untracked:'بدون خصم مخزون', materials:'المواد الخام', materialHint:'مشتريات الموردين ومخزون المكونات', purchase:'أمر شراء', pos:'فتح كاشير اللمس', loading:'جاري التحميل…', rawSearch:'بحث في المواد الخام', rawEmpty:'لا توجد مواد خام. أضف الدجاج أو الأرز أو مكونات أخرى.', setup:'الطبق والوصفة', recipeHint:'الكمية لكل حصة بوحدة المخزون الموضحة. يخصم إرسال الطلب للمطبخ المكونات مرة واحدة.', rawConflict:'تبقى منتجات المخزون في المواد الخام. أضف طبقاً مستقلاً لبيع الطعام المحضر.'},
 fa: { title:'محصولات رستورانت', menu:'منوی فروش غذا', raw:'مواد اولیه و خریداری', hint:'غذا از طریق پوس فروخته می‌شود. مواد اولیه را از سپلایر بخرید و با دستور پخت به غذا وصل کنید.', add:'غذای جدید', edit:'ویرایش غذا و دستور پخت', search:'جستجوی غذا', empty:'در این فرع غذایی ثبت نشده است. غذای جدید اضافه کنید.', branch:'فرع', choose:'انتخاب فرع', image:'لینک تصویر غذا (HTTPS)', persian:'نام فارسی', active:'فعال در پوس', save:'ذخیره غذا', inactive:'غیرفعال', recipe:'دارای دستور پخت', untracked:'بدون کسر موجودی', materials:'مواد اولیه', materialHint:'خرید از سپلایر و موجودی مواد اولیه', purchase:'سفارش خرید', pos:'باز کردن پوس لمسی', loading:'در حال بارگذاری…', rawSearch:'جستجوی مواد اولیه', rawEmpty:'مواد اولیه وجود ندارد. مرغ، برنج یا مواد دیگر را اضافه کنید.', setup:'غذا و دستور پخت', recipeHint:'مقدار هر ماده برای یک پرس، با واحد انبار وارد شود. هنگام ارسال به آشپزخانه فقط یک بار از موجودی کم می‌شود.', rawConflict:'محصولات دارای موجودی در بخش مواد اولیه باقی می‌مانند. برای فروش غذای پخته، غذای جداگانه بسازید.'}
}[lang] || restaurantProductCopy('en'));
