/**
 * Sales Invoice Service
 *
 * Financial values remain canonical: Sales Total = Cash + Network + Credit;
 * localization changes only presentation language, direction, and PDF typography.
 */
import { supabase } from '@/api/supabaseClient';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import {
  drawLocalizedPdfText,
  prepareLocalizedPdf,
  safePdfFilename,
} from '@/lib/pdfLocalization';

const defaultInvoiceOptions = Object.freeze({
  lang: 'en',
  dir: 'ltr',
  translateLiteral: (value) => value,
});

function optionsWithDefaults(options = {}) {
  return { ...defaultInvoiceOptions, ...options };
}

function textFor(options, value) {
  return options.translateLiteral?.(value) || value;
}

function escapeHTML(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatMoney(value, currency) {
  const amount = Number(value || 0);
  // IDs, currency codes, and numerical ERP values intentionally remain LTR.
  // This also avoids viewer-dependent Arabic/Persian digit shaping in PDFs.
  return `${currency || ''}${amount.toLocaleString('en-US')}`;
}

function invoiceStatusColor(status) {
  return {
    Balanced: ['#065f46', '#d1fae5'],
    Shortage: ['#991b1b', '#fee2e2'],
    Overage: ['#92400e', '#fef3c7'],
  }[status] || ['#1e40af', '#dbeafe'];
}

function invoiceDetails(invoice, currency, options) {
  const label = (value) => textFor(options, value);
  const money = (value) => formatMoney(value, currency, options.lang);
  return {
    title: label('SALES INVOICE'),
    generatedBy: label('Generated by'),
    information: [
      [label('Date'), invoice.sale_date || '—'],
      [label('Branch'), invoice.branch || '—'],
      [label('Cashier'), invoice.cashier_name || '—'],
      [label('Shift'), invoice.shift || '—'],
    ],
    reconciliation: {
      title: label('Cash Reconciliation'),
      rows: [
        [label('Opening Cash'), money(invoice.opening_cash)],
        [label('Closing Cash'), money(invoice.closing_cash)],
        [label('Cash Difference'), `${Number(invoice.cash_difference) >= 0 ? '+' : ''}${money(invoice.cash_difference)}`],
        [label('Status'), label(invoice.cash_status || 'Balanced')],
      ],
    },
    sales: {
      title: label('Sales Summary'),
      rows: [
        [label('Cash Sales (Revenue)'), money(invoice.cash_sales)],
        [label('Network Sales'), money(invoice.network_sales)],
        [label('Credit Sales'), money(invoice.credit_sales)],
        [label('Sales Total'), money(invoice.sales_total)],
      ],
    },
  };
}

export async function generateSalesInvoiceNumber(restaurantId, saleDate) {
  try {
    const dateObj = saleDate ? new Date(saleDate) : new Date();
    const { data, error } = await supabase.rpc('generate_sales_invoice_number', {
      p_restaurant_id: restaurantId,
      p_date: format(dateObj, 'yyyy-MM-dd'),
    });
    if (error) throw error;
    return data;
  } catch (err) {
    console.warn('[salesInvoiceService] RPC failed, using fallback:', err.message);
    const dateStr = format(saleDate ? new Date(saleDate) : new Date(), 'yyyyMMdd');
    const rand = Math.floor(Math.random() * 9000) + 1000;
    return `INV-${dateStr}-${rand}`;
  }
}

export async function createSalesInvoice({ invoiceNumber, saleId, saleData, restaurantId, createdBy }) {
  const cashSales = Number(saleData.restaurant_cash || saleData.cash || 0);
  const networkSales = Number(saleData.restaurant_network || saleData.network || 0);
  const creditSales = Number(saleData.credit || 0);
  const salesTotal = Number(saleData.total_sales || (cashSales + networkSales + creditSales));
  const payload = {
    invoice_number: invoiceNumber,
    sale_id: saleId,
    restaurant_id: restaurantId || null,
    branch_id: saleData.branch_id || null,
    tenant_id: saleData.tenant_id || restaurantId || '',
    branch: saleData.branch,
    sale_date: saleData.date,
    opening_cash: Number(saleData.opening_cash || 0),
    closing_cash: Number(saleData.closing_cash || 0),
    cash_difference: Number(saleData.cash_difference || 0),
    cash_status: saleData.cash_status || 'Balanced',
    cash_sales: cashSales,
    network_sales: networkSales,
    credit_sales: creditSales,
    sales_total: salesTotal,
    cashier_name: saleData.cashier_name || '',
    shift: saleData.shift || '',
    notes: saleData.notes || '',
    cash_notes: saleData.cash_notes || '',
    sales_notes: saleData.sales_notes || '',
    manager_approval: saleData.manager_approval || false,
    manager_approved_by: saleData.manager_approved_by || '',
    pos_entries_json: saleData.pos_entries_json || '',
    credit_entries_json: saleData.credit_entries_json || '',
    created_by: createdBy || saleData.created_by || '',
  };
  const { data, error } = await supabase
    .from('sales_invoices')
    .upsert(payload, { onConflict: 'restaurant_id,invoice_number' })
    .select()
    .single();
  if (error) throw error;
  return data;
}

/** Localized HTML is retained for browser printing when a native print dialog is preferred. */
export function buildInvoiceHTML(invoice, brandName = 'BizCTRL', currency = '', options = {}) {
  const resolved = optionsWithDefaults(options);
  const rtl = resolved.dir === 'rtl' || resolved.lang === 'ar' || resolved.lang === 'fa';
  const details = invoiceDetails(invoice, currency, resolved);
  const [statusColor, statusBackground] = invoiceStatusColor(invoice.cash_status);
  const rowHTML = (row, index, total = false) => `<div class="row${total ? ' total' : ''}"><span>${escapeHTML(row[0])}</span><span class="value" dir="ltr">${escapeHTML(row[1])}</span></div>`;
  return `<!DOCTYPE html>
<html dir="${rtl ? 'rtl' : 'ltr'}" lang="${escapeHTML(resolved.lang)}">
<head>
<meta charset="UTF-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;700&family=Vazirmatn:wght@400;600;700&display=swap" rel="stylesheet">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: ${rtl ? "'Vazirmatn', 'Noto Naskh Arabic', Tahoma, sans-serif" : 'Arial, sans-serif'}; color: #1a1a1a; background: #fff; padding: 40px; max-width: 700px; margin: 0 auto; direction: ${rtl ? 'rtl' : 'ltr'}; }
  .header { text-align: center; border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
  .brand { font-size: 28px; font-weight: bold; color: #2563eb; } .invoice-title { font-size: 16px; color: #6b7280; margin-top: 4px; } .invoice-number { font-size: 22px; font-weight: bold; color: #1e40af; margin-top: 8px; direction:ltr; }
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; } .info-box { background: #f8fafc; border-radius: 8px; padding: 14px; border: 1px solid #e2e8f0; } .info-label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; } .info-value { font-size: 15px; font-weight: 600; margin-top: 4px; color: #1e293b; }
  .section { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 10px; padding: 20px; margin-bottom: 20px; } .cash-section { background: #f0fdf4; border: 1px solid #bbf7d0; } .section-title { font-size: 13px; font-weight: bold; color: #1e40af; margin-bottom: 14px; } .cash-section .section-title { color: #065f46; } .row { display: flex; justify-content: space-between; gap:16px; padding: 8px 0; border-bottom: 1px solid #dbeafe; } .row:last-child { border-bottom: none; } .row.total { font-size: 18px; font-weight: bold; color: #1e40af; border-top: 2px solid #2563eb; padding-top: 12px; margin-top: 4px; } .value { font-weight: 600; unicode-bidi: plaintext; } .status-badge { display: inline-block; padding: 5px 14px; border-radius: 20px; font-size: 13px; font-weight: bold; background: ${statusBackground}; color: ${statusColor}; } .footer { text-align: center; color: #9ca3af; font-size: 12px; border-top: 1px solid #e5e7eb; padding-top: 20px; margin-top: 30px; }
</style>
</head>
<body>
  <div id="invoice-content">
    <div class="header"><div class="brand">${escapeHTML(brandName)}</div><div class="invoice-title">${escapeHTML(details.title)}</div><div class="invoice-number">${escapeHTML(invoice.invoice_number)}</div></div>
    <div class="info-grid">${details.information.map(([key, value]) => `<div class="info-box"><div class="info-label">${escapeHTML(key)}</div><div class="info-value">${escapeHTML(value)}</div></div>`).join('')}</div>
    <div class="section cash-section"><div class="section-title">${escapeHTML(details.reconciliation.title)}</div>${details.reconciliation.rows.map((row, index) => index === 3 ? `<div class="row"><span>${escapeHTML(row[0])}</span><span class="status-badge">${escapeHTML(row[1])}</span></div>` : rowHTML(row, index)).join('')}</div>
    <div class="section"><div class="section-title">${escapeHTML(details.sales.title)}</div>${details.sales.rows.map((row, index) => rowHTML(row, index, index === details.sales.rows.length - 1)).join('')}</div>
    <div class="footer"><p>${escapeHTML(details.generatedBy)} ${escapeHTML(brandName)} • ${escapeHTML(invoice.invoice_number)}</p></div>
  </div>
</body></html>`;
}

export function createLocalizedInvoicePDF(invoice, brandName = 'BizCTRL', currency = '', options = {}) {
  const resolved = optionsWithDefaults(options);
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4', putOnlyUsedFonts: true });
  const { rtl } = prepareLocalizedPdf(doc, resolved);
  const details = invoiceDetails(invoice, currency, resolved);
  const W = 210;
  const left = 16;
  const right = W - left;
  const mainX = rtl ? right : left;
  let y = 20;
  const draw = (value, x, yy, opts = {}) => drawLocalizedPdfText(doc, value, x, yy, { rtl, ...opts });
  const drawRow = (label, value, total = false, color = [15, 23, 42]) => {
    doc.setDrawColor(219, 234, 254);
    doc.setLineWidth(total ? 0.7 : 0.25);
    doc.line(left + 4, y + 2.5, right - 4, y + 2.5);
    draw(label, mainX, y, { bold: total, size: total ? 12 : 10, color });
    draw(value, rtl ? left + 5 : right - 5, y, { bold: total, size: total ? 12 : 10, color, align: rtl ? 'left' : 'right' });
    y += total ? 10 : 8;
  };

  doc.setFillColor(37, 99, 235); doc.rect(0, 0, W, 33, 'F');
  draw(brandName, mainX, 13, { bold: true, size: 18, color: [255, 255, 255] });
  draw(details.title, mainX, 21, { bold: true, size: 10, color: [219, 234, 254] });
  draw(invoice.invoice_number, rtl ? left : right, 21, { bold: true, size: 10, color: [255, 255, 255], align: rtl ? 'left' : 'right' });
  y = 43;

  details.information.forEach(([label, value], index) => {
    const isRightColumn = index % 2 === 1;
    const boxX = rtl ? (isRightColumn ? 16 : 108) : (isRightColumn ? 108 : 16);
    doc.setFillColor(248, 250, 252); doc.roundedRect(boxX, y, 86, 19, 2, 2, 'F');
    draw(label, rtl ? boxX + 82 : boxX + 4, y + 6, { bold: true, size: 8, color: [100, 116, 139] });
    draw(value, rtl ? boxX + 82 : boxX + 4, y + 14, { bold: true, size: 10, color: [30, 41, 59] });
    if (index % 2 === 1) y += 23;
  });
  if (details.information.length % 2) y += 23;

  const section = (title, color, background, rows, isSales = false) => {
    doc.setFillColor(...background); doc.roundedRect(left, y, right - left, 11, 2, 2, 'F');
    draw(title, mainX, y + 7, { bold: true, size: 11, color });
    y += 16;
    rows.forEach(([label, value], index) => drawRow(label, value, isSales && index === rows.length - 1, color));
    y += 7;
  };
  section(details.reconciliation.title, [6, 95, 70], [240, 253, 244], details.reconciliation.rows);
  section(details.sales.title, [30, 64, 175], [239, 246, 255], details.sales.rows, true);

  doc.setDrawColor(226, 232, 240); doc.line(left, 277, right, 277);
  draw(`${details.generatedBy} ${brandName} • ${invoice.invoice_number}`, W / 2, 284, { bold: false, size: 8, color: [100, 116, 139], align: 'center' });
  return { doc, filename: safePdfFilename(invoice.invoice_number || 'sales-invoice', resolved.lang) };
}

export async function generateAndUploadPDF(invoice, brandName, currency, options = {}) {
  try {
    const resolved = optionsWithDefaults(options);
    const { doc, filename } = createLocalizedInvoicePDF(invoice, brandName, currency, resolved);
    const pdfBlob = doc.output('blob');
    const filePath = `invoices/${invoice.restaurant_id || 'default'}/${resolved.lang}/${filename}`;
    await supabase.storage.from('sales-invoices').upload(filePath, pdfBlob, { contentType: 'application/pdf', upsert: true });
    const { data: { publicUrl } } = supabase.storage.from('sales-invoices').getPublicUrl(filePath);
    // Keep the most recently generated report URL for backwards compatibility;
    // callers generate per-language URLs instead of treating this field as a locale cache.
    await supabase.from('sales_invoices').update({ pdf_url: publicUrl }).eq('invoice_number', invoice.invoice_number);
    return publicUrl;
  } catch (err) {
    console.error('[salesInvoiceService] PDF failed:', err);
    throw err;
  }
}

export async function shareInvoiceNative(invoice, brandName, currency, options = {}) {
  try {
    const resolved = optionsWithDefaults(options);
    const pdfUrl = await generateAndUploadPDF(invoice, brandName, currency, resolved);
    const response = await fetch(pdfUrl);
    const blob = await response.blob();
    const file = new File([blob], safePdfFilename(invoice.invoice_number || 'sales-invoice', resolved.lang), { type: 'application/pdf' });
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({ title: `${textFor(resolved, 'Invoice')} ${invoice.invoice_number}`, files: [file] });
    } else {
      window.open(pdfUrl, '_blank', 'noopener');
    }
  } catch (err) {
    console.error('[salesInvoiceService] Share failed:', err);
    shareInvoiceWhatsApp(invoice, currency, options);
  }
}

export function openInvoicePrint(invoice, brandName, currency, options = {}) {
  const html = buildInvoiceHTML(invoice, brandName, currency, optionsWithDefaults(options));
  const win = window.open('', '_blank', 'noopener');
  if (win) {
    win.document.write(html);
    win.document.close();
    win.focus();
  }
}

export async function downloadInvoicePDF(invoice, brandName, currency, options = {}) {
  try {
    const resolved = optionsWithDefaults(options);
    const pdfUrl = await generateAndUploadPDF(invoice, brandName, currency, resolved);
    const anchor = document.createElement('a');
    anchor.href = pdfUrl;
    anchor.download = safePdfFilename(invoice.invoice_number || 'sales-invoice', resolved.lang);
    anchor.target = '_blank';
    anchor.click();
  } catch (err) {
    console.error('[salesInvoiceService] Download failed:', err);
  }
}

export function printInvoice(invoice, brandName, currency, options = {}) {
  openInvoicePrint(invoice, brandName, currency, options);
}

export function shareInvoiceWhatsApp(invoice, currency, options = {}) {
  const resolved = optionsWithDefaults(options);
  const label = (value) => textFor(resolved, value);
  const fmt = (value) => formatMoney(value, currency, resolved.lang);
  const text = `*${label('SALES INVOICE')}: ${invoice.invoice_number}*\n`
    + `${label('Date')}: ${invoice.sale_date}\n`
    + `${label('Branch')}: ${invoice.branch}\n`
    + `${label('Shift')}: ${invoice.shift}\n\n`
    + `*${label('Sales Summary')}:*\n`
    + `- ${label('Cash Sales')}: ${fmt(invoice.cash_sales)}\n`
    + `- ${label('Network Sales')}: ${fmt(invoice.network_sales)}\n`
    + `- ${label('Credit Sales')}: ${fmt(invoice.credit_sales)}\n`
    + `*${label('Sales Total')}: ${fmt(invoice.sales_total)}*\n\n`
    + `*${label('Cash Reconciliation')}:*\n`
    + `- ${label('Opening Cash')}: ${fmt(invoice.opening_cash)}\n`
    + `- ${label('Closing Cash')}: ${fmt(invoice.closing_cash)}\n`
    + `- ${label('Diff')}: ${invoice.cash_difference >= 0 ? '+' : ''}${fmt(invoice.cash_difference)} (${label(invoice.cash_status || 'Balanced')})`;
  window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank', 'noopener');
}
