const en = {
  title: 'Cashier workspace', device: 'Select branch / POS', noDevice: 'No POS devices are configured for your branch.', control: 'POS Control',
  sell: 'Sell', orders: 'Held & receipts', stock: 'Branch stock', shift: 'Shift & drawer', live: 'Connected', offline: 'Connection unavailable — payment paused',
  scan: 'Scan barcode', scanHint: 'USB / Bluetooth scanner: focus here, scan and press Enter', search: 'Search name, barcode or SKU', add: 'Add', available: 'Available',
  empty: 'Scan or choose a product to start', noProducts: 'No stocked, sellable products match. Assign products and receive stock in Inventory.', inventory: 'Open inventory',
  invoice: 'Current invoice', units: 'units', subtotal: 'Subtotal after discount', tax: 'Tax', total: 'Total', discount: 'Discount', hold: 'Hold sale', cancel: 'Cancel sale',
  newSale: 'New sale', pay: 'Take payment', quantity: 'Quantity', remove: 'Remove item', price: 'Unit price', next: 'Next', previous: 'Previous',
  reserve: 'Scanning reserves available stock. Payment posts the sale and deducts stock once. Cancel releases it.',
  openShift: 'Open shift', cashier: 'Cashier name', opening: 'Opening cash', closeShift: 'Close shift', counted: 'Counted cash', expected: 'Expected cash', difference: 'Difference', notes: 'Notes / reason',
  closeHint: 'Closing this shift cancels all unpaid and held carts and disconnects the customer display. Count the actual drawer cash.',
  closed: 'Open a shift before scanning or taking payments.', blocked: 'This POS is locked or unavailable. Ask your manager to unlock it.',
  cash: 'Cash', mada: 'Mada', card: 'Card', apple_pay: 'Apple Pay', mixed: 'Split payment', cashReceived: 'Cash received', cardAmount: 'Mada amount', reference: 'Terminal reference (optional)',
  bankHint: 'Bank payments must succeed on the external card terminal first. This app records that payment; it does not charge the card.',
  confirmPayment: 'I confirm payment was received', confirmSale: 'Confirm payment & finish sale', change: 'Change to customer',
  pending: 'The last response was interrupted. Check / retry the same action before making another sale.', retry: 'Check / retry last action', refresh: 'Refresh',
  receipt: 'Sales receipt', refundReceipt: 'Refund receipt', print: 'Print / Save PDF', paid: 'Payment recorded', paper: 'Paper size', back: 'Back', save: 'Save',
  held: 'Held sales', resume: 'Resume', expires: 'Reserved until', history: 'Recent receipts', noOrders: 'No records yet', reprint: 'View receipt',
  refund: 'Full refund', refundHint: 'Owner / manager only. Confirm money was returned using the original payment methods. Returned goods enter quarantine for inspection.',
  confirmRefund: 'I confirm the money was returned', refunded: 'Refunded', discountHint: 'Owner / manager authorization and reason are recorded in the audit log.',
  display: 'Customer display', pair: 'Pair display', revoke: 'Disconnect display', copy: 'Copy link', copied: 'Copied', openDisplay: 'Open customer screen',
  pairHint: 'Open this private link on the customer-facing device. It shows this lane only and expires in 8 hours or when the shift closes. Pairing again replaces the old link.',
  waiting: 'Welcome! Your purchases appear here.', thankYou: 'Thank you for shopping with us', customerTitle: 'Your shopping', displayInvalid: 'Display link is invalid, expired or the shift is closed. Ask the cashier to pair this screen again.',
  stale: 'Reconnecting — waiting for a fresh total', updated: 'Updates with every scan', confirmCancel: 'Cancel this sale and release its reserved stock?',
};
const fa = {
  title: 'صفحهٔ کاشیر', device: 'انتخاب فرع / دستگاه POS', noDevice: 'برای فرع شما دستگاه POS تنظیم نشده است.', control: 'کنترول POS',
  sell: 'فروش', orders: 'سبدها و رسیدها', stock: 'موجودی فرع', shift: 'شیفت و صندوق', live: 'متصل', offline: 'اتصال قطع است — پرداخت متوقف شد',
  scan: 'اسکن بارکد', scanHint: 'اسکنر USB / بلوتوث: این خانه را انتخاب کنید، اسکن کرده Enter بزنید', search: 'جستجوی نام، بارکد یا SKU', add: 'اضافه', available: 'قابل‌فروش',
  empty: 'کالا را اسکن یا انتخاب کنید', noProducts: 'کالای موجود و قابل‌فروش پیدا نشد. در انونتوری کالا را به فرع اختصاص داده و موجودی دریافت کنید.', inventory: 'بازکردن انونتوری',
  invoice: 'انوايس جاری', units: 'واحد', subtotal: 'مبلغ پس از تخفیف، بدون مالیات', tax: 'مالیات', total: 'مجموع', discount: 'تخفیف', hold: 'نگهداری سبد', cancel: 'لغو فروش',
  newSale: 'فروش جدید', pay: 'دریافت پرداخت', quantity: 'تعداد / وزن', remove: 'حذف کالا', price: 'قیمت واحد', next: 'بعدی', previous: 'قبلی',
  reserve: 'اسکن، موجودی قابل‌فروش را رزرو می‌کند. پرداخت موفق فروش را ثبت و موجودی را یک‌بار کم می‌کند. لغو، رزرو را آزاد می‌سازد.',
  openShift: 'آغاز شیفت', cashier: 'نام کاشیر', opening: 'نقد آغاز شیفت', closeShift: 'بستن شیفت', counted: 'نقد شمارش‌شده', expected: 'نقد مورد انتظار', difference: 'تفاوت', notes: 'یادداشت / دلیل',
  closeHint: 'با بستن شیفت، سبدهای پرداخت‌نشده و نگهداری‌شده لغو و نمایشگر مشتری قطع می‌شود. نقد واقعی صندوق را بشمارید.',
  closed: 'پیش از اسکن و دریافت پرداخت، شیفت را آغاز کنید.', blocked: 'این POS قفل یا غیرفعال است. از مدیر بخواهید آن را باز کند.',
  cash: 'نقد', mada: 'مدى', card: 'کارت', apple_pay: 'اپل پی', mixed: 'پرداخت ترکیبی', cashReceived: 'نقد دریافت‌شده', cardAmount: 'مبلغ مدى', reference: 'شمارهٔ پرداخت بانکی (اختیاری)',
  bankHint: 'اول پرداخت روی دستگاه بانکی موفق شود. این اپ پرداخت را ثبت می‌کند؛ کارت مشتری را شارژ نمی‌کند.',
  confirmPayment: 'تأیید می‌کنم مبلغ دریافت شده است', confirmSale: 'تأیید پرداخت و ختم فروش', change: 'باقی پول مشتری',
  pending: 'پاسخ اقدام قبلی قطع شد. پیش از فروش دیگر، همان اقدام را بررسی / دوباره امتحان کنید.', retry: 'بررسی / تکرار همان اقدام', refresh: 'تازه‌سازی',
  receipt: 'رسید فروش', refundReceipt: 'رسید استرداد', print: 'چاپ / ذخیره PDF', paid: 'پرداخت ثبت شد', paper: 'اندازهٔ کاغذ', back: 'بازگشت', save: 'ذخیره',
  held: 'سبدهای نگهداری‌شده', resume: 'ادامهٔ فروش', expires: 'رزرو تا', history: 'رسیدهای اخیر', noOrders: 'هنوز رکوردی نیست', reprint: 'مشاهدهٔ رسید',
  refund: 'استرداد کامل', refundHint: 'فقط اونر / مدیر: بازگرداندن پول با روش پرداخت اصلی را تأیید کنید. کالای برگشتی تا بررسی، قرنطین می‌شود.',
  confirmRefund: 'تأیید می‌کنم پول به مشتری برگشت داده شد', refunded: 'مسترد شده', discountHint: 'اجازهٔ اونر / مدیر و دلیل تخفیف در سابقهٔ بررسی ثبت می‌شود.',
  display: 'نمایشگر مشتری', pair: 'وصل‌کردن نمایشگر', revoke: 'قطع نمایشگر', copy: 'کاپی لینک', copied: 'کاپی شد', openDisplay: 'بازکردن صفحهٔ مشتری',
  pairHint: 'این لینک خصوصی را در دستگاه روبه‌روی مشتری باز کنید. فقط سبد همین کاشیر را نشان می‌دهد؛ پس از ۸ ساعت یا بستن شیفت منقضی می‌شود. اتصال جدید لینک قبلی را باطل می‌کند.',
  waiting: 'خوش آمدید! خریدهای شما اینجا ظاهر می‌شود.', thankYou: 'از خرید شما تشکر', customerTitle: 'خرید شما', displayInvalid: 'لینک نمایشگر نامعتبر، منقضی یا شیفت بسته است. از کاشیر بخواهید دوباره وصل کند.',
  stale: 'اتصال دوباره — منتظر مجموع تازه', updated: 'با هر اسکن آپدیت می‌شود', confirmCancel: 'فروش لغو و موجودی رزروشده آزاد شود؟',
};
const ar = {
  title: 'مساحة الكاشير', device: 'اختيار الفرع / جهاز POS', noDevice: 'لا توجد أجهزة POS مهيأة لفرعك.', control: 'التحكم في POS',
  sell: 'البيع', orders: 'السلال والإيصالات', stock: 'مخزون الفرع', shift: 'الوردية والصندوق', live: 'متصل', offline: 'الاتصال غير متاح — الدفع متوقف',
  scan: 'مسح الباركود', scanHint: 'ماسح USB / Bluetooth: حدد هذا الحقل ثم امسح واضغط Enter', search: 'بحث بالاسم أو الباركود أو SKU', add: 'إضافة', available: 'متاح للبيع',
  empty: 'امسح منتجاً أو اختره للبدء', noProducts: 'لا توجد منتجات متاحة مطابقة. خصص المنتجات للفرع واستلم المخزون أولاً.', inventory: 'فتح المخزون',
  invoice: 'الفاتورة الحالية', units: 'وحدات', subtotal: 'بعد الخصم وقبل الضريبة', tax: 'الضريبة', total: 'الإجمالي', discount: 'الخصم', hold: 'تعليق البيع', cancel: 'إلغاء البيع',
  newSale: 'بيع جديد', pay: 'استلام الدفع', quantity: 'الكمية / الوزن', remove: 'إزالة المنتج', price: 'سعر الوحدة', next: 'التالي', previous: 'السابق',
  reserve: 'المسح يحجز المخزون المتاح. الدفع الناجح يسجل البيع ويخصم المخزون مرة واحدة. الإلغاء يحرر الحجز.',
  openShift: 'فتح الوردية', cashier: 'اسم الكاشير', opening: 'النقد الافتتاحي', closeShift: 'إغلاق الوردية', counted: 'النقد المعدود', expected: 'النقد المتوقع', difference: 'الفرق', notes: 'ملاحظات / السبب',
  closeHint: 'إغلاق الوردية يلغي السلال غير المدفوعة والمعلقة ويفصل شاشة العميل. عد النقد الفعلي في الصندوق.',
  closed: 'افتح وردية قبل المسح أو استلام الدفع.', blocked: 'هذا الجهاز مقفل أو غير متاح. اطلب من المدير فتحه.',
  cash: 'نقد', mada: 'مدى', card: 'بطاقة', apple_pay: 'Apple Pay', mixed: 'دفع مختلط', cashReceived: 'النقد المستلم', cardAmount: 'مبلغ مدى', reference: 'مرجع الجهاز البنكي (اختياري)',
  bankHint: 'يجب نجاح الدفع على الجهاز البنكي أولاً. يسجل التطبيق الدفع ولا يخصم من بطاقة العميل مباشرة.',
  confirmPayment: 'أؤكد استلام المبلغ', confirmSale: 'تأكيد الدفع وإنهاء البيع', change: 'الباقي للعميل',
  pending: 'انقطع الرد السابق. تحقق / أعد نفس العملية قبل إجراء بيع آخر.', retry: 'تحقق / أعد نفس العملية', refresh: 'تحديث',
  receipt: 'إيصال بيع', refundReceipt: 'إيصال استرداد', print: 'طباعة / حفظ PDF', paid: 'تم تسجيل الدفع', paper: 'حجم الورق', back: 'رجوع', save: 'حفظ',
  held: 'المبيعات المعلقة', resume: 'استئناف', expires: 'محجوز حتى', history: 'الإيصالات الأخيرة', noOrders: 'لا توجد سجلات بعد', reprint: 'عرض الإيصال',
  refund: 'استرداد كامل', refundHint: 'للمالك / المدير فقط. أكد رد المال بطرق الدفع الأصلية. توضع المرتجعات في الحجر حتى فحصها.',
  confirmRefund: 'أؤكد إعادة المال للعميل', refunded: 'تم الاسترداد', discountHint: 'يسجل تفويض المالك / المدير وسبب الخصم في سجل التدقيق.',
  display: 'شاشة العميل', pair: 'ربط الشاشة', revoke: 'فصل الشاشة', copy: 'نسخ الرابط', copied: 'تم النسخ', openDisplay: 'فتح شاشة العميل',
  pairHint: 'افتح هذا الرابط الخاص على جهاز العميل. يعرض سلة هذا الكاشير فقط وينتهي بعد 8 ساعات أو إغلاق الوردية. الربط مجدداً يلغي الرابط السابق.',
  waiting: 'مرحباً! ستظهر مشترياتك هنا.', thankYou: 'شكراً لتسوقكم معنا', customerTitle: 'مشترياتك', displayInvalid: 'الرابط غير صالح أو منتهي أو الوردية مغلقة. اطلب من الكاشير ربط الشاشة مجدداً.',
  stale: 'إعادة الاتصال — بانتظار إجمالي محدث', updated: 'تحديث مع كل مسح', confirmCancel: 'إلغاء البيع وتحرير المخزون المحجوز؟',
};
export const cashierCopy = lang => ({ ...en, ...(lang === 'fa' ? fa : lang === 'ar' ? ar : {}) });
