import RestaurantCategorySelect from '@/components/restaurant-pos/RestaurantCategorySelect';
import RestaurantFoodPicker from '@/components/restaurant-pos/RestaurantFoodPicker';
import {SERVING_KEYS,servingCopy} from '@/lib/restaurantServingOptions';
import { useEffect, useState } from 'react';
import { Link, useLocation, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ChefHat, Monitor, Plus, Printer, RefreshCw, Search, Settings2, ShoppingBag, X } from 'lucide-react';
import { useTenant } from '@/lib/TenantContext';
import { useAuth } from '@/lib/AuthContext';
import { useRole } from '@/lib/RoleContext';
import { useLanguage } from '@/lib/LanguageContext';
import { supabase } from '@/api/supabaseClient';
import { useRetailCashier } from '@/hooks/useRetailCashier';
import { subscribeCashierBroadcast } from '@/lib/cashierBroadcast';
import { money, paymentBreakdown, printCashierReceipt } from '@/lib/retailCashier';
import { isRestaurantPOSPortal, restaurantRpc, restaurantProductName as nameOf, restaurantBusinessDate, kitchenNextState, parseRecipeRows } from '@/lib/restaurantPOS';
import { restaurantProductCopy } from '@/lib/restaurantProducts';
import { restaurantCopy } from '@/components/restaurant-pos/copy';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

export const panel = 'rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950 sm:p-5';
export const input = 'h-12 w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 text-base text-slate-900 dark:border-slate-700 dark:bg-slate-900 dark:text-white';
export const button = 'inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold hover:bg-blue-50 disabled:opacity-40 dark:border-slate-700';
export const primary = `${button} border-blue-600 bg-blue-600 text-white hover:bg-blue-700`;
const Field = ({label,children}) => <label className="grid min-w-0 gap-2 text-sm font-semibold">{label}{children}</label>;
const Status = ({fresh,c}) => <span role="status" className={`rounded-full px-3 py-2 text-xs font-bold ${fresh?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{fresh?c.live:c.offline}</span>;

export function useRestaurantWorkspace(tenant,branch,date,active=true) {
 const q=useQuery({queryKey:['restaurant-pos',tenant,branch,date],enabled:active&&Boolean(tenant),queryFn:()=>restaurantRpc('pos_workspace',{p_restaurant_id:tenant,p_branch_id:branch||null,p_date:date}),refetchInterval:active?5000:false,retry:1});
 useEffect(()=>{if(!tenant||!active)return;let timer;const off=subscribeCashierBroadcast(supabase,`restaurant-pos:${tenant}`,s=>{if(['changed','SUBSCRIBED'].includes(s)){clearTimeout(timer);timer=setTimeout(()=>void q.refetch(),200);}});return()=>{off();clearTimeout(timer);};},[tenant,active,q.refetch]);
 return q;
}

export function Setup({tenant,branch,c,close,refresh,initial=null,menuOnly=false}) {
 const {lang}=useLanguage();const labels=restaurantProductCopy(lang);const serving=servingCopy(lang);
 const [count,setCount]=useState(10);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [form,setForm]=useState(()=>({id:crypto.randomUUID(),product_id:'',name:'',name_ar:'',name_fa:'',image_url:'',price:'',tax_rate:'0',category_id:'',category:'Food',station:'Kitchen',stock_mode:'recipe',active:true,option_group:'',option_key:'',...initial,confirm_untracked:false}));
 const [recipe,setRecipe]=useState(()=>initial?.recipe?.length?initial.recipe:[{inventory_id:'',quantity:''}]);
 const data=useQuery({queryKey:['restaurant-pos-setup',tenant,branch],queryFn:()=>restaurantRpc('pos_catalog',{p_restaurant_id:tenant,p_branch_id:branch,p_search:''}),enabled:Boolean(tenant&&branch)});
 const set=(key,value)=>setForm(s=>({...s,[key]:value}));
 const submit=async(command,payload)=>{setBusy(true);setError('');try{await restaurantRpc('pos_setup',{p_restaurant_id:tenant,p_branch_id:branch,p_command:command,p_payload:payload});await refresh();if(command==='menu')close();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)close();}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{menuOnly?labels.setup:c.setup}</DialogTitle><DialogDescription>{labels.recipeHint}</DialogDescription></DialogHeader>
  {!menuOnly&&<div className="flex items-end gap-2"><Field label={c.count}><input className={input} type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/></Field><button className={button} disabled={busy} onClick={()=>void submit('devices',{count:Number(count)})}>{c.createDevices}</button></div>}
  <form className="grid gap-4 border-t pt-4" onSubmit={e=>{e.preventDefault();try{void submit('menu',{...form,price:Number(form.price),tax_rate:Number(form.tax_rate),recipe:parseRecipeRows(recipe)});}catch(e){setError(e.message);}}}>
   <div className="grid gap-3 sm:grid-cols-2">{[['name',c.name],['name_ar',c.arabic],['name_fa',labels.persian],['price',c.price],['tax_rate',c.taxRate],['station',c.station]].map(([k,label])=><Field key={k} label={label}><input className={input} required={!['name_ar','name_fa'].includes(k)} type={['price','tax_rate'].includes(k)?'number':'text'} step="0.01" min={k==='price'?'0.01':'0'} max={k==='tax_rate'?'100':undefined} value={form[k]??''} onChange={e=>set(k,e.target.value)}/></Field>)}</div>
   <RestaurantCategorySelect categories={data.data?.categories} value={form.category_id} onChange={v=>set('category_id',v)} lang={lang} refresh={data.refetch} disabled={busy}/>
   <div className="grid gap-3 rounded-xl border border-blue-100 bg-blue-50/40 p-3 sm:grid-cols-2">
    <Field label={serving.group}><input className={input} maxLength={80} value={form.option_group||''} onChange={e=>{set('option_group',e.target.value);if(!e.target.value.trim())set('option_key','');}}/></Field>
    <Field label={serving.kind}><select className={input} required={Boolean(form.option_group?.trim())} disabled={!form.option_group?.trim()} value={form.option_key||''} onChange={e=>set('option_key',e.target.value)}><option value="">{serving.standalone}</option>{SERVING_KEYS.map(k=><option key={k} value={k}>{serving[k]}</option>)}</select></Field>
    <p className="text-xs leading-5 text-slate-500 sm:col-span-2">{serving.groupHint}</p>
   </div>
   <Field label={labels.image}><input className={input} type="url" pattern="https://.*" value={form.image_url||''} onChange={e=>set('image_url',e.target.value)}/></Field>
   <label className="flex items-center gap-3"><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/>{labels.active}</label>
   <Field label={c.stockMode}><select className={input} value={form.stock_mode} onChange={e=>set('stock_mode',e.target.value)}><option value="recipe">{c.recipe}</option><option value="untracked">{c.untracked}</option></select></Field>
   {form.stock_mode==='recipe'?<div className="space-y-3">{recipe.map((r,i)=><div key={i} className="grid grid-cols-[minmax(0,1fr)_100px_48px] items-end gap-2"><Field label={c.ingredient}><select className={input} required value={r.inventory_id} onChange={e=>setRecipe(rows=>rows.map((v,j)=>j===i?{...v,inventory_id:e.target.value}:v))}><option value="">—</option>{data.data?.inventory.map(s=><option key={s.id} value={s.id}>{s.product_name} · {s.quantity} {s.unit}</option>)}</select></Field><Field label={c.quantity}><input className={input} required type="number" min="0.000001" step="any" value={r.quantity} onChange={e=>setRecipe(rows=>rows.map((v,j)=>j===i?{...v,quantity:e.target.value}:v))}/></Field><button type="button" className={button} aria-label={c.remove} onClick={()=>setRecipe(rows=>rows.filter((_,j)=>j!==i))}><X size={18}/></button></div>)}<button type="button" className={button} onClick={()=>setRecipe(rows=>[...rows,{inventory_id:'',quantity:''}])}><Plus size={18}/>{c.addIngredient}</button></div>:<label className="flex gap-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><input type="checkbox" required checked={form.confirm_untracked} onChange={e=>set('confirm_untracked',e.target.checked)}/>{c.untrackedConfirm}</label>}
   {(error||data.error)&&<p role="alert" className="text-red-600">{error||data.error.message}</p>}<button className={primary} disabled={busy||data.isLoading||data.isError}>{labels.save}</button>
  </form>
 </DialogContent></Dialog>;
}

function ActionDialog({kind,api,c,close,currency,onResult}) {
 const cart=api.snapshot?.cart;
 const [v,setV]=useState({cashier_name:'',opening_cash:'0',counted_cash:'',reason:'',notes:cart?.notes||'',order_type:cart?.order_type||'takeaway',table_label:cart?.table_label||'',mode:'cash',cash:String(cart?.net_total||0),card:'0',confirmed:false});
 const [error,setError]=useState('');const set=(k,value)=>setV(s=>({...s,[k]:value}));const p=paymentBreakdown(cart?.net_total,v.mode,v.cash,v.card);
 const text=(key,label,type='text')=><Field label={label}><input className={input} type={type} min="0" step="0.01" value={v[key]} required={!['table_label','notes'].includes(key)} onChange={e=>set(key,e.target.value)}/></Field>;
 const titles={payment:c.pay,open:c.openShift,close:c.closeShift,cancel:c.cancel,details:c.details};
 const submit=async e=>{e.preventDefault();setError('');try{const payload=kind==='payment'?{payment_confirmed:v.confirmed,payments:p.payments}:kind==='open'?{cashier_name:v.cashier_name,opening_cash:Number(v.opening_cash)}:kind==='close'?{counted_cash:Number(v.counted_cash),notes:v.notes}:kind==='cancel'?{reason:v.reason}:{order_type:v.order_type,table_label:v.table_label,notes:v.notes};const r=await api.command({payment:'checkout',open:'open_shift',close:'close_shift',cancel:'cancel',details:'details'}[kind],payload);onResult(r);close();}catch(e){setError(e.message);}};
 return <Dialog open onOpenChange={v=>{if(!v&&!api.busy)close();}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{titles[kind]}</DialogTitle><DialogDescription>{kind==='close'?c.closeHint:kind==='cancel'?c.cancelHint:c.stockHint}</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4">
  {kind==='open'&&<>{text('cashier_name',c.cashier)}{text('opening_cash',c.opening,'number')}</>}
  {kind==='close'&&<><strong>{c.expected}: {money(api.snapshot?.expected_cash,currency)}</strong>{text('counted_cash',c.counted,'number')}{text('notes',c.notes)}</>}
  {kind==='cancel'&&text('reason',c.reason)}
  {kind==='details'&&<><Field label={c.details}><select className={input} value={v.order_type} onChange={e=>set('order_type',e.target.value)}>{['dine_in','takeaway','delivery'].map(t=><option key={t} value={t}>{c[t]}</option>)}</select></Field>{text('table_label',c.table)}{text('notes',c.notes)}</>}
  {kind==='payment'&&<><strong className="text-3xl" dir="ltr">{money(cart?.net_total,currency)}</strong><div className="grid grid-cols-3 gap-2">{['cash','card','mixed'].map(m=><button className={v.mode===m?primary:button} type="button" key={m} onClick={()=>set('mode',m)}>{c[m]}</button>)}</div>{v.mode!=='card'&&text('cash',c.tendered,'number')}{v.mode==='mixed'&&text('card',c.cardAmount,'number')}<p>{c.change}: {money(p.change,currency)}</p><label className="flex items-start gap-3 text-sm"><input type="checkbox" required checked={v.confirmed} onChange={e=>set('confirmed',e.target.checked)}/>{c.confirmed}</label></>}
  {error&&<p className="text-red-600" role="alert">{error}</p>}<button className={primary} disabled={Boolean(api.busy)||(kind==='payment'&&!p.valid)}>{titles[kind]}</button>
 </form></DialogContent></Dialog>;
}

function Station({device,scope,active,c,lang,menu,page,canSell}) {
 const api=useRetailCashier(device.id,scope,active,restaurantRpc);const s=api.snapshot;const cart=s?.cart;const currency=s?.business?.currency||'SAR';
 const [modal,setModal]=useState(null);const [error,setError]=useState('');const [search,setSearch]=useState('');const [category,setCategory]=useState('');const [link,setLink]=useState('');const [copied,setCopied]=useState(false);const [receipt,setReceipt]=useState(null);
 const fresh=api.connected;const editable=Boolean(canSell&&s?.shift&&cart&&!cart.submitted_at&&!s.device.locked&&!api.pending&&!api.busy);
 const perform=async fn=>{try{setError('');const r=await fn();if(r?.receipt)setReceipt(r.receipt);return r;}catch(e){setError(e.message);return null;}};
 const qty=(m,delta)=>perform(()=>api.command('quantity',current=>({menu_id:m.id||m.menu_id,quantity:Number(current?.lines?.find(l=>l.menu_id===(m.id||m.menu_id))?.quantity||0)+delta})));
 return <div className="space-y-4">
  <div className={`${panel} flex flex-wrap items-center justify-between gap-3`}><div><strong>{s?.business?.branch_name} · {device.code}</strong><p className="text-sm text-slate-500">{s?.shift?.cashier_name}</p></div><div className="flex flex-wrap gap-2"><Status fresh={fresh} c={c}/><button className={button} aria-label={c.refresh} onClick={()=>void api.refresh()}><RefreshCw size={18}/></button>{canSell&&s&&!s.shift&&<button className={primary} disabled={Boolean(api.pending)||s.device.locked} onClick={()=>setModal('open')}>{c.openShift}</button>}{canSell&&s?.shift&&<><button className={button} disabled={Boolean(api.busy)||Boolean(api.pending)} onClick={()=>setModal('close')}>{c.closeShift}</button>{!cart&&<button className={primary} disabled={Boolean(api.busy)||Boolean(api.pending)||s.device.locked} onClick={()=>void perform(()=>api.command('new_sale'))}><Plus size={18}/>{c.newSale}</button>}</>}</div></div>
  {api.pending&&<div className="rounded-xl bg-amber-50 p-4 text-amber-950" role="alert">{c.pending}<button className={button} onClick={()=>void perform(api.retry)}>{c.retry}</button></div>}
  {(error||api.error)&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error||api.error}</p>}
  {page==='display'?<section className={`${panel} grid gap-4`}><Monitor className="text-blue-600" size={40}/><h2 className="text-xl font-black">{c.display}</h2><p>{c.displayHint}</p><div className="flex flex-wrap gap-3"><button className={primary} disabled={!s?.shift||Boolean(api.busy)||Boolean(api.pending)||!canSell} onClick={()=>void perform(async()=>{const r=await api.command('pair_display');if(r.token){setLink(`${window.location.origin}/restaurant/customer-display#${r.token}`);setCopied(false);}})}>{c.pairing}</button><button className={button} disabled={!s?.shift||Boolean(api.busy)||!canSell} onClick={()=>void perform(async()=>{await api.command('unpair_display');setLink('');})}>{c.disconnect}</button></div>{link&&<><input className={input} aria-label={c.display} value={link} readOnly/><div className="flex flex-wrap gap-3"><a className={primary} href={link} target="_blank" rel="noopener noreferrer">{c.openDisplay}</a><button className={button} onClick={()=>void perform(async()=>{await navigator.clipboard.writeText(link);setCopied(true);})}>{copied?c.copied:c.copy}</button></div></>}</section>:<>
   <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_390px]">
    <section className={panel}><div className="relative"><Search className="absolute start-3 top-3.5 text-slate-400" size={20}/><input className={`${input} ps-10`} placeholder={c.search} aria-label={c.search} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="my-4 flex flex-wrap gap-2"><button className={category?button:primary} onClick={()=>setCategory('')}>{c.food}</button>{[...new Map(menu.filter(m=>m.active).map(m=>[m.category_id||m.category,m])).entries()].map(([id,m])=><button key={id} className={category===id?primary:button} onClick={()=>setCategory(id)}>{m['category_'+lang]||m.category}</button>)}</div>
     <RestaurantFoodPicker menu={menu} search={search} category={category} lang={lang} currency={currency} editable={editable} onChoose={(m,quantity)=>qty(m,quantity)} emptyLabel={c.empty}/>
    </section>
    <aside className={`${panel} space-y-4 xl:sticky xl:top-4`}><div className="flex justify-between gap-2"><h2 className="text-xl font-black">{c.current} {cart?`#${cart.number}`:''}</h2>{cart&&<button className={button} disabled={!editable||Boolean(api.busy)} onClick={()=>setModal('details')}>{c.details}</button>}</div>
     {cart?<><p className="text-sm text-slate-500">{c[cart.order_type]} · {cart.table_label} · {c[cart.kitchen_status]}</p>{cart.notes&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-950">{cart.notes}</p>}<div className="max-h-[45dvh] space-y-3 overflow-y-auto">{cart.lines.map(l=><div key={l.menu_id} className="rounded-xl border border-slate-100 p-3"><strong className="block text-sm">{nameOf(l,lang)}</strong><div className="mt-3 flex items-center justify-between gap-2"><div className="flex items-center gap-3"><button className={button} aria-label={`${c.remove} ${nameOf(l,lang)}`} disabled={!editable} onClick={()=>qty(l,-1)}>−</button><span>{l.quantity}</span><button className={button} aria-label={`${c.quantity} ${nameOf(l,lang)}`} disabled={!editable} onClick={()=>qty(l,1)}>+</button></div><strong dir="ltr">{money(l.line_total,currency)}</strong></div></div>)}</div>
      <div className="flex justify-between text-sm text-slate-500"><span>{c.tax}</span><span>{money(cart.tax_total,currency)}</span></div><div className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-blue-50 p-4 text-blue-700 dark:bg-blue-950"><strong>{c.total}</strong><strong className="text-3xl" dir="ltr">{money(cart.net_total,currency)}</strong></div>
      {canSell&&<><button className={`${primary} w-full`} disabled={!cart.lines.length||Boolean(api.busy)||Boolean(api.pending)||s?.device.locked} onClick={()=>setModal('payment')}>{c.pay}</button><div className="grid grid-cols-2 gap-2"><button className={button} disabled={!editable||!cart.lines.length||Boolean(api.busy)} onClick={()=>void perform(()=>api.command('send_kitchen'))}>{c.send}</button><button className={button} disabled={Boolean(api.busy)||Boolean(api.pending)} onClick={()=>void perform(()=>api.command('hold'))}>{c.hold}</button><button className={`${button} text-red-600`} disabled={Boolean(api.busy)||Boolean(api.pending)} onClick={()=>setModal('cancel')}>{c.cancel}</button></div></>}
      <p className="text-xs leading-relaxed text-slate-500">{cart.submitted_at?c.sentHint:c.stockHint}</p></>:<p className="py-10 text-center text-slate-500">{c.selectDevice}</p>}
    </aside>
   </div>
   <section className={`${panel} space-y-3`}><h2 className="font-black">{c.hold}</h2>{s?.held?.map(o=><div key={o.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><span>#{o.number} · {c[o.order_type]} · {money(o.net_total,currency)}</span><button className={button} disabled={!canSell||Boolean(cart)||Boolean(api.busy)||Boolean(api.pending)} onClick={()=>void perform(()=>api.command('resume',{cart_id:o.id,revision:o.revision}))}>{c.resume}</button></div>)}</section>
   <section className={`${panel} space-y-3`}><h2 className="font-black">{c.receipts}</h2>{(receipt?[receipt,...(s?.receipts||[]).filter(r=>r.id!==receipt.id)]:s?.receipts||[]).map(r=><div key={r.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><span>{r.receipt_number} · {money(r.net_total,currency)}</span><button className={button} onClick={()=>void perform(()=>printCashierReceipt(r,lang,'80mm'))}><Printer size={18}/>{c.print}</button></div>)}<p className="text-xs text-slate-500">{c.noHardware}</p></section>
  </>}
  {modal&&<ActionDialog key={modal} kind={modal} api={api} c={c} currency={currency} close={()=>setModal(null)} onResult={r=>{if(r.receipt)setReceipt(r.receipt);}}/>}
 </div>;
}

function Kitchen({orders,c,lang,refresh,canKitchen}) {
 const [station,setStation]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const advance=async o=>{setBusy(o.id);setError('');try{await restaurantRpc('pos_kitchen',{p_order_id:o.id,p_revision:o.revision,p_status:kitchenNextState(o.kitchen_status)});await refresh();}catch(e){setError(e.message);}finally{setBusy('');}};
 const filtered=orders.filter(o=>!station||o.lines.some(l=>l.station===station));
 return <section className="space-y-4"><div className="flex flex-wrap gap-2"><button className={station?button:primary} onClick={()=>setStation('')}>{c.all}</button>{[...new Set(orders.flatMap(o=>o.lines.map(l=>l.station)))].map(s=><button className={station===s?primary:button} key={s} onClick={()=>setStation(s)}>{s}</button>)}</div>{error&&<p role="alert" className="text-red-600">{error}</p>}<div className="grid gap-4 lg:grid-cols-3">{['queued','preparing','ready'].map(stage=><div className={panel} key={stage}><h2 className={`mb-4 rounded-xl p-3 text-lg font-black ${stage==='ready'?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-900'}`}>{c[stage]} · {filtered.filter(o=>o.kitchen_status===stage).length}</h2>{filtered.filter(o=>o.kitchen_status===stage).map(o=><article key={o.id} className="mb-3 space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-2"><strong className="text-xl">#{o.number}</strong><span className="text-sm">{c[o.order_type]} {o.table_label}</span></div><p className="text-xs text-slate-500">{c.started}: {new Date(o.submitted_at).toLocaleTimeString()}</p>{o.lines.map(l=><p key={l.menu_id} className="text-sm"><strong>{l.quantity} × </strong>{nameOf(l,lang)}</p>)}{o.notes&&<p className="rounded-lg bg-amber-50 p-2 text-sm text-amber-900">{o.notes}</p>}<span className={`inline-block rounded-full px-3 py-1 text-xs font-bold ${o.status==='paid'?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-600'}`}>{o.status==='paid'?c.paid:c.unpaid}</span><button className={`${primary} w-full`} disabled={!canKitchen||Boolean(busy)||(stage==='ready'&&o.status!=='paid')} onClick={()=>void advance(o)}>{c[kitchenNextState(stage)]}</button></article>)}</div>)}</div>{!orders.length&&<p className={`${panel} text-center`}>{c.noOrders}</p>}</section>;
}

export default function RestaurantPOS() {
 const {activeRestaurant,branches=[]}=useTenant();const {user}=useAuth();const {lang}=useLanguage();const {can,role}=useRole();const c=restaurantCopy(lang);const [params,setParams]=useSearchParams();const location=useLocation();
 const page=['sell','kitchen','display','control'].includes(params.get('page'))?params.get('page'):'sell';const [branchChoice,setBranchChoice]=useState('');const [date,setDate]=useState(restaurantBusinessDate);const [setup,setSetup]=useState(false);const [error,setError]=useState('');
 const active=location.pathname==='/restaurant/pos';const tenant=activeRestaurant?.id;const portal=isRestaurantPOSPortal(activeRestaurant);const branch=branches.some(b=>b.id===branchChoice)?branchChoice:branches[0]?.id||null;
 const queryBranch=page==='control'&&branchChoice==='all'&&role==='owner'?null:branch;const q=useRestaurantWorkspace(portal?tenant:null,queryBranch,date,active);const [now,setNow]=useState(Date.now());
 useEffect(()=>{if(!active)return;const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[active]);
 const fresh=Boolean(q.dataUpdatedAt&&now-q.dataUpdatedAt<12000&&!q.isError&&navigator.onLine!==false);const data=q.data;const devices=data?.devices||[];const device=devices.find(d=>d.id===params.get('device'))||devices.find(d=>d.branch_id===branch);const changePage=value=>setParams(prev=>{const p=new URLSearchParams(prev);p.set('page',value);return p;});
 if(!portal)return <p role="alert" className={panel}>{c.unavailable}</p>;
 return <main dir={lang==='en'?'ltr':'rtl'} className="mx-auto max-w-[1720px] space-y-4 pb-28 text-slate-950 dark:text-white">
  <header className={`${panel} space-y-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-2xl bg-blue-600 p-3 text-white"><ChefHat size={28}/></span><div><h1 className="text-2xl font-black">{c.title}</h1><p className="text-sm text-slate-500">{c.subtitle}</p></div></div><div className="flex gap-2"><Status fresh={fresh} c={c}/>{data?.can_manage&&branch&&<button className={button} onClick={()=>setSetup(true)}><Settings2 size={18}/>{c.setup}</button>}</div></div>
   <nav aria-label={c.title} className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[['sell',ShoppingBag],['kitchen',ChefHat],['display',Monitor],['control',RefreshCw]].map(([p,Icon])=><button key={p} className={page===p?primary:button} aria-pressed={page===p} onClick={()=>changePage(p)}><Icon size={18}/>{c[p]}</button>)}</nav>
   <div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Field label={c.branch}><select className={input} value={queryBranch||'all'} onChange={e=>{setBranchChoice(e.target.value);setParams(prev=>{const p=new URLSearchParams(prev);p.delete('device');return p;});}}>{page==='control'&&role==='owner'&&<option value="all">{c.all}</option>}{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>{['sell','display'].includes(page)&&<Field label={c.device}><select className={input} value={device?.id||''} onChange={e=>setParams(prev=>{const p=new URLSearchParams(prev);p.set('device',e.target.value);return p;})}><option value="" disabled>—</option>{devices.filter(d=>d.branch_id===branch).map(d=><option key={d.id} value={d.id}>{d.code}</option>)}</select></Field>}{page==='control'&&<Field label={c.date}><input className={input} type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field>}</div>
  </header>
  {(error||q.error)&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error||q.error.message}</p>}
  {q.isLoading&&<p className={panel}>…</p>}
  {['sell','display'].includes(page)&&(device?<Station key={`${tenant}:${user?.id}:${device.id}`} device={device} scope={`${tenant}:${user?.id}`} active={active} c={c} lang={lang} menu={data?.menu||[]} page={page} canSell={can.uploadSales}/>:<p className={panel}>{c.empty}</p>)}
  {page==='kitchen'&&<Kitchen orders={data?.orders||[]} c={c} lang={lang} refresh={q.refetch} canKitchen={can.viewOrders&&fresh}/>}
  {page==='control'&&data?.can_manage&&<><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[['paid_sales',c.paidSales],['unpaid_orders',c.unpaidOrders],['purchases',c.purchases],['expenses',c.expenses]].map(([key,label])=><section key={key} className={panel}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 break-words text-2xl font-black text-blue-700" dir="ltr">{data[key]===null?'—':money(data[key],activeRestaurant.currency||'SAR')}</p></section>)}</div><div className="flex flex-wrap gap-3">{can.viewExpenses&&<Link className={primary} to="/expenses">{c.expense}</Link>}<Link className={button} to="/owner-command-center">{c.reports}</Link></div><section className={`${panel} space-y-3`}><h2 className="font-black">{c.device}</h2>{devices.map(d=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3" key={d.id}><span>{branches.find(b=>b.id===d.branch_id)?.name} · {d.code} · {d.locked?c.lock:new Date(d.last_seen_at||0).getTime()>now-90000?c.live:c.offline}</span><button className={button} onClick={async()=>{try{setError('');await restaurantRpc('pos_setup',{p_restaurant_id:tenant,p_branch_id:d.branch_id,p_command:'lock',p_payload:{device_id:d.id,locked:!d.locked}});void q.refetch();}catch(e){setError(e.message);}}}>{d.locked?c.unlock:c.lock}</button></div>)}</section><section className={`${panel} space-y-3`}><h2 className="font-black">{c.audit}</h2>{data.events?.map((e,i)=><div className="flex flex-wrap justify-between gap-2 border-b py-3 text-sm" key={`${e.occurred_at}:${i}`}><span>{e.code} · {e.action}</span><time>{new Date(e.occurred_at).toLocaleString()}</time></div>)}</section></>}
  {setup&&branch&&<Setup key={`${tenant}:${branch}`} tenant={tenant} branch={branch} c={c} close={()=>setSetup(false)} refresh={q.refetch}/>}
 </main>;
}
