import React, { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowDownToLine, ArrowLeftRight, ArrowUpRight, Barcode, Boxes, Building2, CalendarClock, ClipboardCheck, Download, FileSpreadsheet, Plus, ScanLine, Search, ShieldCheck, TriangleAlert, Wallet, Warehouse } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/api/supabaseClient';
import { useRole } from '@/lib/RoleContext';
import { useLanguage } from '@/lib/LanguageContext';
import { useRetailInventory, useInventoryList } from '@/hooks/useRetailInventory';
import { csvCell, inventoryRPC, productName } from '@/lib/retailInventory';
import { Button } from '@/components/ui/button';
import ProductBarcodeDialog from '@/components/products/ProductBarcodeDialog';
import { barcodeText } from '@/lib/barcodeCopy';
import BarcodeScanDialog from '@/components/shared/BarcodeScanDialog';
import { useInventoryCopy } from '@/components/retail-inventory/inventoryCopy';
import { InventoryWorkspace, Panel, Metric, Empty, ErrorNotice, Status, Pagination, ProductIdentity, Field, fieldClass } from '@/components/retail-inventory/InventoryUI';
import { ProductPicker } from '@/components/retail-inventory/ProductPicker';
import InventoryDocumentForm from '@/components/retail-inventory/InventoryDocumentForm';
import InventoryDocumentDetail from '@/components/retail-inventory/InventoryDocumentDetail';
import { InventorySettingsDialog, InventoryStockDetail } from '@/components/retail-inventory/InventoryStockDetail';
const ProductBulkImportDialog = lazy(() => import('@/components/products/ProductBulkImportDialog'));
const QUICK = [['receipt', ArrowDownToLine], ['transfer', ArrowLeftRight], ['count', ClipboardCheck], ['scan', ScanLine], ['barcode', Barcode]];

function QuickActions({ edit, purchase, onAction }) {
  const c = useInventoryCopy(); const { lang } = useLanguage(); return <div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{QUICK.filter(([key]) => key === 'scan' || (edit && (key !== 'receipt' || purchase))).map(([key, Icon]) => <Button key={key} variant={key === 'receipt' ? 'default' : 'outline'} className="min-h-14 gap-2 rounded-2xl text-xs sm:text-sm" onClick={() => onAction({ kind: key })}><Icon className="h-5 w-5" />{key === 'barcode' ? barcodeText(lang).create : c[key]}</Button>)}</div>;
}
function MovementList({ rows }) {
  const c = useInventoryCopy(); const { formatNumber, formatDate, lang } = useLanguage();
  return rows.length ? <div className="divide-y">{rows.map((m) => <div key={m.id} className="flex items-start justify-between gap-3 py-3"><div className="flex min-w-0 gap-3"><span className={`mt-1 rounded-lg p-2 ${Number(m.quantity) >= 0 ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-blue-600'}`}><Activity className="h-4 w-4" /></span><div><p className="text-sm font-bold">{productName(m, lang)}</p><p className="mt-1 text-[11px] text-muted-foreground">{c[m.kind] || m.kind} · {m.branch_name} · {m.warehouse_name}</p><p className="text-[10px] text-muted-foreground">{formatDate(m.created_at)}</p></div></div><strong className="whitespace-nowrap text-sm">{Number(m.quantity) > 0 ? '+' : ''}{formatNumber(m.quantity)} {m.unit}</strong></div>)}</div> : <Empty />;
}
function Overview({ ctx, onAction }) {
  const c = useInventoryCopy(); const { can } = useRole(); const { formatMoney, formatNumber } = useLanguage(); const navigate = useNavigate(); const s = ctx.snapshot.summary;
  return <><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label={c.stockValue} value={formatMoney(s.stock_value || 0)} icon={Wallet} /><Metric label={c.tracked} value={formatNumber(s.tracked_skus || 0)} hint={`${formatNumber(s.master_skus || 0)} ${c.master}`} icon={Boxes} /><Metric label={c.low} value={s.low_count || 0} icon={TriangleAlert} tone="amber" onClick={() => navigate('/inventory/stock?filter=low')} /><Metric label={c.expiry} value={s.near_expiry || 0} icon={CalendarClock} tone="red" onClick={() => navigate('/inventory/control')} /></div>
    <div className="flex flex-wrap gap-3 rounded-2xl bg-blue-50 px-4 py-3 text-xs font-semibold text-blue-900 dark:bg-blue-950 dark:text-blue-100">{[['branches', s.branch_count], ['warehouses', s.warehouse_count], ['devices', s.device_count]].map(([k, v]) => <span key={k}>{formatNumber(v || 0)} {c[k]}</span>)}</div>
    {!Number(s.stock_rows) && <Panel title={c.title}><Empty>{c.setup}</Empty><div className="mt-3 flex flex-wrap gap-2">{can?.updateInventory && <Button onClick={() => onAction({ kind: 'add' })}>{c.add}</Button>}<Button variant="outline" asChild><Link to="/products">{c.catalog}</Link></Button></div></Panel>}
    <div className="grid gap-4 xl:grid-cols-[1.15fr_1fr]"><Panel title={c.health} action={<Building2 className="h-5 w-5 text-primary" />}><div className="space-y-3">{ctx.snapshot.branches.map((b) => <button key={b.id} type="button" onClick={() => { ctx.setSelectedBranchId(b.id); navigate('/inventory/stock'); }} className="flex w-full items-center justify-between gap-3 rounded-2xl border p-4 text-start transition-colors hover:border-primary"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><Building2 className="h-5 w-5" /></span><div><b className="text-sm">{b.name}</b><p className="mt-1 text-xs text-muted-foreground">{b.item_count} SKU · {formatMoney(b.stock_value)}</p></div></div><div className="flex items-center gap-2">{Number(b.low_count) > 0 && <span className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-800">{b.low_count} {c.low}</span>}<ArrowUpRight className="h-4 w-4 text-muted-foreground" /></div></button>)}{!ctx.snapshot.branches.length && <Empty />}</div></Panel><Panel title={c.movements} action={<Link className="text-xs font-bold text-primary" to="/inventory/control">{c.viewAll}</Link>}><MovementList rows={ctx.snapshot.movements} /></Panel></div>
    {(Number(s.pending_approvals) > 0 || Number(s.blocked_count) > 0 || Number(s.unmapped_pos_items) > 0) && <Panel title={c.attention}><div className="grid gap-2 sm:grid-cols-3"><Metric label={c.approvals} value={s.pending_approvals || 0} icon={ShieldCheck} onClick={() => navigate('/inventory/control')} /><Metric label={c.blocked} value={s.blocked_count || 0} icon={TriangleAlert} tone="red" onClick={() => navigate('/inventory/stock?filter=blocked')} /><Metric label={c.noMapping} value={s.unmapped_pos_items || 0} icon={ScanLine} tone="amber" /></div></Panel>}
  </>;
}
function Stock({ ctx, onAction, onDetail }) {
  const c = useInventoryCopy(); const { formatMoney, formatNumber } = useLanguage(); const location = useLocation(); const { can } = useRole();
  const searchRef = useRef(null); const stockPath = useRef(location.pathname);
  const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(1);
  const [filter, setFilter] = useState(() => new URLSearchParams(location.search).get('filter') || 'all'); const [exporting, setExporting] = useState(false);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 250); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { setPage(1); }, [ctx.branchId, ctx.warehouseId, filter]);
  useEffect(() => { if (location.pathname === '/inventory/stock') { const f = new URLSearchParams(location.search).get('filter'); if (['all', 'low', 'expiry', 'blocked'].includes(f)) setFilter(f); } }, [location.pathname, location.search]);
  useEffect(() => {
    if (location.pathname !== stockPath.current) return;
    const barcode = new URLSearchParams(location.search).get('barcode');
    if (barcode !== null) { setSearch(barcode); setQuery(barcode); setFilter('all'); setPage(1); }
  }, [location.pathname, location.search, location.key]);
  const data = useInventoryList(ctx, 'stock', { p_query: query, p_filter: filter, p_page: page });
  const exportCSV = async () => {
    setExporting(true); try {
      let rows = []; let total = 0; let cursor = 1;
      do { const result = await inventoryRPC('stock', { ...ctx.params, p_query: query, p_filter: filter, p_page: cursor++, p_page_size: 100 }); total = Number(result.total); if (!result.rows.length) break; rows.push(...result.rows); } while (rows.length < total);
      const columns = ['name', 'name_ar', 'sku', 'barcode', 'branch_name', 'warehouse_name', 'on_hand', 'reserved', 'blocked', 'available', 'unit', 'average_cost', 'stock_value', 'pack_size', 'min_stock', 'max_stock', 'bin_location'];
      const numericColumns = new Set(['on_hand', 'reserved', 'blocked', 'available', 'average_cost', 'stock_value', 'pack_size', 'min_stock', 'max_stock']);
      const csv = '\uFEFF' + [columns.map(csvCell).join(','), ...rows.map((r) => columns.map((k) => csvCell(numericColumns.has(k) ? Number(r[k] || 0) : r[k])).join(','))].join('\r\n');
      const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'BizCTRL_Inventory.csv'; document.body.append(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (err) { toast.error(err.message); } finally { setExporting(false); }
  };
  return <><div className="flex flex-wrap gap-2">{can?.updateInventory && <><Button className="gap-2 rounded-xl" onClick={() => onAction({ kind: 'add' })}><Plus className="h-4 w-4" />{c.add}</Button><Button variant="outline" className="gap-2 rounded-xl" onClick={() => onAction({ kind: 'import' })}><FileSpreadsheet className="h-4 w-4" />{c.import}</Button></>}{can?.exportPDF && <Button variant="outline" className="gap-2 rounded-xl" disabled={exporting || !data.data?.total} onClick={exportCSV}><Download className="h-4 w-4" />{exporting ? c.pending : c.export}</Button>}<Button variant="outline" asChild><Link to="/products">{c.catalog}</Link></Button></div>
    <Panel title={c.stock} subtitle={c.stockHint}><div className="relative"><Search className="absolute start-3 top-3.5 h-4 w-4 text-muted-foreground" /><input ref={searchRef} aria-label={c.search} className={`${fieldClass} ps-9`} value={search} placeholder={c.search} onChange={(e) => setSearch(e.target.value)} /></div><div className="my-3 flex flex-wrap gap-2">{['all', 'low', 'expiry', 'blocked'].map((f) => <Button key={f} variant={f === filter ? 'default' : 'outline'} size="sm" className="rounded-full text-xs" onClick={() => setFilter(f)}>{c[f]}</Button>)}</div>
    {data.error ? <ErrorNotice error={data.error} retry={data.refetch} /> : <div className="grid gap-3 xl:grid-cols-2">{data.data?.rows?.map((p) => <button key={p.id} onClick={() => onDetail(p)} type="button" className="space-y-3 rounded-2xl border bg-background p-4 text-start transition-colors hover:border-primary"><div className="flex items-start justify-between gap-3"><ProductIdentity product={p} />{Number(p.on_hand) < 0 ? <TriangleAlert className="h-5 w-5 shrink-0 text-red-500" aria-label={c.shortage} /> : Number(p.available) <= Number(p.min_stock) && <span className="whitespace-nowrap rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-800">{c.low}</span>}</div><p className="text-[11px] text-muted-foreground">{p.branch_name} · {p.warehouse_name}{p.bin_location && ` · ${p.bin_location}`}</p><div className="grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-900">{[['onHand', p.on_hand], ['reserved', p.reserved], ['available', p.available]].map(([label, value]) => <div key={label}><p className="text-[10px] text-muted-foreground">{c[label]}</p><p className={`mt-1 text-lg font-black ${label === 'available' ? 'text-primary' : ''}`}>{formatNumber(value)}</p></div>)}</div><div className="flex flex-wrap justify-between gap-2 text-[11px] text-muted-foreground"><span>{c.unitCost} {formatMoney(p.average_cost)}</span><span>{p.pack_size > 1 ? `1 ${c.carton} = ${p.pack_size} ${p.unit}` : p.unit}</span><span>{p.batch_count} {c.batches}</span></div></button>)}</div>}{!data.isFetching && !data.data?.rows?.length && <Empty>{c.setup}</Empty>}<Pagination page={page} total={data.data?.total || 0} onChange={setPage} busy={data.isFetching} /></Panel>
  </>;
}
export function DocumentList({ ctx, onDocument, assurance = false }) {
  const c = useInventoryCopy(); const { formatMoney, formatDate } = useLanguage();
  const [kind, setKind] = useState('all'); const [status, setStatus] = useState(assurance ? 'requested' : 'all'); const [page, setPage] = useState(1);
  const query = useInventoryList(ctx, 'documents', { p_kind: kind, p_status: status, p_page: page });
  useEffect(() => { setPage(1); }, [ctx.branchId, ctx.warehouseId, kind, status]);
  return <Panel title={assurance ? c.approvals : c.documents} subtitle={assurance ? c.ownerReview : undefined}><div className="mb-4 grid grid-cols-2 gap-2"><Field label={c.documents}><select className={fieldClass} value={kind} onChange={(e) => setKind(e.target.value)}>{['all', 'receipt', 'transfer', 'count', 'adjustment', 'return', 'reorder'].map((k) => <option key={k} value={k}>{c[k]}</option>)}</select></Field><Field label={c.details}><select className={fieldClass} value={status} onChange={(e) => setStatus(e.target.value)}>{['all', 'draft', 'requested', 'approved', 'in_transit', 'received', 'posted', 'rejected', 'cancelled'].map((k) => <option key={k} value={k}>{c[k]}</option>)}</select></Field></div>{query.error ? <ErrorNotice error={query.error} retry={query.refetch} /> : <div className="space-y-3">{query.data?.rows?.map((d) => <button key={d.id} type="button" className="w-full space-y-2 rounded-2xl border p-4 text-start hover:border-primary" onClick={() => onDocument(d)}><div className="flex items-center justify-between gap-2"><b className="text-sm">{d.document_number}</b><Status status={d.status} /></div><p className="text-xs">{c[d.kind]} · {d.warehouse_name || c.source}{d.destination_name && ` → ${d.destination_name}`}</p><p className="text-xs text-muted-foreground">{d.branch_name} · {d.supplier_name}</p><div className="flex justify-between text-[11px] text-muted-foreground"><span>{d.kind === 'count' ? `${d.counted_count}/${d.line_count} · ${d.variance_count} ${c.variance}` : formatMoney(d.total_cost)}</span><span>{formatDate(d.created_at)}</span></div></button>)}</div>}{!query.isFetching && !query.data?.rows?.length && <Empty />}<Pagination page={page} total={query.data?.total || 0} size={20} onChange={setPage} busy={query.isFetching} /></Panel>;
}
function Operations({ ctx, onAction, onDocument }) {
  const c = useInventoryCopy(); const { formatNumber } = useLanguage(); const { can } = useRole();
  return <><div className="flex flex-wrap gap-2">{can?.updateInventory && ['adjustment', 'return', 'reorder'].map((k) => <Button key={k} variant="outline" className="rounded-xl" onClick={() => onAction({ kind: k })}>{c[k]}</Button>)}<Button variant="outline" asChild><Link to="/purchase-orders">{c.purchaseOrders}</Link></Button></div><div className="grid items-start gap-4 xl:grid-cols-2"><DocumentList ctx={ctx} onDocument={onDocument} /><div className="space-y-4"><Panel title={c.incoming} action={<ArrowDownToLine className="h-5 w-5 text-primary" />}>{ctx.snapshot.purchase_orders.length ? <div className="space-y-3">{ctx.snapshot.purchase_orders.map((po) => <div key={po.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b className="text-sm">{po.order_number}</b><p className="text-xs text-muted-foreground">{po.supplier_name} · {po.expected_date}</p></div>{can?.createPurchases && can?.updateInventory && <Button size="sm" onClick={() => onAction({ kind: 'receipt', order_id: po.id, branch_id: po.branch_id })}>{c.receipt}</Button>}</div>)}</div> : <Empty />}</Panel><Panel title={c.replenishment} subtitle={`${c.min} → ${c.max}`}>{ctx.snapshot.replenishment.length ? <div className="space-y-3">{ctx.snapshot.replenishment.map((p) => <div key={p.id} className="space-y-2 rounded-xl border p-3"><ProductIdentity product={p} compact /><p className="text-xs text-muted-foreground">{p.branch_name} · {p.warehouse_name} · {c.available}: {formatNumber(p.available)}</p><div className="flex items-center justify-between"><b className="text-sm">+{formatNumber(p.suggested_quantity)} {p.unit}</b>{can?.updateInventory && Number(p.suggested_quantity) > 0 && <Button variant="outline" size="sm" onClick={() => onAction({ kind: 'reorder', warehouse_id: p.warehouse_id, branch_id: p.branch_id, supplier_id: p.supplier_id, lines: [p] })}>{c.reorder}</Button>}</div></div>)}</div> : <Empty />}</Panel></div></div></>;
}
function Control({ ctx, onAction, onDocument }) {
  const c = useInventoryCopy(); const { role, can } = useRole(); const { formatNumber, formatDate } = useLanguage(); const [auditPage, setAuditPage] = useState(1);
  const audit = useQuery({ queryKey: ['retail-inventory', ctx.restaurantId, 'audit', ctx.branchId, auditPage], queryFn: async () => { let q = supabase.from('retail_inventory_audit').select('*', { count: 'exact' }).eq('restaurant_id', ctx.restaurantId); if (ctx.branchId) q = q.eq('branch_id', ctx.branchId); const result = await q.order('created_at', { ascending: false }).order('id').range((auditPage - 1) * 20, auditPage * 20 - 1); if (result.error) throw result.error; return result; }, enabled: ctx.enabled });
  return <><div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><Metric label={c.approvals} value={ctx.snapshot.summary.pending_approvals || 0} icon={ShieldCheck} /><Metric label={c.expiry} value={ctx.snapshot.summary.near_expiry || 0} icon={CalendarClock} tone="amber" /><Metric label={c.blocked} value={ctx.snapshot.summary.blocked_count || 0} icon={TriangleAlert} tone="red" /></div><div className="flex flex-wrap gap-2">{can?.updateInventory && <Button className="gap-2 rounded-xl" onClick={() => onAction({ kind: 'count' })}><ClipboardCheck className="h-4 w-4" />{c.count}</Button>}{role === 'owner' && <Button variant="outline" className="gap-2 rounded-xl" onClick={() => onAction({ kind: 'warehouse' })}><Warehouse className="h-4 w-4" />{c.createWarehouse}</Button>}</div>
    <div className="grid items-start gap-4 xl:grid-cols-2"><DocumentList ctx={ctx} onDocument={onDocument} assurance /><Panel title={c.expiryQueue} subtitle={c.fefo}>{ctx.snapshot.expiry.length ? <div className="space-y-3">{ctx.snapshot.expiry.map((lot) => <div key={lot.id} className="space-y-3 rounded-2xl border p-3"><ProductIdentity product={lot} compact /><p className="text-xs text-muted-foreground">{lot.branch_name} · {lot.warehouse_name} · {lot.batch_number}</p><div className="flex items-center justify-between text-sm"><b>{formatNumber(lot.quantity)} {lot.unit}</b><span>{lot.expiry_date || '—'}</span>{lot.quarantined && <Status status="quarantine" />}</div>{can?.updateInventory && <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => onAction({ kind: 'adjustment', branch_id: lot.branch_id, warehouse_id: lot.warehouse_id, lines: [{ ...lot, lot_id: lot.id, suggested_quantity: -Math.abs(Number(lot.quantity)), average_cost: lot.unit_cost }] })}>{c.writeOff}</Button>{lot.quarantined && role === 'owner' && <Button size="sm" variant="outline" onClick={() => onAction({ kind: 'release', lot_id: lot.id })}>{c.release}</Button>}</div>}</div>)}</div> : <Empty />}</Panel></div>
    <Panel title={c.history} subtitle={c.ownerReview}>{audit.error ? <ErrorNotice error={audit.error} retry={audit.refetch} /> : <div className="divide-y">{audit.data?.data.map((entry) => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-xs"><div><b>{c[entry.action] || entry.action}</b><p className="mt-1 text-muted-foreground">{entry.detail}</p></div><span className="text-muted-foreground">{formatDate(entry.created_at)}</span></div>)}</div>}{!audit.isFetching && !audit.data?.count && <Empty />}<Pagination page={auditPage} total={audit.data?.count || 0} size={20} onChange={setAuditPage} busy={audit.isFetching} /></Panel>
  </>;
}
export default function RetailInventory({ page = 'overview', scanOnOpen = false }) {
  const ctx = useRetailInventory(); const c = useInventoryCopy(); const { role, can } = useRole(); const navigate = useNavigate();
  const location = useLocation(); const entryPath = useRef(location.pathname);
  const [action, setAction] = useState(null); const [document, setDocument] = useState(null); const [product, setProduct] = useState(null);
  const onAction = (config) => { if (config.kind === 'add' && !ctx.branchId) { toast.info(c.requiredBranch); return; } setAction(config); };
  useEffect(() => { if (location.pathname !== entryPath.current) { setAction(null); setDocument(null); setProduct(null); } }, [location.pathname]);
  // Changing business scope must not leave an old tenant's editable modal open.
  useEffect(() => { setAction(null); setDocument(null); setProduct(null); }, [ctx.restaurantId]);
  useEffect(() => {
    if (location.pathname === entryPath.current && (scanOnOpen || (page === 'stock' && new URLSearchParams(location.search).get('scan') === '1'))) setAction({ kind: 'scan' });
  }, [scanOnOpen, page, location.pathname, location.search, location.key]);
  return <><InventoryWorkspace ctx={ctx} active={page} actions={<QuickActions edit={can?.updateInventory} purchase={can?.createPurchases} onAction={onAction} />}>
    {page === 'overview' && <Overview ctx={ctx} onAction={onAction} />}{page === 'stock' && <Stock ctx={ctx} onAction={onAction} onDetail={setProduct} />}{page === 'operations' && <Operations ctx={ctx} onAction={onAction} onDocument={setDocument} />}{page === 'control' && <Control ctx={ctx} onAction={onAction} onDocument={setDocument} />}
  </InventoryWorkspace>
  {action?.kind === 'barcode' && ctx.enabled && can?.updateInventory && location.pathname === entryPath.current && <ProductBarcodeDialog key={ctx.restaurantId} restaurantId={ctx.restaurantId} onClose={() => setAction(null)} onChanged={ctx.refresh} />}
  {action?.kind === 'scan' && <BarcodeScanDialog open onOpenChange={(open) => !open && setAction(null)} onScan={(barcode) => navigate(`/inventory/stock?barcode=${encodeURIComponent(barcode)}`)} />}
  {action?.kind === 'add' && <ProductPicker ctx={ctx} open onClose={() => setAction(null)} onSelect={async (products) => { try { await ctx.run({ command: 'assign', payload: { branch_id: ctx.branchId, warehouse_id: ctx.warehouseId, product_ids: products.map((p) => p.id) } }); toast.success(c.success); } catch (err) { toast.error(err.message); throw err; } }} />}
  {action?.kind === 'import' && can?.updateInventory && <Suspense fallback={null}><ProductBulkImportDialog open isAllowed={ctx.enabled} onOpenChange={(v) => !v && setAction(null)} restaurantId={ctx.restaurantId} selectedBranch={ctx.selectedBranch} onImported={ctx.refresh} /></Suspense>}
  {['warehouse', 'release'].includes(action?.kind) && role === 'owner' && <InventorySettingsDialog ctx={ctx} config={action} onClose={() => setAction(null)} />}
  {['receipt', 'transfer', 'count', 'adjustment', 'return', 'reorder'].includes(action?.kind) && can?.updateInventory && <InventoryDocumentForm ctx={ctx} config={action} onClose={() => setAction(null)} onCreated={setDocument} />}
  {document && <InventoryDocumentDetail key={document.id} ctx={ctx} document={document} onClose={() => setDocument(null)} />}
  {product && <InventoryStockDetail key={product.id} ctx={ctx} product={product} onClose={() => setProduct(null)} onAction={onAction} />}
  </>;
}
