import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Package,Maximize,ArrowLeft,RefreshCw} from 'lucide-react';
import {money} from '@/lib/retailCashier';
import {groupRestaurantFoods,canSellServing,PORTIONS,SIDES,touchCopy as servingCopy} from '@/lib/restaurantServingOptions';
import {axesFromItems} from '@/lib/restaurantCustomization';
import {Pager,touchCopy,usePage} from './TouchPrimitives';

function Variant({group,lang,currency,onAdd,close,editable}){
 const t=touchCopy(lang),s=servingCopy(lang);const first=group.items.find(canSellServing)||group.items[0];
 const custom=Boolean(first.variant_options?.length);
 const axes=custom?axesFromItems(group.items).map(a=>({label:a.label,values:a.values.split('\n')})):[{label:s.size,values:PORTIONS},{label:s.side,values:SIDES}];
 const [selected,setSelected]=useState(()=>custom?first.variant_options.map(o=>o.value):first.option_key.split('_'));
 const [step,setStep]=useState(0),[quantity,setQuantity]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');const inFlight=useRef(false);
 const item=group.items.find(m=>custom?m.variant_options?.length===axes.length&&m.variant_options.every((o,i)=>o.value===selected[i]):m.option_key===selected.join('_'));
 const options=usePage(axes[step]?.values||[],6,step);const summary=step===axes.length;
 const add=async()=>{if(!editable||!canSellServing(item)||inFlight.current)return;inFlight.current=true;setBusy(true);try{const result=await onAdd(item,quantity);if(result!==null)close();}catch(e){setError(e.message);}finally{inFlight.current=false;setBusy(false);}};
 return <section className="touch-layer" role="dialog" aria-modal="true" aria-label={group.title}><header><h2>{group.title}</h2><button disabled={busy} onClick={close}>{t.cancel}</button></header><div className="touch-layer-body">{!summary?<><h2>{axes[step].label}</h2><div className="touch-options">{options.items.map(value=><button key={value} aria-pressed={selected[step]===value} onClick={()=>setSelected(a=>a.map((v,i)=>i===step?value:v))}>{custom?value:s[value]}</button>)}</div>{options.pages>1&&<Pager {...options} onChange={options.setPage} lang={lang}/>}</>:<><h2>{item?.['name_'+lang]||item?.name||t.empty}</h2><strong className="text-3xl">{canSellServing(item)?money(item.price,currency):t.empty}</strong><div className="touch-line-controls"><button aria-label="−" disabled={quantity<=1||busy} onClick={()=>setQuantity(q=>q-1)}>−</button><output>{quantity}</output><button aria-label="+" disabled={quantity>=99||busy} onClick={()=>setQuantity(q=>q+1)}>+</button></div></>}{error&&<p role="alert">{error}</p>}</div><footer className="touch-footer"><button disabled={step===0||busy} onClick={()=>setStep(p=>p-1)}>{t.previous}</button>{summary?<button className="touch-primary" disabled={!editable||!canSellServing(item)||busy} onClick={add}>{t.add} · {money(Number(item?.price||0)*quantity,currency)}</button>:<button className="touch-primary" onClick={()=>setStep(p=>p+1)}>{t.next} ({step+1}/{axes.length+1})</button>}</footer></section>;
}

export default function TouchWorkspace({kind,api,lang='en',c,menu=[],search,setSearch,catalogPage=1,setCatalogPage,hasMore=false,catalogLoading=false,catalogError,editable,canPay,canStart,onAdd,onQuantity,onScan,onAction,onExit,actions=[],held=[],receipts=[],onResume,onReceipt,selection}){
 const t=touchCopy(lang),restaurant=kind==='restaurant';const s=api.snapshot,cart=s?.cart,currency=s?.business?.currency||'SAR';
 const [size,setSize]=useState(()=>({w:window.innerWidth,h:window.innerHeight}));
 const [mobileView,setMobileView]=useState('products');
 const [category,setCategory]=useState(''),[overlay,setOverlay]=useState(null),[scan,setScan]=useState(''),[dismissed,setDismissed]=useState('');const scanner=useRef(null),root=useRef(null);
 useEffect(()=>{const update=()=>setSize({w:window.innerWidth,h:window.innerHeight});window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update);},[]);
 const compact=size.w<1000;const pageSize=compact?(size.h<600?2:4):(size.w>=1450?4:3)*(size.h>=850?3:2),lineSize=size.h<600?2:size.h>=850?5:3;
 useEffect(()=>{const body=document.body.style.overflow,html=document.documentElement.style.overflow;document.body.classList.add('touch-cashier-open');document.body.style.overflow='hidden';document.documentElement.style.overflow='hidden';return()=>{document.body.classList.remove('touch-cashier-open');document.body.style.overflow=body;document.documentElement.style.overflow=html;};},[]);
 const groups=restaurant?groupRestaurantFoods(menu,{search,category}):menu.map(m=>({id:m.id,items:[m],grouped:false}));
 const products=usePage(groups,pageSize,search+category+catalogPage);const lines=usePage(cart?.lines||[],lineSize,cart?.id||'');
 const categories=[...new Map(menu.filter(m=>m.active&&(m.category_id||m.category)).map(m=>[m.category_id||m.category,m])).entries()];
 const categoryActions=[{id:'',label:c.food},...categories.map(([id,m])=>({id,label:m['category_'+lang]||m.category}))];
 const records=usePage(overlay==='held'?held:overlay==='receipts'?receipts:overlay==='categories'?categoryActions:actions,['actions','categories'].includes(overlay)?6:4,overlay);
 const name=m=>m?.['name_'+lang]||m?.name||m?.name_en||m?.name_ar||'';
 const error=catalogError||api.error;const showError=error&&error!==dismissed;
 const add=async(item,quantity=1)=>{const result=await onAdd(item,quantity);if(!restaurant)scanner.current?.focus();return result;};
 const layer=overlay&&typeof overlay==='object';
 return createPortal(<div className="touch-pos" ref={root} dir={lang==='en'?'ltr':'rtl'} data-touch-pos={kind} data-mobile-view={mobileView}>
  <header className="touch-top"><button onClick={onExit} aria-label={t.exit}><ArrowLeft size={20}/></button><strong>{s?.business?.branch_name} · {s?.device?.code}<small>{s?.shift?.cashier_name} · {api.connected?c.live:c.offline}</small></strong>{selection}<button aria-label={c.refresh} onClick={()=>void api.refresh()}><RefreshCw size={20}/></button><button aria-label={t.full} onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen?.().catch(()=>{});else void document.documentElement.requestFullscreen?.().catch(()=>{});}}><Maximize size={20}/></button><button onClick={()=>setOverlay('actions')}>{t.more}</button></header>
  {compact&&<nav className="touch-mobile-tabs"><button aria-pressed={mobileView==='products'} onClick={()=>setMobileView('products')}>{t.products}</button><button aria-pressed={mobileView==='invoice'} onClick={()=>setMobileView('invoice')}>{t.invoice} ({cart?.lines?.length||0}) · {money(cart?.net_total,currency)}</button></nav>}
  <div className="touch-columns" aria-hidden={overlay?true:undefined} inert={overlay?'':undefined}>
   <section className="touch-catalog"><div className="touch-search"><input aria-label={c.search} placeholder={c.search} value={search} onChange={e=>setSearch(e.target.value)}/>{restaurant&&<button onClick={()=>setOverlay('categories')}>{categoryActions.find(a=>a.id===category)?.label||c.food}</button>}</div>
    {!restaurant&&<form className="touch-search" onSubmit={e=>{e.preventDefault();if(editable&&scan){onScan(scan);setScan('');}}}><input ref={scanner} aria-label={c.scan} placeholder={c.scan} value={scan} disabled={!editable} onChange={e=>setScan(e.target.value)} autoComplete="off"/><button type="submit" disabled={!editable||!scan}>{c.add}</button></form>}
    <div className="touch-grid">{products.items.map(group=>{const m=group.items.find(v=>v.active)||group.items[0];const title=group.grouped?group.title:name(m);return <button type="button" className="touch-product" key={group.id} disabled={!group.grouped&&(!editable||(restaurant?!canSellServing(m):Number(m.available)<=0||m.serial_tracked))} onClick={()=>group.grouped?setOverlay(group):void add(m)}>{m.image_url?<img src={m.image_url} alt=""/>:<Package size={35}/>}<strong>{title}</strong><span>{group.grouped?t.choose:money(m.price,currency)}</span></button>;})}{!groups.length&&<p>{catalogLoading?'…':t.empty}</p>}</div>
    <nav className="touch-pager"><button disabled={catalogLoading||(products.page===0&&(!setCatalogPage||catalogPage<=1))} onClick={()=>products.page>0?products.setPage(products.page-1):setCatalogPage(catalogPage-1)}>{t.previous}</button><output>{!restaurant&&`${catalogPage} · `}{products.page+1} / {products.pages}</output><button disabled={catalogLoading||(products.page===products.pages-1&&!hasMore)} onClick={()=>products.page<products.pages-1?products.setPage(products.page+1):setCatalogPage?.(catalogPage+1)}>{t.next}</button></nav>
   </section>
   <aside className="touch-invoice"><header><strong>{t.invoice} {cart?.number?`#${cart.number}`:''}</strong><span>{cart?.lines?.length||0}</span></header><div className="touch-lines">{lines.items.map(line=><div className="touch-line" key={line.menu_id||line.product_id}><div><strong>{name(line)}</strong><small dir="ltr">{money(line.line_total,currency)}</small></div><div className="touch-line-controls"><button disabled={!editable} aria-label={c.remove+' '+name(line)} onClick={()=>onQuantity(line,-1)}>−</button><output>{line.quantity}</output><button disabled={!editable} aria-label={c.quantity+' '+name(line)} onClick={()=>onQuantity(line,1)}>+</button></div></div>)}{!cart?.lines?.length&&<p>{c.empty||t.empty}</p>}</div><Pager page={lines.page} pages={lines.pages} onChange={lines.setPage} lang={lang}/><div className="touch-total"><div><small>{c.tax}</small><small dir="ltr">{money(cart?.tax_total,currency)}</small></div><div><strong>{c.total}</strong><strong dir="ltr">{money(cart?.net_total,currency)}</strong></div></div><button className="touch-primary" disabled={cart?!canPay:!canStart||api.busy||!api.connected||Boolean(api.pending)} onClick={()=>onAction(cart?'payment':s?.shift?'new_sale':'open')}>{cart?c.pay:s?.shift?c.newSale:c.openShift}</button><div className="touch-footer"><button onClick={()=>setOverlay('held')}>{t.hold} ({held.length})</button><button onClick={()=>setOverlay('receipts')}>{t.receipts}</button></div></aside>
  </div>
  {layer&&<Variant key={overlay.id} group={overlay} lang={lang} currency={currency} onAdd={add} editable={editable} close={()=>setOverlay(null)}/>}
  {typeof overlay==='string'&&<section className="touch-layer" role="dialog" aria-modal="true" aria-label={t[overlay]||t.more}><header><h2>{t[overlay]||t.more}</h2><button onClick={()=>setOverlay(null)}>{t.cancel}</button></header><div className="touch-layer-body">{['actions','categories'].includes(overlay)?<div className="touch-options">{records.items.map(action=><button key={action.id} disabled={action.disabled} onClick={()=>{setOverlay(null);if(overlay==='categories')setCategory(action.id);else onAction(action.id);}}>{action.label}</button>)}</div>:records.items.map((r,i)=><div className="touch-record" key={r.id||i}><strong>{r.receipt_number||'#'+(r.number||r.id?.slice(0,8))} · {money(r.cart?.net_total??r.net_total,currency)}</strong><button disabled={overlay==='held'&&(Boolean(cart)||api.busy||Boolean(api.pending))} onClick={()=>{if(overlay==='held'){void onResume(r);setOverlay(null);}else void onReceipt(r);}}>{overlay==='held'?c.resume:c.print}</button></div>)}</div><Pager page={records.page} pages={records.pages} onChange={records.setPage} lang={lang}/></section>}
  {(showError||api.pending)&&<div className="touch-alert" role="alert"><p>{api.pending?c.pending:error}</p>{api.pending?<button disabled={Boolean(api.busy)} onClick={()=>onAction('retry')}>{c.retry}</button>:<button onClick={()=>setDismissed(error)}>{t.cancel}</button>}</div>}
 </div>,document.body);
}
