import {useRef,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {parseProductSpreadsheet} from '@/lib/productSpreadsheet';
import {downloadFoodFile,foodCsv,foodTemplate,prepareFoodImport,runFoodImport} from '@/lib/restaurantFoodImport';
import {restaurantRpc} from '@/lib/restaurantPOS';

export function foodImportCopy(lang){return ({
 en:{title:'Import foods · Excel / CSV',hint:'Up to 500 dishes for this branch. Each row is a separate dish. Configure sizes and custom options afterwards in the food editor. Purchase materials are separate.',template:'Download Excel template',reference:'Download category & ingredient IDs',choose:'Choose Excel / CSV',preview:'Preview',ready:'Ready',errors:'Errors',confirm:'I confirm that foods marked untracked will not automatically deduct ingredients.',import:'Import foods',retry:'Retry failed rows',close:'Close',prev:'Previous',next:'Next',report:'Download report',update:'Update',create:'New',success:'Saved',failed:'Failed',notice:'Keep food_code unchanged to update the same imported dish. Codes are case-sensitive and scoped to this branch. Each row saves separately; successful rows remain if another fails. Prices include tax. Recipe JSON example: [{"inventory_id":"ID from reference file","quantity":0.5}]. Replace the template example with your foods.',missing:'Choose a file and resolve all errors first.'},
 ar:{title:'استيراد الأطعمة · Excel / CSV',hint:'حتى ٥٠٠ طبق لهذا الفرع. كل صف طبق مستقل. اضبط الأحجام والخيارات لاحقاً من محرر الطعام. مواد الشراء منفصلة.',template:'تحميل قالب Excel',reference:'تحميل معرفات الفئات والمكونات',choose:'اختيار Excel / CSV',preview:'معاينة',ready:'جاهز',errors:'أخطاء',confirm:'أؤكد أن الأطعمة بنمط untracked لا تخصم المكونات تلقائياً.',import:'استيراد الأطعمة',retry:'إعادة الصفوف الفاشلة',close:'إغلاق',prev:'السابق',next:'التالي',report:'تحميل التقرير',update:'تحديث',create:'جديد',success:'تم الحفظ',failed:'فشل',notice:'احتفظ بنفس food_code لتحديث الطبق المستورد في هذا الفرع؛ الأحرف الكبيرة والصغيرة مختلفة. يُحفظ كل صف مستقلاً. الأسعار شاملة الضريبة. مثال recipe_json: [{"inventory_id":"معرف المكون","quantity":0.5}]. استبدل المثال بأطباقك.',missing:'اختر ملفاً وصحح جميع الأخطاء أولاً.'},
 fa:{title:'امپورت غذا · Excel / CSV',hint:'تا ۵۰۰ غذا برای همین فرع. هر سطر یک غذای جدا است. اندازه‌ها و گزینه‌ها را بعداً در ویرایش غذا تنظیم کنید. مواد اولیهٔ خرید جدا است.',template:'دانلود نمونهٔ اکسل',reference:'دانلود شناسهٔ کتگوری و مواد اولیه',choose:'انتخاب Excel / CSV',preview:'پیش‌نمایش',ready:'آماده',errors:'خطاها',confirm:'تأیید می‌کنم غذاهای با حالت untracked مواد اولیه را خودکار از انبار کم نمی‌کنند.',import:'امپورت غذاها',retry:'تلاش مجدد سطرهای ناموفق',close:'بستن',prev:'قبلی',next:'بعدی',report:'دانلود گزارش',update:'به‌روزرسانی',create:'جدید',success:'ذخیره شد',failed:'ناموفق',notice:'برای به‌روزرسانی همان غذای واردشده، food_code را تغییر ندهید. حروف بزرگ و کوچک فرق دارند و کد مخصوص همین فرع است. هر سطر جدا ذخیره می‌شود؛ سطرهای موفق باقی می‌مانند. قیمت شامل مالیات است. نمونهٔ recipe_json: [{"inventory_id":"شناسه از فایل مرجع","quantity":0.5}]. نمونه را با غذاهای خود جایگزین کنید.',missing:'فایل را انتخاب و تمام خطاها را اصلاح کنید.'}
 })[lang]||foodImportCopy('en');}
const btn='min-h-12 rounded-xl border px-4 py-3 text-sm font-bold disabled:opacity-40';
export default function RestaurantFoodImport({tenant,branch,catalog,lang,close,refresh}){
 const c=foodImportCopy(lang);const guard=useRef(false);const [busy,setBusy]=useState(false),[prepared,setPrepared]=useState(null),[results,setResults]=useState([]),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[page,setPage]=useState(0);
 const entries=results.length?results:prepared?.errors.length?prepared.errors:prepared?.rows||[];const pages=Math.max(1,Math.ceil(entries.length/10));
 const read=async file=>{if(!file||guard.current)return;guard.current=true;setBusy(true);setError('');setPrepared(null);setResults([]);setPage(0);setConfirmed(false);try{if(file.size>5*1024*1024)throw new Error('Maximum 5 MB.');const records=await parseProductSpreadsheet(file);setPrepared(await prepareFoodImport(records,{tenant,branch,...catalog}));}catch(e){setError(e.message);}finally{guard.current=false;setBusy(false);}};
 const save=async()=>{if(guard.current)return;if(!prepared||prepared.errors.length){setError(c.missing);return;}guard.current=true;setBusy(true);setError('');setPage(0);const targets=results.length?results.filter(r=>!r.ok):prepared.rows;const saved=results.filter(r=>r.ok);try{await runFoodImport(targets,{tenant,branch,confirmUntracked:confirmed,rpc:restaurantRpc,onProgress:progress=>setResults([...saved,...progress])});await refresh();}catch(e){setError(e.message);}finally{guard.current=false;setBusy(false);}};
 const reference=()=>downloadFoodFile(foodCsv([['type','id','name','unit'],...(catalog.categories||[]).filter(c=>c.is_active!==false).map(c=>['category',c.id,c.name,'']),...(catalog.inventory||[]).map(i=>['ingredient',i.id,i.product_name,i.unit])]),'restaurant-food-reference.csv');
 const hasUntracked=prepared?.rows.some(r=>r.payload.stock_mode==='untracked');const failed=results.filter(r=>!r.ok).length;
 return <Dialog open onOpenChange={open=>{if(!open&&!guard.current)close();}}><DialogContent dir={lang==='en'?'ltr':'rtl'} className="max-h-[90dvh] overflow-y-auto sm:max-w-3xl" onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onPointerDownOutside={e=>{if(busy)e.preventDefault();}}><DialogHeader><DialogTitle>{c.title}</DialogTitle><DialogDescription>{c.hint}</DialogDescription></DialogHeader>
  <p className="text-sm leading-6 text-slate-600">{c.notice}</p>
  <fieldset disabled={busy} className="flex flex-wrap gap-2"><button type="button" className={btn} onClick={()=>downloadFoodFile(foodTemplate(),'restaurant-food-import.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}>{c.template}</button><button type="button" className={btn} onClick={reference}>{c.reference}</button><label className={'grid gap-2 '+btn}>{c.choose}<input type="file" accept=".xlsx,.csv" onChange={e=>void read(e.target.files?.[0])}/></label></fieldset>
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
  {prepared&&<><p role="status">{c.ready}: {prepared.rows.length} · {c.errors}: {prepared.errors.length}{results.length>0&&` · ${c.success}: ${results.filter(r=>r.ok).length} · ${c.failed}: ${failed}`}{busy?' …':''}</p>
   <div className="divide-y rounded-xl border" aria-label={c.preview}>{entries.slice(page*10,page*10+10).map(r=><div key={r.row} className="grid gap-1 p-3 text-sm"><strong>{r.row} · {r.code} · {r.payload?.name} {r.payload?`· ${r.payload.price}`:''}</strong><span className={r.message?'text-red-700':'text-slate-500'}>{r.message||('ok' in r?r.ok?c.success:c.failed:r.update?c.update:c.create)}</span></div>)}</div>
   <div className="flex items-center justify-between"><button className={btn} disabled={page===0} onClick={()=>setPage(p=>p-1)}>{c.prev}</button><span>{page+1} / {pages}</span><button className={btn} disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)}>{c.next}</button></div>
   {hasUntracked&&<label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" className="h-6 w-6 shrink-0" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{c.confirm}</label>}
   <button className={btn+' bg-blue-600 text-white'} disabled={busy||!!prepared.errors.length||!prepared.rows.length||(hasUntracked&&!confirmed)||(results.length>0&&!failed)} onClick={()=>void save()}>{results.length?c.retry:c.import}</button>
   <button className={btn} disabled={busy} onClick={()=>downloadFoodFile(foodCsv([['row','food_code','name','result','message'],...entries.map(r=>[r.row,r.code,r.payload?.name,'ok' in r?r.ok?'saved':'failed':r.message?'invalid':r.update?'update':'new',r.message||''])]),'restaurant-food-import-report.csv')}>{c.report}</button>
  </>}
  <button className={btn} disabled={busy} onClick={close}>{c.close}</button>
 </DialogContent></Dialog>;
}
