import {useRef,useState} from 'react';
import {restaurantRpc} from '@/lib/restaurantPOS';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function foodDeleteCopy(lang){return ({en:{remove:'Delete from menu',all:'Select all results',selected:'Delete selected',show:'Show inactive / removed foods',hint:'These foods will be deactivated and removed from the sales menu. Past invoices and recipes are retained. You can reactivate them from inactive foods.',confirm:'Confirm removal',cancel:'Close',saved:'Removed',failed:'Failed',select:'Select',removing:'Removing…'},ar:{remove:'حذف من القائمة',all:'تحديد جميع النتائج',selected:'حذف المحدد',show:'عرض الأطعمة المحذوفة / غير النشطة',hint:'سيتم تعطيل الأطعمة وإزالتها من قائمة البيع مع الاحتفاظ بالفواتير السابقة والوصفات. يمكنك إعادة تفعيلها من الأطعمة غير النشطة.',confirm:'تأكيد الحذف',cancel:'إغلاق',saved:'تم الحذف',failed:'فشل',select:'تحديد',removing:'جارٍ الحذف…'},fa:{remove:'حذف از منو',all:'انتخاب تمام نتایج',selected:'حذف انتخاب‌شده‌ها',show:'نمایش غذاهای حذف‌شده / غیرفعال',hint:'غذاها غیرفعال و از منوی فروش حذف می‌شوند. فاکتورهای قبلی و دستور پخت باقی می‌مانند. از بخش غذاهای غیرفعال می‌توانید دوباره فعال‌شان کنید.',confirm:'تأیید حذف',cancel:'بستن',saved:'حذف شد',failed:'ناموفق',select:'انتخاب',removing:'در حال حذف…'}})[lang]||foodDeleteCopy('en');}
export default function RestaurantFoodDelete({items,tenant,branch,lang,close,onRemoved}){
 const c=foodDeleteCopy(lang),guard=useRef(false);const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const run=async()=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await restaurantRpc('pos_setup',{p_restaurant_id:tenant,p_branch_id:branch,p_command:'menu_archive',p_payload:{ids:items.map(i=>i.id)}});onRemoved(items.map(i=>i.id));}catch(e){setError(e.message);guard.current=false;setBusy(false);}};
 return <Dialog open onOpenChange={v=>{if(!v&&!guard.current)close();}}><DialogContent className="max-h-[85dvh] overflow-y-auto" dir={lang==='en'?'ltr':'rtl'}><DialogHeader><DialogTitle>{c.selected} ({items.length})</DialogTitle><DialogDescription>{c.hint}</DialogDescription></DialogHeader><div className="max-h-48 overflow-y-auto text-sm">{items.map(i=><p key={i.id}>{i['name_'+lang]||i.name}</p>)}</div>{error&&<p role="alert">{error}</p>}<button className="min-h-12 rounded-xl bg-red-600 px-4 font-bold text-white disabled:opacity-40" disabled={busy} onClick={()=>void run()}>{busy?c.removing:c.confirm}</button><button className="min-h-12 rounded-xl border" disabled={busy} onClick={close}>{c.cancel}</button></DialogContent></Dialog>;
}
