import React from 'react';
import { Link } from 'react-router-dom';
import { Activity, Boxes, ArrowLeftRight, ShieldCheck, RefreshCw, Radio, Package, AlertTriangle, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { useLanguage } from '@/lib/LanguageContext';
import { useInventoryCopy } from './inventoryCopy';
import { INVENTORY_PAGES, productName } from '@/lib/retailInventory';
export const fieldClass = 'min-h-11 w-full rounded-xl border border-slate-200 bg-background px-3 py-2 text-sm dark:border-slate-700';
export function Field({ label, children, hint }) { return <label className="grid gap-1.5 text-xs font-semibold text-muted-foreground"><span>{label}</span>{children}{hint && <span className="font-normal">{hint}</span>}</label>; }
export function Panel({ title, subtitle, action, children, className }) { return <section className={cn('overflow-hidden rounded-3xl border border-slate-200/80 bg-card shadow-sm dark:border-slate-800', className)}><header className="flex items-center justify-between gap-3 border-b border-slate-100 p-4 dark:border-slate-800"><div><h2 className="font-bold">{title}</h2>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</header><div className="p-4">{children}</div></section>; }
export function Empty({ children }) { const c = useInventoryCopy(); return <div className="grid justify-items-center gap-3 rounded-2xl border border-dashed p-7 text-center text-sm text-muted-foreground"><Package className="h-9 w-9 text-slate-300" /><p>{children || c.empty}</p></div>; }
export function ErrorNotice({ error, retry }) { const c = useInventoryCopy(); return <div role="alert" className="space-y-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-900"><p className="flex items-center gap-2 font-bold"><AlertTriangle className="h-4 w-4" />{c.error}</p><p className="text-sm break-words">{error?.message}</p>{retry && <Button variant="outline" onClick={retry}>{c.retry}</Button>}</div>; }
export function Status({ status }) { const c = useInventoryCopy(); return <span className={cn('inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-[11px] font-bold', ['posted', 'received', 'approved'].includes(status) ? 'bg-emerald-50 text-emerald-700' : ['rejected', 'cancelled', 'expired'].includes(status) ? 'bg-red-50 text-red-700' : status === 'in_transit' ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-800')}>{c[status] || status}</span>; }
export function Metric({ label, value, hint, icon: Icon, tone = 'blue', onClick }) { const Tag = onClick ? 'button' : 'div'; return <Tag type={onClick ? 'button' : undefined} onClick={onClick} className="rounded-2xl border border-slate-200/80 bg-card p-4 text-start shadow-sm dark:border-slate-800"><div className="flex items-start justify-between gap-2"><span className="text-xs font-medium text-muted-foreground">{label}</span>{Icon && <Icon className={cn('h-5 w-5 shrink-0', tone === 'amber' ? 'text-amber-500' : tone === 'red' ? 'text-red-500' : 'text-primary')} />}</div><p className="mt-2 text-2xl font-black tracking-tight lg:text-3xl">{value}</p>{hint && <p className="mt-1 text-[11px] text-muted-foreground">{hint}</p>}</Tag>; }
export function Pagination({ page, total, size = 30, onChange, busy }) { const c = useInventoryCopy(); return <div className="flex items-center justify-between gap-2 py-3 text-xs text-muted-foreground"><span>{c.page} {page} / {Math.max(1, Math.ceil(total / size))} · {total}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page <= 1 || busy} onClick={() => onChange(page - 1)} aria-label={c.back}><ChevronLeft className="h-4 w-4" /></Button><Button variant="outline" size="sm" disabled={page * size >= total || busy} onClick={() => onChange(page + 1)} aria-label={c.next}><ChevronRight className="h-4 w-4" /></Button></div></div>; }
export function ProductIdentity({ product, compact = false }) { const { lang } = useLanguage(); const name = productName(product, lang); return <div className="flex min-w-0 items-center gap-3">{!compact && <div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-blue-50">{product.image_url ? <img alt="" src={product.image_url} loading="lazy" className="h-full w-full object-contain" onError={(e) => { e.currentTarget.style.display = 'none'; }} /> : <Package className="h-6 w-6 text-blue-500" />}</div>}<div className="min-w-0"><p className="break-words text-sm font-bold">{name}</p>{product.name_ar && product.name_ar !== name && <p dir="rtl" className="mt-0.5 text-start text-xs text-muted-foreground">{product.name_ar}</p>}<p dir="ltr" className="mt-1 truncate text-start font-mono text-[10px] text-muted-foreground">{product.sku || product.barcode || '—'}</p></div></div>; }
const icons = [Activity, Boxes, ArrowLeftRight, ShieldCheck];
export function InventoryWorkspace({ ctx, active, actions, children }) {
  const c = useInventoryCopy(); const { lang } = useLanguage();
  const live = ctx.realtime.status === 'SUBSCRIBED';
  return <div dir={lang === 'en' ? 'ltr' : 'rtl'} className="mx-auto w-full max-w-[1600px] space-y-4 pb-28 lg:pb-8" data-inventory-page={active}>
    <section className="rounded-3xl border border-slate-200/80 bg-card p-4 shadow-sm dark:border-slate-800 sm:p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-black tracking-tight sm:text-2xl">{active === 'overview' ? c.title : c[active]}</h1><span className={cn('flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-bold', live ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800')}><Radio className="h-3 w-3" />{live ? c.live : ctx.realtime.status === 'CONNECTING' ? c.connecting : c.offline}</span></div><p className="mt-1 text-xs text-muted-foreground sm:text-sm">{c.subtitle}</p></div><Button variant="outline" size="icon" className="rounded-xl" aria-label={c.refresh} onClick={ctx.refresh} disabled={ctx.isFetching}><RefreshCw className={cn('h-4 w-4', ctx.isFetching && 'animate-spin')} /></Button></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-2"><Field label={c.branch}><select className={fieldClass} value={ctx.selectedBranchId || 'all'} onChange={(e) => ctx.setSelectedBranchId(e.target.value)} disabled={ctx.isBranchScoped}>{!ctx.isBranchScoped && <option value="all">{c.allBranches}</option>}{ctx.branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label={c.warehouse}><select className={fieldClass} value={ctx.warehouseId || ''} onChange={(e) => ctx.setWarehouseId(e.target.value)}><option value="">{c.allWarehouses}</option>{ctx.snapshot.warehouses.filter((w) => !ctx.branchId || w.branch_id === ctx.branchId).map((w) => <option key={w.id} value={w.id}>{w.name} · {ctx.branches.find((b) => b.id === w.branch_id)?.name}</option>)}</select></Field></div>
      <nav aria-label="Inventory pages" className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{INVENTORY_PAGES.map((p, i) => { const Icon = icons[i]; return <Link key={p.key} to={p.path} aria-current={active === p.key ? 'page' : undefined} className={cn('flex min-h-12 items-center justify-center gap-2 rounded-xl border px-2 py-2 text-center text-xs font-bold transition-colors sm:text-sm', active === p.key ? 'border-primary bg-primary text-primary-foreground shadow-sm' : 'bg-background text-muted-foreground hover:border-primary/40')}><Icon className="h-4 w-4 shrink-0" />{c[p.key]}</Link>; })}</nav>
    </section>
    {actions}{ctx.error ? <ErrorNotice error={ctx.error} retry={ctx.refresh} /> : ctx.isLoading ? <div aria-busy="true" className="grid grid-cols-2 gap-3">{[1, 2, 3, 4].map((i) => <div key={i} className="h-32 animate-pulse rounded-2xl bg-slate-200/60 dark:bg-slate-800" />)}</div> : children}
  </div>;
}
