import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/api/supabaseClient';
import { platformOwnerApi } from '@/lib/platformOwnerApi';
import { useLanguage } from '@/lib/LanguageContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import { Activity, BarChart3, Building2, ChevronLeft, ChevronRight, CircleDollarSign, CreditCard, FileCheck2, Gauge, Landmark, Layers3, LayoutDashboard, LogOut, Menu, ShieldCheck, SlidersHorizontal, Tag, Users, WalletCards, X } from 'lucide-react';
import { toast } from 'sonner';

const labels = {
  en: { dashboard: 'Dashboard', users: 'Users', organizations: 'Organizations', subscriptions: 'Subscriptions', plans: 'Plans', promotions: 'Promotions', payments: 'Payments', access: 'Feature access', reports: 'Reports', activity: 'Activity logs', settings: 'Settings', signOut: 'Sign out', search: 'Search', pending: 'Pending', approve: 'Approve', reject: 'Reject', suspend: 'Suspend', activate: 'Activate', extend: 'Extend trial', noData: 'No records found.', total: 'Total', view: 'View', save: 'Save', revenue: 'Revenue', active: 'Active', trial: 'Trial', expired: 'Expired', cancelled: 'Cancelled', platform: 'Platform Owner', range: 'Live platform totals', page: 'Page', review: 'Payment review', reason: 'Reason (optional)', confirm: 'Confirm', close: 'Close', loading: 'Loading control plane…' },
  fa: { dashboard: 'داشبورد', users: 'کاربران', organizations: 'سازمان‌ها', subscriptions: 'اشتراک‌ها', plans: 'پلن‌ها', promotions: 'پروموشن‌ها', payments: 'پرداخت‌ها', access: 'دسترسی ویژگی', reports: 'گزارش‌ها', activity: 'گزارش فعالیت', settings: 'تنظیمات', signOut: 'خروج', search: 'جستجو', pending: 'در انتظار', approve: 'تأیید', reject: 'رد', suspend: 'تعلیق', activate: 'فعال‌سازی', extend: 'تمدید آزمایشی', noData: 'رکوردی یافت نشد.', total: 'کل', view: 'نمایش', save: 'ذخیره', revenue: 'درآمد', active: 'فعال', trial: 'آزمایشی', expired: 'منقضی', cancelled: 'لغو شده', platform: 'مالک پلتفرم', range: 'مجموع زنده پلتفرم', page: 'صفحه', review: 'بررسی پرداخت', reason: 'دلیل (اختیاری)', confirm: 'تأیید', close: 'بستن', loading: 'در حال بارگذاری کنترل پلتفرم…' },
  ar: { dashboard: 'لوحة التحكم', users: 'المستخدمون', organizations: 'المنظمات', subscriptions: 'الاشتراكات', plans: 'الخطط', promotions: 'العروض', payments: 'المدفوعات', access: 'وصول الميزات', reports: 'التقارير', activity: 'سجل النشاط', settings: 'الإعدادات', signOut: 'تسجيل الخروج', search: 'بحث', pending: 'معلق', approve: 'موافقة', reject: 'رفض', suspend: 'تعليق', activate: 'تفعيل', extend: 'تمديد التجربة', noData: 'لا توجد سجلات.', total: 'الإجمالي', view: 'عرض', save: 'حفظ', revenue: 'الإيراد', active: 'نشط', trial: 'تجريبي', expired: 'منتهي', cancelled: 'ملغى', platform: 'مالك المنصة', range: 'إجماليات المنصة المباشرة', page: 'صفحة', review: 'مراجعة الدفع', reason: 'السبب (اختياري)', confirm: 'تأكيد', close: 'إغلاق', loading: 'جارٍ تحميل مركز التحكم…' },
};
const nav = [
  ['dashboard', LayoutDashboard], ['users', Users], ['organizations', Building2], ['subscriptions', Layers3], ['plans', SlidersHorizontal], ['promotions', Tag], ['payments', WalletCards], ['access', ShieldCheck], ['reports', BarChart3], ['activity', Activity], ['settings', Landmark],
];
const LIMIT = 25;
const currency = (cents) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format((Number(cents) || 0) / 100);
const statusClass = (value) => ({ ACTIVE: 'bg-emerald-100 text-emerald-700', TRIAL: 'bg-sky-100 text-sky-700', EXPIRED: 'bg-slate-200 text-slate-700', CANCELED: 'bg-rose-100 text-rose-700', SUSPENDED: 'bg-amber-100 text-amber-700', PENDING_PAYMENT: 'bg-violet-100 text-violet-700', paid: 'bg-emerald-100 text-emerald-700', pending: 'bg-violet-100 text-violet-700', rejected: 'bg-rose-100 text-rose-700' }[value] || 'bg-slate-100 text-slate-700');

function Stat({ icon: Icon, label, value, tone = 'cyan' }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`mb-3 grid size-9 place-items-center rounded-xl bg-${tone}-50 text-${tone}-600`}><Icon className="size-5" /></div><p className="text-2xl font-black tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs font-medium text-slate-500">{label}</p></div>; }
function Empty({ text }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">{text}</div>; }
function Pager({ result, page, setPage, t }) { const total = result?.total || 0; return <div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{t.total}: {total}</span><span className="flex items-center gap-2"><Button size="icon" variant="outline" disabled={!page} onClick={() => setPage(page - 1)}><ChevronLeft className="size-4" /></Button>{t.page} {page + 1}<Button size="icon" variant="outline" disabled={(page + 1) * LIMIT >= total} onClick={() => setPage(page + 1)}><ChevronRight className="size-4" /></Button></span></div>; }

function Sidebar({ active, setActive, t, close }) { return <aside className="flex h-full w-72 flex-col bg-slate-950 p-4 text-slate-300"><div className="mb-8 flex items-center justify-between px-2"><div className="flex items-center gap-3 font-black text-white"><span className="grid size-9 place-items-center rounded-xl bg-cyan-400 text-slate-950"><ShieldCheck className="size-5" /></span> RestoCTRL</div><button className="lg:hidden" onClick={close}><X /></button></div><p className="mb-3 px-3 text-[11px] font-bold uppercase tracking-[.16em] text-cyan-300">{t.platform}</p><nav className="space-y-1">{nav.map(([key, Icon]) => <button key={key} onClick={() => { setActive(key); close?.(); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${active === key ? 'bg-cyan-400 text-slate-950' : 'hover:bg-slate-800 hover:text-white'}`}><Icon className="size-4" />{t[key]}</button>)}</nav><div className="mt-auto rounded-xl border border-slate-800 p-3 text-xs leading-5 text-slate-400">Separate platform control plane. Customer tenant navigation is never mounted here.</div></aside>; }

export default function PlatformOwnerPortal() {
  const { lang, setLang, dir } = useLanguage(); const t = labels[lang] || labels.en; const navigate = useNavigate(); const client = useQueryClient();
  const [active, setActive] = useState('dashboard'); const [drawer, setDrawer] = useState(false); const [page, setPage] = useState(0); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [review, setReview] = useState(null); const [action, setAction] = useState(null); const [promotionOpen, setPromotionOpen] = useState(false); const [promotion, setPromotion] = useState({ name: '', planId: 'growth_40', percentOff: 50, startsAt: '', endsAt: '', couponCode: '', isActive: true }); const [settings, setSettings] = useState({ iban: '', bankName: '', beneficiaryName: '', instructions: '', currency: 'USD', isActive: false });
  const snapshot = useQuery({ queryKey: ['platform-owner', 'snapshot'], queryFn: platformOwnerApi.snapshot, retry: false });
  const dashboard = useQuery({ queryKey: ['platform-owner', 'dashboard'], queryFn: platformOwnerApi.dashboard, enabled: active === 'dashboard' });
  const organizations = useQuery({ queryKey: ['platform-owner', 'organizations', search, status, page], queryFn: () => platformOwnerApi.organizations(search, status, LIMIT, page * LIMIT), enabled: active === 'organizations' });
  const users = useQuery({ queryKey: ['platform-owner', 'users', search, status, page], queryFn: () => platformOwnerApi.users(search, status, LIMIT, page * LIMIT), enabled: active === 'users' });
  const subscriptions = useQuery({ queryKey: ['platform-owner', 'subscriptions', status, page], queryFn: () => platformOwnerApi.subscriptions(status, LIMIT, page * LIMIT), enabled: active === 'subscriptions' });
  const payments = useQuery({ queryKey: ['platform-owner', 'payments', status, page], queryFn: () => platformOwnerApi.payments(status, LIMIT, page * LIMIT), enabled: active === 'payments' });
  const plans = useQuery({ queryKey: ['platform-owner', 'plans'], queryFn: platformOwnerApi.plans, enabled: active === 'plans' || active === 'promotions' });
  const promotions = useQuery({ queryKey: ['platform-owner', 'promotions', page], queryFn: () => platformOwnerApi.promotions(LIMIT, page * LIMIT), enabled: active === 'promotions' });
  const activity = useQuery({ queryKey: ['platform-owner', 'activity', page], queryFn: () => platformOwnerApi.activity(LIMIT, page * LIMIT), enabled: active === 'activity' });
  const invalidate = () => client.invalidateQueries({ queryKey: ['platform-owner'] });
  const mutation = useMutation({ mutationFn: ({ fn, args }) => fn(...args), onSuccess: () => { toast.success('Saved to the canonical platform backend.'); invalidate(); setReview(null); setAction(null); }, onError: (error) => toast.error(error.message || 'The platform operation could not be completed.') });
  React.useEffect(() => { setPage(0); setStatus(''); setSearch(''); }, [active]);
  React.useEffect(() => { if (snapshot.isSuccess && (!snapshot.data?.authorized || (snapshot.data.mfa_required && !snapshot.data.mfa_verified))) { supabase.auth.signOut().finally(() => navigate('/platform-owner/login', { replace: true })); } }, [snapshot.isSuccess, snapshot.data, navigate]);
  const logout = async () => { await supabase.auth.signOut(); navigate('/platform-owner/login', { replace: true }); };
  if (snapshot.isLoading) return <div className="grid min-h-screen place-items-center bg-slate-950 text-slate-300">{t.loading}</div>;
  if (!snapshot.data?.authorized || (snapshot.data.mfa_required && !snapshot.data.mfa_verified)) return null;
  const renderTableHead = (items, columns) => <><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map((column) => <th key={column} className="p-3 font-bold">{column}</th>)}</tr></thead><tbody>{items.map}</tbody></table></div></>;
  const cards = (data, make) => <div className="grid gap-3 md:hidden">{data.map(make)}</div>;
  const data = dashboard.data || {};
  let content;
  if (active === 'dashboard') content = <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black text-slate-950">{t.dashboard}</h1><p className="mt-1 text-sm text-slate-500">{t.range}</p></div><Badge className="bg-cyan-100 text-cyan-800">Server-validated aggregates</Badge></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Users} label="Total users" value={data.total_users ?? '—'} /><Stat icon={Building2} label="Organizations" value={data.total_organizations ?? '—'} tone="violet" /><Stat icon={Layers3} label="Active subscriptions" value={data.active_subscriptions ?? '—'} tone="emerald" /><Stat icon={WalletCards} label="Pending payments" value={data.pending_payments ?? '—'} tone="amber" /><Stat icon={CircleDollarSign} label="MRR" value={currency(data.monthly_recurring_revenue_cents)} tone="emerald" /><Stat icon={CreditCard} label="Monthly revenue" value={currency(data.monthly_revenue_cents)} tone="cyan" /><Stat icon={Tag} label="Active promotions" value={data.active_promotions ?? '—'} tone="violet" /><Stat icon={Gauge} label="Trial conversion" value={`${data.trial_conversion_rate ?? 0}%`} tone="amber" /></div><section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-950">Subscription health</h2><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div><p className="text-2xl font-black">{data.trial_users ?? 0}</p><p className="text-xs text-slate-500">Trials</p></div><div><p className="text-2xl font-black">{data.expired_subscriptions ?? 0}</p><p className="text-xs text-slate-500">Expired</p></div><div><p className="text-2xl font-black">{data.cancelled_subscriptions ?? 0}</p><p className="text-xs text-slate-500">Cancelled</p></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-950">Payment review queue</h2><p className="mt-3 text-4xl font-black text-violet-700">{data.pending_payments ?? 0}</p><p className="mt-1 text-sm text-slate-500">Manual transfers awaiting verified review.</p><Button className="mt-4" onClick={() => setActive('payments')}>Open payment center</Button></div></section></div>;
  else if (active === 'organizations') { const list = organizations.data?.items || []; content = <EntityPage title={t.organizations} search={search} setSearch={setSearch} status={status} setStatus={setStatus} t={t} loading={organizations.isLoading} empty={t.noData}>{renderTableHead(list, ['Organization', 'Portal', 'Plan', 'Subscription', 'Branches', 'Users', 'Action'])}{cards(list, (item) => <OrgCard key={item.id} item={item} t={t} onAction={setAction} />)}<div className="hidden md:block"><table className="w-full -mt-[1px] text-left text-sm"><tbody>{list.map((item) => <tr className="border border-slate-200 bg-white" key={item.id}><td className="p-3 font-semibold">{item.name}</td><td className="p-3 capitalize">{item.business_mode}</td><td className="p-3">{item.plan}</td><td className="p-3"><Badge className={statusClass(item.subscription_status)}>{item.subscription_status}</Badge></td><td className="p-3">{item.branch_count}</td><td className="p-3">{item.user_count}</td><td className="p-3"><Button size="sm" variant="outline" onClick={() => setAction({ type: item.is_active ? 'suspend-org' : 'activate-org', item })}>{item.is_active ? t.suspend : t.activate}</Button></td></tr>)}</tbody></table></div><Pager result={organizations.data} page={page} setPage={setPage} t={t} /></EntityPage>; }
  else if (active === 'users') { const list = users.data?.items || []; content = <EntityPage title={t.users} search={search} setSearch={setSearch} status={status} setStatus={setStatus} t={t} loading={users.isLoading} empty={t.noData}>{cards(list, (item) => <div key={item.id} className="rounded-2xl border bg-white p-4"><p className="font-bold">{item.full_name || '—'}</p><p className="text-sm text-slate-500">{item.email}</p><div className="mt-3 flex justify-between"><Badge>{item.role}</Badge><Button size="sm" variant="outline" onClick={() => setAction({ type: item.is_active ? 'suspend-user' : 'activate-user', item })}>{item.is_active ? t.suspend : t.activate}</Button></div></div>)}<div className="hidden overflow-x-auto rounded-2xl border bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{['User', 'Organization', 'Role', 'Plan', 'Subscription', 'Action'].map((head) => <th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{list.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="p-3"><p className="font-semibold">{item.full_name || '—'}</p><p className="text-xs text-slate-500">{item.email}</p></td><td className="p-3">{item.organization_name || '—'}</td><td className="p-3">{item.role}</td><td className="p-3">{item.plan || '—'}</td><td className="p-3"><Badge className={statusClass(item.subscription_status)}>{item.subscription_status || '—'}</Badge></td><td className="p-3"><Button size="sm" variant="outline" onClick={() => setAction({ type: item.is_active ? 'suspend-user' : 'activate-user', item })}>{item.is_active ? t.suspend : t.activate}</Button></td></tr>)}</tbody></table></div><Pager result={users.data} page={page} setPage={setPage} t={t} /></EntityPage>; }
  else if (active === 'subscriptions') { const list = subscriptions.data?.items || []; content = <EntityPage title={t.subscriptions} status={status} setStatus={setStatus} t={t} loading={subscriptions.isLoading} empty={t.noData}>{cards(list, (item) => <SubscriptionCard key={item.id} item={item} onAction={setAction} t={t} />)}<div className="hidden overflow-x-auto rounded-2xl border bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Organization', 'Plan', 'Status', 'Trial end', 'Next billing', 'Action'].map((head) => <th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{list.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="p-3 font-semibold">{item.organization_name}</td><td className="p-3">{item.plan_name}</td><td className="p-3"><Badge className={statusClass(item.subscription_status)}>{item.subscription_status}</Badge></td><td className="p-3">{item.trial_end || '—'}</td><td className="p-3">{item.current_period_end || '—'}</td><td className="p-3"><Button size="sm" variant="outline" onClick={() => setAction({ type: 'subscription', item })}>{t.view}</Button></td></tr>)}</tbody></table></div><Pager result={subscriptions.data} page={page} setPage={setPage} t={t} /></EntityPage>; }
  else if (active === 'payments') { const list = payments.data?.items || []; content = <EntityPage title={t.payments} status={status} setStatus={setStatus} t={t} loading={payments.isLoading} empty={t.noData}>{cards(list, (item) => <PaymentCard key={item.id} item={item} onReview={setReview} t={t} />)}<div className="hidden overflow-x-auto rounded-2xl border bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Organization', 'Plan', 'Amount', 'Reference', 'Proof', 'Status', 'Review'].map((head) => <th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{list.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="p-3 font-semibold">{item.organization_name}</td><td className="p-3">{item.plan_name}</td><td className="p-3">{currency(item.amount_cents)}</td><td className="p-3">{item.payment_reference || '—'}</td><td className="p-3">{item.payment_proof_filename || 'Not submitted'}</td><td className="p-3"><Badge className={statusClass(item.status)}>{item.status}</Badge></td><td className="p-3">{item.status === 'pending' && item.payment_proof_key ? <Button size="sm" onClick={() => setReview(item)}>{t.review}</Button> : '—'}</td></tr>)}</tbody></table></div><Pager result={payments.data} page={page} setPage={setPage} t={t} /></EntityPage>; }
  else if (active === 'plans') content = <div><Title title={t.plans} t={t} /><div className="grid gap-4 lg:grid-cols-3">{(plans.data || []).map((plan) => <div key={plan.id} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold text-cyan-700">{plan.display_name}</p><p className="mt-3 text-3xl font-black">{currency(plan.monthly_price_cents)}<span className="text-sm font-medium text-slate-500"> / month</span></p><p className="mt-3 text-sm text-slate-500">{plan.max_branches} branches · {plan.max_employees} employees · {plan.max_users} users</p><div className="mt-4 flex flex-wrap gap-1">{(plan.feature_flags || []).slice(0, 6).map((flag) => <Badge key={flag} variant="secondary">{flag}</Badge>)}</div></div>)}</div></div>;
  else if (active === 'promotions') { const list = promotions.data?.items || []; content = <div><div className="mb-5 flex items-center justify-between"><Title title={t.promotions} t={t} /><Button onClick={() => setPromotionOpen(true)}>Create promotion</Button></div>{list.length ? <div className="grid gap-3 md:grid-cols-2">{list.map((item) => <div key={item.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between"><p className="font-bold">{item.name}</p><Badge className={item.is_active ? 'bg-emerald-100 text-emerald-700' : ''}>{item.is_active ? 'Active' : 'Inactive'}</Badge></div><p className="mt-2 text-sm text-slate-500">{item.plan_name} · {item.percent_off ? `${item.percent_off}% off` : currency(item.fixed_amount_cents)}</p><p className="mt-2 text-xs text-slate-500">{item.starts_at} → {item.ends_at}</p></div>)}</div> : <Empty text={t.noData} />}<Pager result={promotions.data} page={page} setPage={setPage} t={t} /></div>; }
  else if (active === 'access') content = <FeatureAccess t={t} run={(restaurantId, feature, enabled, reason) => mutation.mutate({ fn: platformOwnerApi.featureOverride, args: [restaurantId, feature, enabled, reason] })} />;
  else if (active === 'settings') content = <div className="max-w-2xl"><Title title={t.settings} t={t} /><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Manual IBAN payment settings</h2><p className="mt-1 text-sm text-slate-500">Stored server-side and shown only through owner billing instructions.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['iban', 'IBAN'], ['bankName', 'Bank name'], ['beneficiaryName', 'Beneficiary name'], ['currency', 'Currency']].map(([key, label]) => <div key={key}><Label>{label}</Label><Input className="mt-2" value={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.value })} /></div>)}</div><div className="mt-4"><Label>Transfer instructions</Label><Textarea className="mt-2" value={settings.instructions} onChange={(event) => setSettings({ ...settings, instructions: event.target.value })} /></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.isActive} onChange={(event) => setSettings({ ...settings, isActive: event.target.checked })} />Enable manual IBAN payments</label><Button className="mt-5" onClick={() => mutation.mutate({ fn: platformOwnerApi.saveManualPaymentSettings, args: [settings] })}>{t.save}</Button></div></div>;
  else if (active === 'activity') { const list = activity.data?.items || []; content = <div><Title title={t.activity} t={t} />{list.length ? <div className="mt-5 space-y-3">{list.map((item) => <div key={item.id} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{item.action.replaceAll('_', ' ')}</p><span className="text-xs text-slate-500">{new Date(item.created_at).toLocaleString()}</span></div><p className="mt-2 text-sm text-slate-600">{item.actor_name || item.actor_email || 'Platform Owner'} · {item.organization_name || item.resource_type}</p></div>)}</div> : <Empty text={t.noData} />}<Pager result={activity.data} page={page} setPage={setPage} t={t} /></div>; }
  else content = <Reports dashboard={data} />;
  return <div className="min-h-screen bg-slate-50 text-slate-800" dir={dir}><div className="hidden fixed inset-y-0 start-0 lg:block"><Sidebar active={active} setActive={setActive} t={t} /></div><div className="lg:ps-72"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-white/95 px-4 backdrop-blur sm:px-7"><div className="flex items-center gap-3"><Sheet open={drawer} onOpenChange={setDrawer}><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden"><Menu /></Button></SheetTrigger><SheetContent side="left" className="w-72 border-0 p-0"><Sidebar active={active} setActive={setActive} t={t} close={() => setDrawer(false)} /></SheetContent></Sheet><div><p className="text-sm font-black text-slate-950">{t.platform}</p><p className="text-[11px] text-slate-500">Server-backed administration</p></div></div><div className="flex items-center gap-2"><select className="rounded-lg border bg-white px-2 py-1.5 text-sm" value={lang} onChange={(event) => setLang(event.target.value)}><option value="en">English</option><option value="fa">فارسی</option><option value="ar">العربية</option></select><Button variant="outline" size="sm" onClick={logout}><LogOut className="me-1 size-4" />{t.signOut}</Button></div></header><main className="mx-auto max-w-7xl p-4 sm:p-7">{content}</main></div><ReviewDialog item={review} t={t} pending={mutation.isPending} onClose={() => setReview(null)} onConfirm={(approve, note) => mutation.mutate({ fn: platformOwnerApi.reviewPayment, args: [review.id, approve, note] })} /><ActionDialog action={action} t={t} pending={mutation.isPending} onClose={() => setAction(null)} onConfirm={(reason) => { if (action.type.includes('user')) mutation.mutate({ fn: platformOwnerApi.setUserStatus, args: [action.item.id, action.type === 'suspend-user' ? 'suspended' : 'active', reason] }); else if (action.type.includes('org')) mutation.mutate({ fn: platformOwnerApi.setOrganizationStatus, args: [action.item.id, action.type === 'activate-org', reason] }); else mutation.mutate({ fn: platformOwnerApi.setSubscriptionStatus, args: [action.item.restaurant_id, 'suspend', reason] }); }} /><PromotionDialog open={promotionOpen} close={() => setPromotionOpen(false)} promotion={promotion} setPromotion={setPromotion} plans={plans.data || []} onSave={() => mutation.mutate({ fn: platformOwnerApi.savePromotion, args: [promotion] }, { onSuccess: () => setPromotionOpen(false) })} /></div>;
}

function Title({ title, t }) { return <div><h1 className="text-2xl font-black text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-500">{t.range}</p></div>; }
function EntityPage({ title, search, setSearch, status, setStatus, t, loading, empty, children }) { return <div><Title title={title} t={t} /><div className="my-5 flex flex-col gap-3 sm:flex-row"><Input value={search || ''} onChange={(event) => setSearch?.(event.target.value)} placeholder={t.search} className="sm:max-w-md" /><select className="rounded-lg border bg-white px-3 py-2 text-sm" value={status || ''} onChange={(event) => setStatus?.(event.target.value)}><option value="">All statuses</option><option value="TRIAL">TRIAL</option><option value="ACTIVE">ACTIVE</option><option value="PENDING_PAYMENT">PENDING_PAYMENT</option><option value="EXPIRED">EXPIRED</option><option value="CANCELED">CANCELED</option><option value="SUSPENDED">SUSPENDED</option></select></div>{loading ? <Empty text="Loading…" /> : React.Children.count(children) ? children : <Empty text={empty} />}</div>; }
function OrgCard({ item, t, onAction }) { return <div className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{item.name}</p><p className="text-sm text-slate-500 capitalize">{item.business_mode} · {item.branch_count} branches</p></div><Badge className={statusClass(item.subscription_status)}>{item.subscription_status}</Badge></div><div className="mt-3 flex justify-between"><span className="text-sm">{item.plan}</span><Button size="sm" variant="outline" onClick={() => onAction({ type: item.is_active ? 'suspend-org' : 'activate-org', item })}>{item.is_active ? t.suspend : t.activate}</Button></div></div>; }
function SubscriptionCard({ item, t, onAction }) { return <div className="rounded-2xl border bg-white p-4"><div className="flex justify-between"><p className="font-bold">{item.organization_name}</p><Badge className={statusClass(item.subscription_status)}>{item.subscription_status}</Badge></div><p className="mt-2 text-sm text-slate-500">{item.plan_name} · Next: {item.current_period_end || '—'}</p><Button className="mt-3" size="sm" variant="outline" onClick={() => onAction({ type: 'subscription', item })}>{t.view}</Button></div>; }
function PaymentCard({ item, t, onReview }) { return <div className="rounded-2xl border bg-white p-4"><div className="flex justify-between"><p className="font-bold">{item.organization_name}</p><Badge className={statusClass(item.status)}>{item.status}</Badge></div><p className="mt-2 text-sm text-slate-500">{item.plan_name} · {currency(item.amount_cents)}</p><p className="mt-1 text-xs text-slate-500">{item.payment_proof_filename || 'No proof submitted'}</p>{item.status === 'pending' && item.payment_proof_key && <Button className="mt-3" size="sm" onClick={() => onReview(item)}>{t.review}</Button>}</div>; }
function Reports({ dashboard }) { return <div><h1 className="text-2xl font-black">Platform reports</h1><p className="mt-1 text-sm text-slate-500">Current canonical aggregates. PDF, CSV, and Excel exports can be generated from these bounded server-side queries.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><Stat icon={CircleDollarSign} label="Total revenue" value={currency(dashboard.total_revenue_cents)} tone="emerald" /><Stat icon={BarChart3} label="Active subscriptions" value={dashboard.active_subscriptions ?? 0} tone="cyan" /><Stat icon={Users} label="New users today" value={dashboard.new_users ?? 0} tone="violet" /></div></div>; }
function FeatureAccess({ t, run }) { const [restaurantId, setRestaurantId] = useState(''); const [feature, setFeature] = useState('driver_analytics'); const [enabled, setEnabled] = useState(true); const [reason, setReason] = useState(''); return <div className="max-w-xl"><Title title={t.access} t={t} /><div className="mt-5 rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Feature overrides are organization-specific and are evaluated by the existing server-side entitlement guard.</p><div className="mt-4 space-y-4"><div><Label>Organization ID</Label><Input className="mt-2" value={restaurantId} onChange={(event) => setRestaurantId(event.target.value)} /></div><div><Label>Feature key</Label><Input className="mt-2" value={feature} onChange={(event) => setFeature(event.target.value)} /></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} />Enabled for this organization</label><Textarea placeholder={t.reason} value={reason} onChange={(event) => setReason(event.target.value)} /><Button onClick={() => run(restaurantId, feature, enabled, reason)}>{t.save}</Button></div></div></div>; }
function ReviewDialog({ item, t, pending, onClose, onConfirm }) { const [note, setNote] = useState(''); React.useEffect(() => setNote(''), [item?.id]); return <Dialog open={!!item} onOpenChange={onClose}><DialogContent><DialogHeader><DialogTitle>{t.review}</DialogTitle></DialogHeader><p className="text-sm text-slate-500">{item?.organization_name} · {item?.plan_name} · {currency(item?.amount_cents)}</p><Textarea placeholder={t.reason} value={note} onChange={(event) => setNote(event.target.value)} /><div className="flex gap-2"><Button className="flex-1 bg-emerald-600 hover:bg-emerald-700" disabled={pending} onClick={() => onConfirm(true, note)}>{t.approve}</Button><Button className="flex-1" variant="destructive" disabled={pending} onClick={() => onConfirm(false, note)}>{t.reject}</Button></div></DialogContent></Dialog>; }
function ActionDialog({ action, t, pending, onClose, onConfirm }) { const [reason, setReason] = useState(''); React.useEffect(() => setReason(''), [action?.type]); return <Dialog open={!!action} onOpenChange={onClose}><DialogContent><DialogHeader><DialogTitle>{action?.type?.replaceAll('-', ' ')}</DialogTitle></DialogHeader><p className="text-sm text-slate-500">{action?.item?.name || action?.item?.full_name || action?.item?.organization_name}</p><Textarea placeholder={t.reason} value={reason} onChange={(event) => setReason(event.target.value)} /><div className="flex gap-2"><Button className="flex-1" disabled={pending} onClick={() => onConfirm(reason)}>{t.confirm}</Button><Button className="flex-1" variant="outline" onClick={onClose}>{t.close}</Button></div></DialogContent></Dialog>; }
function PromotionDialog({ open, close, promotion, setPromotion, plans, onSave }) { return <Dialog open={open} onOpenChange={close}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Create limited-time promotion</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Name</Label><Input value={promotion.name} onChange={(event) => setPromotion({ ...promotion, name: event.target.value })} /></div><div><Label>Plan</Label><select className="mt-2 w-full rounded-lg border p-2" value={promotion.planId} onChange={(event) => setPromotion({ ...promotion, planId: event.target.value })}>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.display_name}</option>)}</select></div><div><Label>Percent off</Label><Input type="number" value={promotion.percentOff} onChange={(event) => setPromotion({ ...promotion, percentOff: event.target.value, fixedAmountCents: '' })} /></div><div><Label>Coupon code (optional)</Label><Input value={promotion.couponCode} onChange={(event) => setPromotion({ ...promotion, couponCode: event.target.value })} /></div><div className="grid grid-cols-2 gap-3"><div><Label>Starts</Label><Input type="datetime-local" value={promotion.startsAt} onChange={(event) => setPromotion({ ...promotion, startsAt: event.target.value })} /></div><div><Label>Ends</Label><Input type="datetime-local" value={promotion.endsAt} onChange={(event) => setPromotion({ ...promotion, endsAt: event.target.value })} /></div></div><Button onClick={onSave}>Save promotion</Button></div></DialogContent></Dialog>; }
